# Translation dictionaries
TRANSLATIONS = {
    'en': {
        'app_title': 'Salah Times',
        'next_prayer': 'NEXT PRAYER',
        'tomorrow': 'Tomorrow',
        'loading': '🔄 Loading prayer times...',
        'refresh': '↻ Refresh',
        'error': '⚠️ Error: {}\n\nPlease check your internet connection\nand try refreshing.',
        'welcome': '🕌 Welcome to Salah Times',
        'select_city': 'Please select your default city for prayer times:',
        'select_country': 'Please select your country first, then your city:',
        'search_city': 'Search for a city...',
        'search_country_city': 'Search country or city...',
        'back': '< Back',
        'cancel': 'Cancel',
        'set_default': 'Set as Default',
        'change_city': 'Change Default City',
        'iqama_time': 'Time before Iqama of {}: {:02d}:{:02d}:{:02d}',
        'iqama_passed': 'Iqama of {}: 00:00:00',
        'hijri_unavailable': 'Hijri date unavailable',
        'hijri_approx': '{} AH (Approximate)',
        'morocco': 'Morocco',
        'months': ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        'days': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        'hijri_months': {'Muharram': 'Muharram', 'Safar': 'Safar', 'Rabi\'al-awwal': 'Rabi al-Awwal', 'Rabi\'al-thani': 'Rabi al-Thani', 'Jumada al-awwal': 'Jumada al-Awwal', 'Jumada al-thani': 'Jumada al-Thani', 'Rajab': 'Rajab', 'Sha\'ban': 'Shaban', 'Ramadan': 'Ramadan', 'Shawwal': 'Shawwal', 'Dhu al-Qi\'dah': 'Dhu al-Qidah', 'Dhu al-Hijjah': 'Dhu al-Hijjah'},
        'language': 'Language',
        'settings': 'Settings',
        'monthly_calendar': 'Monthly Calendar',
        'weekly_schedule': 'Weekly Schedule',
        'refresh_db': '🗄️ Refresh DB',
        'refresh_db_updating': '⏳ Updating...',
        'refresh_db_prompt_title': 'Update Prayer Times',
        'refresh_db_prompt_msg': '30 days have passed since the last database update.\nRefresh all prayer times now?',
        'timezone_view': 'Multiple Timezones',
        'view': 'View',
        'tray_show': '🪟 Show Main Window',
        'tray_refresh': '↻ Refresh Prayer Times',
        'tray_quit': '❌ Quit',
        'no_internet_title': 'No Internet Connection',
        'no_internet_msg': 'Cannot update without an internet connection.\n\nCurrent database:\n• {} cities\n• From: {}\n• Until: {}',
        'prayers': {
            'Date': 'Date',
            'Fajr': 'Fajr',
            'Dohr': 'Dhuhr',
            'Asr': 'Asr',
            'Maghreb': 'Maghrib',
            'Isha': 'Isha'
        }
    },
    'ar': {
        'app_title': 'مواقيت الصلاة',
        'next_prayer': 'الصلاة القادمة',
        'tomorrow': 'غداً',
        'loading': '🔄 جاري تحميل مواقيت الصلاة...',
        'refresh': '↻ تحديث',
        'error': '⚠️ خطأ: {}\n\nيرجى التحقق من اتصال الإنترنت\nوإعادة المحاولة.',
        'welcome': '🕌 مرحباً بك في مواقيت الصلاة',
        'select_city': 'يرجى اختيار مدينتك الافتراضية لمواقيت الصلاة:',
        'select_country': 'يرجى اختيار البلد أولاً ثم مدينتك:',
        'search_city': 'البحث عن مدينة...',
        'search_country_city': 'البحث عن بلد أو مدينة...',
        'back': '< رجوع',
        'cancel': 'إلغاء',
        'set_default': 'تعيين كافتراضي',
        'change_city': 'تغيير المدينة الافتراضية',
        'iqama_time': 'الوقت المتبقي لإقامة {}: {:02d}:{:02d}:{:02d}',
        'iqama_passed': 'إقامة {}: 00:00:00',
        'hijri_unavailable': 'التاريخ الهجري غير متوفر',
        'hijri_approx': '{} هـ (تقريبي)',
        'morocco': 'المغرب',
        'months': ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'],
        'days': ['الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت', 'الأحد'],
        'hijri_months': {'Muharram': 'محرم', 'Safar': 'صفر', 'Rabi\'al-awwal': 'ربيع الأول', 'Rabi\'al-thani': 'ربيع الثاني', 'Jumada al-awwal': 'جمادى الأولى', 'Jumada al-thani': 'جمادى الثانية', 'Rajab': 'رجب', 'Sha\'ban': 'شعبان', 'Ramadan': 'رمضان', 'Shawwal': 'شوال', 'Dhu al-Qi\'dah': 'ذو القعدة', 'Dhu al-Hijjah': 'ذو الحجة'},
        'language': 'اللغة',
        'settings': 'الإعدادات',
        'monthly_calendar': 'التقويم الشهري',
        'weekly_schedule': 'الجدول الأسبوعي',
        'refresh_db': '🗄️ تحديث قاعدة البيانات',
        'refresh_db_updating': '⏳ جاري التحديث...',
        'refresh_db_prompt_title': 'تحديث مواقيت الصلاة',
        'refresh_db_prompt_msg': 'مرّ 30 يوماً منذ آخر تحديث لقاعدة البيانات.\nهل تريد تحديث مواقيت الصلاة الآن؟',
        'timezone_view': 'مناطق زمنية متعددة',
        'view': 'عرض',
        'tray_show': '🪟 عرض النافذة الرئيسية',
        'tray_refresh': '↻ تحديث مواقيت الصلاة',
        'tray_quit': '❌ خروج',
        'no_internet_title': 'لا يوجد اتصال بالإنترنت',
        'no_internet_msg': 'لا يمكن التحديث بدون اتصال بالإنترنت.\n\nقاعدة البيانات الحالية:\n• {} مدينة\n• من: {}\n• حتى: {}',
        'prayers': {
            'Date': 'التاريخ',
            'Fajr': 'الفجر',
            'Dohr': 'الظهر',
            'Asr': 'العصر',
            'Maghreb': 'المغرب',
            'Isha': 'العشاء'
        }
    },
    'fr': {
        'app_title': 'Horaires de Priere',
        'next_prayer': 'PROCHAINE PRIERE',
        'tomorrow': 'Demain',
        'loading': '🔄 Chargement des horaires de priere...',
        'refresh': '↻ Actualiser',
        'error': '⚠️ Erreur: {}\n\nVeuillez verifier votre connexion Internet\net reessayer.',
        'welcome': '🕌 Bienvenue dans Horaires de Priere',
        'select_city': 'Veuillez selectionner votre ville par defaut pour les horaires de priere:',
        'select_country': 'Veuillez sélectionner votre pays, puis votre ville :',
        'search_city': 'Rechercher une ville...',
        'search_country_city': 'Rechercher un pays ou une ville...',
        'back': '< Retour',
        'cancel': 'Annuler',
        'set_default': 'Definir par defaut',
        'change_city': 'Changer la ville par defaut',
        'iqama_time': 'Temps avant Iqama de {}: {:02d}:{:02d}:{:02d}',
        'iqama_passed': 'Iqama de {}: 00:00:00',
        'hijri_unavailable': 'Date hijri non disponible',
        'hijri_approx': '{} AH (Approximatif)',
        'morocco': 'Maroc',
        'months': ['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Aout', 'Septembre', 'Octobre', 'Novembre', 'Decembre'],
        'days': ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'],
        'hijri_months': {'Muharram': 'Muharram', 'Safar': 'Safar', 'Rabi\'al-awwal': 'Rabi al-Awwal', 'Rabi\'al-thani': 'Rabi al-Thani', 'Jumada al-awwal': 'Jumada al-Awwal', 'Jumada al-thani': 'Jumada al-Thani', 'Rajab': 'Rajab', 'Sha\'ban': 'Shaban', 'Ramadan': 'Ramadan', 'Shawwal': 'Shawwal', 'Dhu al-Qi\'dah': 'Dhu al-Qidah', 'Dhu al-Hijjah': 'Dhu al-Hijjah'},
        'language': 'Langue',
        'settings': 'Parametres',
        'monthly_calendar': 'Calendrier Mensuel',
        'weekly_schedule': 'Horaire Hebdomadaire',
        'refresh_db': '🗄️ Actualiser BD',
        'refresh_db_updating': '⏳ Mise a jour...',
        'refresh_db_prompt_title': 'Mise a jour des horaires',
        'refresh_db_prompt_msg': '30 jours se sont ecoules depuis la derniere mise a jour.\nActualiser les horaires de priere maintenant?',
        'timezone_view': 'Fuseaux Horaires Multiples',
        'view': 'Affichage',
        'tray_show': '🪟 Afficher la fenetre',
        'tray_refresh': '↻ Actualiser les horaires',
        'tray_quit': '❌ Quitter',
        'no_internet_title': 'Pas de connexion Internet',
        'no_internet_msg': 'Impossible de mettre a jour sans connexion.\n\nBase de donnees actuelle:\n• {} villes\n• Du: {}\n• Au: {}',
        'prayers': {
            'Date': 'Date',
            'Fajr': 'Fajr',
            'Dohr': 'Dhuhr',
            'Asr': 'Asr',
            'Maghreb': 'Maghrib',
            'Isha': 'Isha'
        }
    }
}

CITY_SLUGS = {
    'Agadir': 'agadir', 'Al Hoceima': 'al-hoceima', 'Assila': 'assila',
    'Beni Mellal': 'beni-mellal', 'Berkane': 'berkane', 'Boulemane': 'boulemane',
    'Casablanca': 'casablanca', 'Chefchaouen': 'chefchaouen', 'Dakhla': 'dakhla',
    'El Jadida': 'el-jadida', 'Errachidia': 'errachidia', 'Essaouira': 'essaouira',
    'Fes': 'fes', 'Ifrane': 'ifrane', 'Kalaat Sraghna': 'kalaat-sraghna',
    'Kenitra': 'kenitra', 'Khenifra': 'khenifra', 'Khouribga': 'khouribga',
    'Ksar Lekbir': 'ksar-lekbir', 'Laayoune': 'laayoune', 'Lagouira': 'lagouira',
    'Larache': 'larache', 'Marrakech': 'marrakech', 'Meknes': 'meknes',
    'Mohammedia': 'mohammedia', 'Moulay Idriss Zerhoun': 'moulay-idriss-zerhoun',
    'Nador': 'nador', 'Ouazzane': 'ouazzane', 'Oujda': 'oujda', 'Rabat': 'rabat',
    'Safi': 'safi', 'Sefrou': 'sefrou', 'Settat': 'settat', 'Sidi Kacem': 'sidi-kacem',
    'Smara': 'smara', 'Tan Tan': 'tan-tan', 'Tangier': 'tanger', 'Taounate': 'taounate',
    'Taroudant': 'taroudant', 'Taza': 'taza', 'Tetouan': 'tetouan', 'Tiznit': 'tiznit',
    'Zagora': 'zagora',
    # ── new countries (2026-09 yabiladi expansion) ──
    'Boksburg': 'boksburg',
    'Durban': 'durban',
    'Germiston': 'germiston',
    'Johannesburg': 'johannesburg',
    'Le Cap': 'le-cap',
    'Pretoria': 'pretoria',
    'Alger': 'alger',
    'Annaba': 'annaba',
    'Batna': 'batna',
    'Bir El Djir': 'bir-el-djir',
    'Biskra': 'biskra',
    'Blida': 'blida',
    'Bordj Bou Arreridj': 'bordj-bou-arreridj',
    'Béchar': 'bechar',
    'Béjaïa': 'bejaia',
    'Chlef': 'chlef',
    'Constantine': 'constantine',
    'Djelfa': 'djelfa',
    'El Eulma': 'el-eulma',
    'El Khroub': 'el-khroub',
    'El Oued': 'el-oued',
    'Jijel': 'jijel',
    'Laghouat': 'laghouat',
    "M'Sila": 'm-sila',
    'Mostaganem': 'mostaganem',
    'Médéa': 'medea',
    'Oran': 'oran',
    'Ouargla': 'ouargla',
    'Sidi bel Abbès': 'sidi-bel-abbes',
    'Skikda': 'skikda',
    'Souk Ahras': 'souk-ahras',
    'Sétif': 'setif',
    'Tiaret': 'tiaret',
    'Tizi Ouzou': 'tizi-ouzou',
    'Tlemcen': 'tlemcen',
    'Tébessa': 'tebessa',
    'Berlin': 'berlin',
    'Bielefeld': 'bielefeld',
    'Bochum': 'bochum',
    'Bonn': 'bonn',
    'Brême': 'breme',
    'Cologne': 'cologne',
    'Dortmund': 'dortmund',
    'Dresde': 'dresde',
    'Duisbourg': 'duisbourg',
    'Düsseldorf': 'dusseldorf',
    'Essen': 'essen',
    'Francfort': 'francfort',
    'Hambourg': 'hambourg',
    'Hanovre': 'hanovre',
    'Leipzig': 'leipzig',
    'Mannheim': 'mannheim',
    'Munich': 'munich',
    'Nuremberg': 'nuremberg',
    'Stuttgart': 'stuttgart',
    'Wuppertal': 'wuppertal',
    'Djeddah': 'djeddah',
    'La Mecque': 'la-mecque',
    'Médine': 'medine',
    'Riyad': 'riyad',
    'Adélaïde': 'adelaide',
    'Brisbane': 'brisbane',
    'Canberra': 'canberra',
    'Geelong': 'geelong',
    'Hobart': 'hobart',
    'Melbourne': 'melbourne',
    'Newcastle': 'newcastle',
    'Perth': 'perth',
    'Sydney': 'sydney',
    'Wollongong': 'wollongong',
    'Linz': 'linz',
    'Vienne': 'vienne',
    'Villach': 'villach',
    'Anvers': 'anvers',
    'Bruxelles': 'bruxelles',
    'Charleroi': 'charleroi',
    'Gand': 'gand',
    'Hasselt': 'hasselt',
    'Liège': 'liege',
    'Mons': 'mons',
    'Namur': 'namur',
    'Renaix': 'renaix',
    'Tournai': 'tournai',
    'Verviers': 'verviers',
    'Yaoundé': 'yaounde',
    'Montréal': 'montreal',
    'Ottawa': 'ottawa',
    'Québec': 'quebec',
    'Toronto': 'toronto',
    'Vancouver': 'vancouver',
    'Abidjan': 'abidjan',
    'Copenhague': 'copenhague',
    'Le Caire': 'le-caire',
    'Abou Dhabi': 'abou-dhabi',
    'Dubaï': 'dubai',
    'Albacete': 'albacete',
    'Alcalá de Henares': 'alcala-de-henares',
    'Alcorcón': 'alcorcon',
    'Algeciras': 'algeciras',
    'Alicante': 'alicante',
    'Almería': 'almeria',
    'Badajoz': 'badajoz',
    'Badalona': 'badalona',
    'Barcelona': 'barcelona',
    'Bilbao': 'bilbao',
    'Burgos': 'burgos',
    'Cartagena': 'cartagena',
    'Castellón de la Plana': 'castellon-de-la-plana',
    'Cádiz': 'cadiz',
    'Córdoba': 'cordoba',
    'Elche': 'elche',
    'Fuenlabrada': 'fuenlabrada',
    'Getafe': 'getafe',
    'Gijón': 'gijon',
    'Granada': 'granada',
    'Huelva': 'huelva',
    'Jaén': 'jaen',
    'Jerez de la Frontera': 'jerez-de-la-frontera',
    "L'hospitalet De Llobregat": 'l-hospitalet-de-llobregat',
    'La Coruña': 'la-coruna',
    'Las Palmas De Gran Canaria': 'las-palmas-de-gran-canaria',
    'Leganés': 'leganes',
    'León': 'leon',
    'Logroño': 'logrono',
    'Lérida': 'lerida',
    'Madrid': 'madrid',
    'Marbella': 'marbella',
    'Murcia': 'murcia',
    'Málaga': 'malaga',
    'Móstoles': 'mostoles',
    'Oviedo': 'oviedo',
    'Palma de Mallorca': 'palma-de-mallorca',
    'Pamplona': 'pamplona',
    'Reus': 'reus',
    'Sabadell': 'sabadell',
    'Salamanca': 'salamanca',
    'San Cristóbal de La Laguna': 'san-cristobal-de-la-laguna',
    'San Sebastián': 'san-sebastian',
    'Santa Cruz De Tenerife': 'santa-cruz-de-tenerife',
    'Santander': 'santander',
    'Sevilla': 'sevilla',
    'Tarifa': 'tarifa',
    'Tarragona': 'tarragona',
    'Terrassa': 'terrassa',
    'Valencia': 'valencia',
    'Valladolid': 'valladolid',
    'Vigo': 'vigo',
    'Vitoria': 'vitoria',
    'Zaragoza': 'zaragoza',
    'Anchorage': 'anchorage',
    'Atlanta': 'atlanta',
    'Chicago': 'chicago',
    'Dallas': 'dallas',
    'Denver': 'denver',
    'Détroit': 'detroit',
    'Honolulu': 'honolulu',
    'Houston': 'houston',
    'Los Angeles': 'los-angeles',
    'Miami': 'miami',
    'New York': 'new-york',
    'Seattle': 'seattle',
    'Washington': 'washington',
    'Espoo': 'espoo',
    'Helsinki': 'helsinki',
    'Turku': 'turku',
    'Vantaa': 'vantaa',
    'Albi': 'albi',
    'Amiens': 'amiens',
    'Angers': 'angers',
    'Angoulême': 'angouleme',
    'Annecy': 'annecy',
    'Arras': 'arras',
    'Auxerre': 'auxerre',
    'Avignon': 'avignon',
    'Bar-le-Duc': 'bar-le-duc',
    'Bayeux': 'bayeux',
    'Beauvais': 'beauvais',
    'Belfort': 'belfort',
    'Besançon': 'besancon',
    'Bordeaux': 'bordeaux',
    'Bourges': 'bourges',
    'Caen': 'caen',
    'Carcassonne': 'carcassonne',
    'Chalon sur Marne': 'chalon-sur-marne',
    'Chalon sur Saône': 'chalon-sur-saone',
    'Chambéry': 'chambery',
    'Charleville-Mézières': 'charleville-mezieres',
    'Chartres': 'chartres',
    'Chaumont': 'chaumont',
    'Cherbourg': 'cherbourg',
    'Cholet': 'cholet',
    'Château-Chinon': 'chateau-chinon',
    'Châtellerault': 'chatellerault',
    'Clermont-Ferrand': 'clermont-ferrand',
    'Dieppe': 'dieppe',
    'Dijon': 'dijon',
    'Douai': 'douai',
    'Draguignan': 'draguignan',
    'Epinal': 'epinal',
    'Foix': 'foix',
    'Forbach': 'forbach',
    'La Rochelle': 'la-rochelle',
    'Langres': 'langres',
    'Laval': 'laval',
    'Le Havre': 'le-havre',
    'Le Mans': 'le-mans',
    'Le Puy': 'le-puy',
    'Lens': 'lens',
    'Lille': 'lille',
    'Limoges': 'limoges',
    'Lyon': 'lyon',
    'Macon': 'macon',
    'Marseille': 'marseille',
    'Meaux': 'meaux',
    'Melun': 'melun',
    'Metz': 'metz',
    'Montluçon': 'montlucon',
    'Montpellier': 'montpellier',
    'Mulhouse': 'mulhouse',
    'Nancy': 'nancy',
    'Nantes': 'nantes',
    'Nevers': 'nevers',
    'Nice': 'nice',
    'Niort': 'niort',
    'Nogent sur Seine': 'nogent-sur-seine',
    'Nîmes': 'nimes',
    'Orléans': 'orleans',
    'Paris': 'paris',
    'Pau': 'pau',
    'Perpignan': 'perpignan',
    'Poitiers': 'poitiers',
    'Pontarlier': 'pontarlier',
    'Péronne': 'peronne',
    'Reims': 'reims',
    'Rennes': 'rennes',
    'Roanne': 'roanne',
    'Rodez': 'rodez',
    'Rouen': 'rouen',
    'Saint Etienne': 'saint-etienne',
    'Saint-Dizier': 'saint-dizier',
    'Saint-Dié': 'saint-die',
    'Strasbourg': 'strasbourg',
    'Thionville': 'thionville',
    'Toul': 'toul',
    'Toulon': 'toulon',
    'Toulouse': 'toulouse',
    'Tours': 'tours',
    'Troyes': 'troyes',
    'Valence': 'valence',
    'Valenciennes': 'valenciennes',
    'Verdun': 'verdun',
    'Vichy': 'vichy',
    'Accra': 'accra',
    'Kumasi': 'kumasi',
    'Sekondi': 'sekondi',
    'Takoradi': 'takoradi',
    'Tamale': 'tamale',
    'Tema': 'tema',
    'Bagdad': 'bagdad',
    'Dublin': 'dublin',
    'Bari': 'bari',
    'Bologna': 'bologna',
    'Cagliari': 'cagliari',
    'Catania': 'catania',
    'Firenze': 'firenze',
    'Genoa': 'genoa',
    'Milan': 'milan',
    'Napoli': 'napoli',
    'Palermo': 'palermo',
    'Roma': 'roma',
    'Turin': 'turin',
    'Venezia': 'venezia',
    'Verona': 'verona',
    'Fukuoka': 'fukuoka',
    'Hiroshima': 'hiroshima',
    'Kawasaki': 'kawasaki',
    'Kitakyushu': 'kitakyushu',
    'Kobe': 'kobe',
    'Kyoto': 'kyoto',
    'Nagoya': 'nagoya',
    'Osaka': 'osaka',
    'Sapporo': 'sapporo',
    'Tokyo': 'tokyo',
    'Beyrouth': 'beyrouth',
    'Tripoli': 'tripoli',
    'Bamako': 'bamako',
    'Nouakchott': 'nouakchott',
    'Ibadan': 'ibadan',
    'Ilesha': 'ilesha',
    'Ilorin': 'ilorin',
    'Kano': 'kano',
    'Lagos': 'lagos',
    'Onitsha': 'onitsha',
    'Zaria': 'zaria',
    'Oslo': 'oslo',
    'Auckland': 'auckland',
    'Dunedin': 'dunedin',
    'Hamilton': 'hamilton',
    'Wellington': 'wellington',
    'Almere': 'almere',
    'Amersfoort': 'amersfoort',
    'Amsterdam': 'amsterdam',
    'Apeldoorn': 'apeldoorn',
    'Arnhem': 'arnhem',
    'Bois-le-Duc': 'bois-le-duc',
    'Bréda': 'breda',
    'Eindhoven': 'eindhoven',
    'Enschede': 'enschede',
    'Groningue': 'groningue',
    'Haarlem': 'haarlem',
    'Haarlemmermeer': 'haarlemmermeer',
    'La Haye': 'la-haye',
    'Maastricht': 'maastricht',
    'Nimègue': 'nimegue',
    'Rotterdam': 'rotterdam',
    'Tilburg': 'tilburg',
    'Utrecht': 'utrecht',
    'Zaanstad': 'zaanstad',
    'Zoetermeer': 'zoetermeer',
    'Zwolle': 'zwolle',
    'Doha': 'doha',
    'Belfast': 'belfast',
    'Birmingham': 'birmingham',
    'Bristol': 'bristol',
    'Cardiff': 'cardiff',
    'Glasgow': 'glasgow',
    'Liverpool': 'liverpool',
    'London': 'london',
    'Manchester': 'manchester',
    'Sheffield': 'sheffield',
    'Dakar': 'dakar',
    'Borås': 'boras',
    'Malmö': 'malmo',
    'Stockholm': 'stockholm',
    'Uppsala': 'uppsala',
    'Örebro': 'orebro',
    'Berne': 'berne',
    'Bienne': 'bienne',
    'Bâle': 'bale',
    'Fribourg': 'fribourg',
    'Genève': 'geneve',
    'La Chaux-de-Fonds': 'la-chaux-de-fonds',
    'Lausanne': 'lausanne',
    'Lucerne': 'lucerne',
    'Lugano': 'lugano',
    'Montreux': 'montreux',
    'Neuchatel': 'neuchatel',
    'Saint-Gall': 'saint-gall',
    'Thoune': 'thoune',
    'Winterthour': 'winterthour',
    'Zurich': 'zurich',
    'Damas': 'damas',
    'Ariana': 'ariana',
    'Ben Arous': 'ben-arous',
    'Bizerte': 'bizerte',
    'Béja': 'beja',
    'Gabès': 'gabes',
    'Gafsa': 'gafsa',
    'Jendouba': 'jendouba',
    'Kairouan': 'kairouan',
    'Kasserine': 'kasserine',
    'Kébili': 'kebili',
    'La Manouba': 'la-manouba',
    'Le Kef': 'le-kef',
    'Mahdia': 'mahdia',
    'Monastir': 'monastir',
    'Médenine': 'medenine',
    'Nabeul': 'nabeul',
    'Sfax': 'sfax',
    'Sidi Bouzid': 'sidi-bouzid',
    'Siliana': 'siliana',
    'Sousse': 'sousse',
    'Tataouine': 'tataouine',
    'Tozeur': 'tozeur',
    'Tunis': 'tunis',
    'Zaghouan': 'zaghouan',
}

BASE_URL = 'https://www.yabiladi.com/prieres/details/{}/{}.html'
SCRAPER_HEADERS = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}

CITIES = {
    'Tangier': {'id': 101, 'en': 'Tangier', 'ar': 'طنجة', 'fr': 'Tanger', 'lat': 35.7595, 'lon': -5.8340, 'country': 'Maroc', 'es': 'Tánger'},
    'Casablanca': {'id': 71, 'en': 'Casablanca', 'ar': 'الدار البيضاء', 'fr': 'Casablanca', 'lat': 33.5731, 'lon': -7.5898, 'country': 'Maroc', 'es': 'Casablanca'},
    'Rabat': {'id': 95, 'en': 'Rabat', 'ar': 'الرباط', 'fr': 'Rabat', 'lat': 34.0209, 'lon': -6.8416, 'country': 'Maroc', 'es': 'Rabat'},
    'Marrakech': {'id': 88, 'en': 'Marrakech', 'ar': 'مراكش', 'fr': 'Marrakech', 'lat': 31.6295, 'lon': -7.9811, 'country': 'Maroc', 'es': 'Marrakech'},
    'Fes': {'id': 78, 'en': 'Fes', 'ar': 'فاس', 'fr': 'Fes', 'lat': 34.0181, 'lon': -5.0078, 'country': 'Maroc', 'es': 'Fez'},
    'Agadir': {'id': 66, 'en': 'Agadir', 'ar': 'أكادير', 'fr': 'Agadir', 'lat': 30.4278, 'lon': -9.5981, 'country': 'Maroc', 'es': 'Agadir'},
    'Meknes': {'id': 89, 'en': 'Meknes', 'ar': 'مكناس', 'fr': 'Meknes', 'lat': 33.8935, 'lon': -5.5473, 'country': 'Maroc', 'es': 'Mequínez'},
    'Oujda': {'id': 93, 'en': 'Oujda', 'ar': 'وجدة', 'fr': 'Oujda', 'lat': 34.6814, 'lon': -1.9086, 'country': 'Maroc', 'es': 'Oujda'},
    'Kenitra': {'id': 81, 'en': 'Kenitra', 'ar': 'القنيطرة', 'fr': 'Kenitra', 'lat': 34.2610, 'lon': -6.5802, 'country': 'Maroc', 'es': 'Kenitra'},
    'Tetouan': {'id': 100, 'en': 'Tetouan', 'ar': 'تطوان', 'fr': 'Tetouan', 'lat': 35.5889, 'lon': -5.3626, 'country': 'Maroc', 'es': 'Tetuán'},
    'Safi': {'id': 96, 'en': 'Safi', 'ar': 'آسفي', 'fr': 'Safi', 'lat': 32.2994, 'lon': -9.2372, 'country': 'Maroc', 'es': 'Safí'},
    'Mohammedia': {'id': 90, 'en': 'Mohammedia', 'ar': 'المحمدية', 'fr': 'Mohammedia', 'lat': 33.6866, 'lon': -7.3837, 'country': 'Maroc', 'es': 'Mohammedia'},
    'Khouribga': {'id': 83, 'en': 'Khouribga', 'ar': 'خريبكة', 'fr': 'Khouribga', 'lat': 32.8811, 'lon': -6.9063, 'country': 'Maroc', 'es': 'Juribga'},
    'El Jadida': {'id': 74, 'en': 'El Jadida', 'ar': 'الجديدة', 'fr': 'El Jadida', 'lat': 33.2316, 'lon': -8.5007, 'country': 'Maroc', 'es': 'El Yadida'},
    'Taza': {'id': 105, 'en': 'Taza', 'ar': 'تازة', 'fr': 'Taza', 'lat': 34.2133, 'lon': -4.0103, 'country': 'Maroc', 'es': 'Taza'},
    'Nador': {'id': 91, 'en': 'Nador', 'ar': 'الناظور', 'fr': 'Nador', 'lat': 35.1681, 'lon': -2.9287, 'country': 'Maroc', 'es': 'Nador'},
    'Settat': {'id': 98, 'en': 'Settat', 'ar': 'سطات', 'fr': 'Settat', 'lat': 33.0018, 'lon': -7.6164, 'country': 'Maroc', 'es': 'Settat'},
    'Larache': {'id': 87, 'en': 'Larache', 'ar': 'العرائش', 'fr': 'Larache', 'lat': 35.1932, 'lon': -6.1563, 'country': 'Maroc', 'es': 'Larache'},
    'Khenifra': {'id': 82, 'en': 'Khenifra', 'ar': 'خنيفرة', 'fr': 'Khenifra', 'lat': 32.9359, 'lon': -5.6675, 'country': 'Maroc', 'es': 'Jenifra'},
    'Essaouira': {'id': 76, 'en': 'Essaouira', 'ar': 'الصويرة', 'fr': 'Essaouira', 'lat': 31.5085, 'lon': -9.7595, 'country': 'Maroc', 'es': 'Esauira'},
    'Chefchaouen': {'id': 72, 'en': 'Chefchaouen', 'ar': 'شفشاون', 'fr': 'Chefchaouen', 'lat': 35.1688, 'lon': -5.2636, 'country': 'Maroc', 'es': 'Chauen'},
    'Beni Mellal': {'id': 68, 'en': 'Beni Mellal', 'ar': 'بني ملال', 'fr': 'Beni Mellal', 'lat': 32.3373, 'lon': -6.3498, 'country': 'Maroc', 'es': 'Beni Melal'},
    'Al Hoceima': {'id': 79, 'en': 'Al Hoceima', 'ar': 'الحسيمة', 'fr': 'Al Hoceima', 'lat': 35.2517, 'lon': -3.9316, 'country': 'Maroc', 'es': 'Alhucemas'},
    'Taroudant': {'id': 103, 'en': 'Taroudant', 'ar': 'تارودانت', 'fr': 'Taroudant', 'lat': 30.4703, 'lon': -8.8770, 'country': 'Maroc', 'es': 'Tarudant'},
    'Ouazzane': {'id': 92, 'en': 'Ouazzane', 'ar': 'وزان', 'fr': 'Ouazzane', 'lat': 34.7936, 'lon': -5.5836, 'country': 'Maroc', 'es': 'Uezán'},
    'Sefrou': {'id': 97, 'en': 'Sefrou', 'ar': 'صفرو', 'fr': 'Sefrou', 'lat': 33.8307, 'lon': -4.8372, 'country': 'Maroc', 'es': 'Sefrú'},
    'Berkane': {'id': 69, 'en': 'Berkane', 'ar': 'بركان', 'fr': 'Berkane', 'lat': 34.9218, 'lon': -2.3200, 'country': 'Maroc', 'es': 'Berkane'},
    'Errachidia': {'id': 75, 'en': 'Errachidia', 'ar': 'الراشيدية', 'fr': 'Errachidia', 'lat': 31.9314, 'lon': -4.4244, 'country': 'Maroc', 'es': 'Errachidía'},
    'Laayoune': {'id': 85, 'en': 'Laayoune', 'ar': 'العيون', 'fr': 'Laayoune', 'lat': 27.1253, 'lon': -13.1625, 'country': 'Maroc', 'es': 'El Aaiún'},
    'Tiznit': {'id': 106, 'en': 'Tiznit', 'ar': 'تزنيت', 'fr': 'Tiznit', 'lat': 29.6974, 'lon': -9.7316, 'country': 'Maroc', 'es': 'Tiznit'},
    'Ifrane': {'id': 80, 'en': 'Ifrane', 'ar': 'إفران', 'fr': 'Ifrane', 'lat': 33.5228, 'lon': -5.1106, 'country': 'Maroc', 'es': 'Ifrán'},
    'Zagora': {'id': 107, 'en': 'Zagora', 'ar': 'زاكورة', 'fr': 'Zagora', 'lat': 30.3314, 'lon': -5.8372, 'country': 'Maroc', 'es': 'Zagora'},
    'Dakhla': {'id': 73, 'en': 'Dakhla', 'ar': 'الداخلة', 'fr': 'Dakhla', 'lat': 23.6848, 'lon': -15.9570, 'country': 'Maroc', 'es': 'Dajla'},
    'Tan Tan': {'id': 102, 'en': 'Tan Tan', 'ar': 'طانطان', 'fr': 'Tan-Tan', 'lat': 28.4378, 'lon': -11.1031, 'country': 'Maroc', 'es': 'Tan-Tan'},
    'Sidi Kacem': {'id': 99, 'en': 'Sidi Kacem', 'ar': 'سيدي قاسم', 'fr': 'Sidi Kacem', 'lat': 34.2214, 'lon': -5.7081, 'country': 'Maroc', 'es': 'Sidi Kasem'},
    'Ksar Lekbir': {'id': 84, 'en': 'Ksar Lekbir', 'ar': 'القصر الكبير', 'fr': 'Ksar el-Kebir', 'lat': 35.0119, 'lon': -5.9033, 'country': 'Maroc', 'es': 'Alcazarquivir'},
    'Taounate': {'id': 104, 'en': 'Taounate', 'ar': 'تاونات', 'fr': 'Taounate', 'lat': 34.5386, 'lon': -4.6372, 'country': 'Maroc', 'es': 'Taounate'},
    'Assila': {'id': 67, 'en': 'Assila', 'ar': 'أصيلة', 'fr': 'Asilah', 'lat': 35.4650, 'lon': -6.0362, 'country': 'Maroc', 'es': 'Arcila'},
    'Boulemane': {'id': 70, 'en': 'Boulemane', 'ar': 'بولمان', 'fr': 'Boulemane', 'lat': 33.3614, 'lon': -4.7331, 'country': 'Maroc', 'es': 'Bulman'},
    'Kalaat Sraghna': {'id': 94, 'en': 'Kalaat Sraghna', 'ar': 'قلعة السراغنة', 'fr': 'Kalaat es-Sraghna', 'lat': 32.0587, 'lon': -7.4103, 'country': 'Maroc', 'es': 'El Kelaa'},
    'Lagouira': {'id': 86, 'en': 'Lagouira', 'ar': 'الكويرة', 'fr': 'Lagouira', 'lat': 20.9331, 'lon': -17.0439, 'country': 'Maroc', 'es': 'La Güera'},
    'Moulay Idriss Zerhoun': {'id': 108, 'en': 'Moulay Idriss Zerhoun', 'ar': 'مولاي إدريس زرهون', 'fr': 'Moulay Idriss Zerhoun', 'lat': 34.0581, 'lon': -5.5203, 'country': 'Maroc', 'es': 'Mulay Idrís Zerhún'},
    'Smara': {'id': 77, 'en': 'Smara', 'ar': 'السمارة', 'fr': 'Smara', 'lat': 26.7386, 'lon': -11.6719, 'country': 'Maroc', 'es': 'Esmara'},
    # ── Afrique du sud (6 villes) ──
    'Boksburg': {'id': 370, 'en': 'Boksburg', 'ar': 'بوكسبرغ', 'fr': 'Boksburg', 'lat': None, 'lon': None, 'country': 'Afrique du sud', 'es': 'Boksburg'},
    'Durban': {'id': 371, 'en': 'Durban', 'ar': 'ديربان', 'fr': 'Durban', 'lat': None, 'lon': None, 'country': 'Afrique du sud', 'es': 'Durban'},
    'Germiston': {'id': 369, 'en': 'Germiston', 'ar': 'جيرميستون', 'fr': 'Germiston', 'lat': None, 'lon': None, 'country': 'Afrique du sud', 'es': 'Germiston'},
    'Johannesburg': {'id': 374, 'en': 'Johannesburg', 'ar': 'جوهانسبرغ', 'fr': 'Johannesburg', 'lat': None, 'lon': None, 'country': 'Afrique du sud', 'es': 'Johannesburg'},
    'Le Cap': {'id': 372, 'en': 'Cape Town', 'ar': 'كيب تاون', 'fr': 'Le Cap', 'lat': None, 'lon': None, 'country': 'Afrique du sud', 'es': 'Ciudad del Cabo'},
    'Pretoria': {'id': 373, 'en': 'Pretoria', 'ar': 'بريتوريا', 'fr': 'Pretoria', 'lat': None, 'lon': None, 'country': 'Afrique du sud', 'es': 'Pretoria'},
    # ── Algérie (30 villes) ──
    'Alger': {'id': 2, 'en': 'Algiers', 'ar': 'الجزائر', 'fr': 'Alger', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Argel'},
    'Annaba': {'id': 280, 'en': 'Annaba', 'ar': 'عنابة', 'fr': 'Annaba', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Annaba'},
    'Batna': {'id': 277, 'en': 'Batna', 'ar': 'باتنة', 'fr': 'Batna', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Batna'},
    'Bir El Djir': {'id': 295, 'en': 'Bir El Djir', 'ar': 'بير الجير', 'fr': 'Bir El Djir', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Bir El Djir'},
    'Biskra': {'id': 282, 'en': 'Biskra', 'ar': 'بسكرة', 'fr': 'Biskra', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Biskra'},
    'Blida': {'id': 291, 'en': 'Blida', 'ar': 'البليدة', 'fr': 'Blida', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Blida'},
    'Bordj Bou Arreridj': {'id': 288, 'en': 'Bordj Bou Arreridj', 'ar': 'برج بوعريريج', 'fr': 'Bordj Bou Arreridj', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Bordj Bou Arreridj'},
    'Béchar': {'id': 289, 'en': 'Bechar', 'ar': 'بشار', 'fr': 'Béchar', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Béchar'},
    'Béjaïa': {'id': 287, 'en': 'Bejaia', 'ar': 'بجاية', 'fr': 'Béjaïa', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Béjaïa'},
    'Chlef': {'id': 286, 'en': 'Chlef', 'ar': 'الشلف', 'fr': 'Chlef', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Chlef'},
    'Constantine': {'id': 276, 'en': 'Constantine', 'ar': 'قسنطينة', 'fr': 'Constantine', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Constantine'},
    'Djelfa': {'id': 278, 'en': 'Djelfa', 'ar': 'الجلفة', 'fr': 'Djelfa', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Djelfa'},
    'El Eulma': {'id': 294, 'en': 'El Eulma', 'ar': 'العلمة', 'fr': 'El Eulma', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'El Eulma'},
    'El Khroub': {'id': 285, 'en': 'El Khroub', 'ar': 'الخروب', 'fr': 'El Khroub', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'El Khroub'},
    'El Oued': {'id': 302, 'en': 'El Oued', 'ar': 'الوادي', 'fr': 'El Oued', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'El Oued'},
    'Jijel': {'id': 301, 'en': 'Jijel', 'ar': 'جيجل', 'fr': 'Jijel', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Jijel'},
    'Laghouat': {'id': 297, 'en': 'Laghouat', 'ar': 'الأغواط', 'fr': 'Laghouat', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Laghouat'},
    "M'Sila": {'id': 292, 'en': "M'Sila", 'ar': 'المسيلة', 'fr': "M'Sila", 'lat': None, 'lon': None, 'country': 'Algérie', 'es': "M'Sila"},
    'Mostaganem': {'id': 296, 'en': 'Mostaganem', 'ar': 'مستغانم', 'fr': 'Mostaganem', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Mostaganem'},
    'Médéa': {'id': 299, 'en': 'Medea', 'ar': 'المدية', 'fr': 'Médéa', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Médéa'},
    'Oran': {'id': 275, 'en': 'Oran', 'ar': 'وهران', 'fr': 'Oran', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Oran'},
    'Ouargla': {'id': 303, 'en': 'Ouargla', 'ar': 'ورقلة', 'fr': 'Ouargla', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Ouargla'},
    'Sidi bel Abbès': {'id': 281, 'en': 'Sidi Bel Abbes', 'ar': 'سيدي بلعباس', 'fr': 'Sidi bel Abbès', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Sidi bel Abbès'},
    'Skikda': {'id': 290, 'en': 'Skikda', 'ar': 'سكيكدة', 'fr': 'Skikda', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Skikda'},
    'Souk Ahras': {'id': 293, 'en': 'Souk Ahras', 'ar': 'سوق أهراس', 'fr': 'Souk Ahras', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Souk Ahras'},
    'Sétif': {'id': 279, 'en': 'Setif', 'ar': 'سطيف', 'fr': 'Sétif', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Sétif'},
    'Tiaret': {'id': 283, 'en': 'Tiaret', 'ar': 'تيارت', 'fr': 'Tiaret', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Tiaret'},
    'Tizi Ouzou': {'id': 300, 'en': 'Tizi Ouzou', 'ar': 'تيزي وزو', 'fr': 'Tizi Ouzou', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Tizi Ouzou'},
    'Tlemcen': {'id': 298, 'en': 'Tlemcen', 'ar': 'تلمسان', 'fr': 'Tlemcen', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Tlemcen'},
    'Tébessa': {'id': 284, 'en': 'Tebessa', 'ar': 'تبسة', 'fr': 'Tébessa', 'lat': None, 'lon': None, 'country': 'Algérie', 'es': 'Tébessa'},
    # ── Allemagne (20 villes) ──
    'Berlin': {'id': 35, 'en': 'Berlin', 'ar': 'برلين', 'fr': 'Berlin', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Berlin'},
    'Bielefeld': {'id': 273, 'en': 'Bielefeld', 'ar': 'بيليفيلد', 'fr': 'Bielefeld', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Bielefeld'},
    'Bochum': {'id': 271, 'en': 'Bochum', 'ar': 'بوخوم', 'fr': 'Bochum', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Bochum'},
    'Bonn': {'id': 38, 'en': 'Bonn', 'ar': 'بون', 'fr': 'Bonn', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Bonn'},
    'Brême': {'id': 265, 'en': 'Bremen', 'ar': 'بريمن', 'fr': 'Brême', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Bremen'},
    'Cologne': {'id': 40, 'en': 'Cologne', 'ar': 'كولونيا', 'fr': 'Cologne', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Colonia'},
    'Dortmund': {'id': 263, 'en': 'Dortmund', 'ar': 'دورتموند', 'fr': 'Dortmund', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Dortmund'},
    'Dresde': {'id': 266, 'en': 'Dresden', 'ar': 'دريسدن', 'fr': 'Dresde', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Dresde'},
    'Duisbourg': {'id': 270, 'en': 'Duisburg', 'ar': 'دويسبورغ', 'fr': 'Duisbourg', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Duisbourg'},
    'Düsseldorf': {'id': 41, 'en': 'Dusseldorf', 'ar': 'دوسلدورف', 'fr': 'Düsseldorf', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Düsseldorf'},
    'Essen': {'id': 264, 'en': 'Essen', 'ar': 'إيسن', 'fr': 'Essen', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Essen'},
    'Francfort': {'id': 39, 'en': 'Frankfurt', 'ar': 'فرانكفورت', 'fr': 'Francfort', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Fráncfort'},
    'Hambourg': {'id': 37, 'en': 'Hamburg', 'ar': 'هامبورغ', 'fr': 'Hambourg', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Hambourg'},
    'Hanovre': {'id': 268, 'en': 'Hanover', 'ar': 'هانوفر', 'fr': 'Hanovre', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Hannover'},
    'Leipzig': {'id': 267, 'en': 'Leipzig', 'ar': 'لايبزيغ', 'fr': 'Leipzig', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Leipzig'},
    'Mannheim': {'id': 274, 'en': 'Mannheim', 'ar': 'مانهايم', 'fr': 'Mannheim', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Mannheim'},
    'Munich': {'id': 36, 'en': 'Munich', 'ar': 'ميونخ', 'fr': 'Munich', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Múnich'},
    'Nuremberg': {'id': 269, 'en': 'Nuremberg', 'ar': 'نورنبرغ', 'fr': 'Nuremberg', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Núremberg'},
    'Stuttgart': {'id': 262, 'en': 'Stuttgart', 'ar': 'شتوتغارت', 'fr': 'Stuttgart', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Stuttgart'},
    'Wuppertal': {'id': 272, 'en': 'Wuppertal', 'ar': 'فوبرتال', 'fr': 'Wuppertal', 'lat': None, 'lon': None, 'country': 'Allemagne', 'es': 'Wuppertal'},
    # ── Arabie-Saoudite (4 villes) ──
    'Djeddah': {'id': 328, 'en': 'Jeddah', 'ar': 'جدة', 'fr': 'Djeddah', 'lat': None, 'lon': None, 'country': 'Arabie-Saoudite', 'es': 'Yeda'},
    'La Mecque': {'id': 13, 'en': 'Mecca', 'ar': 'مكة المكرمة', 'fr': 'La Mecque', 'lat': None, 'lon': None, 'country': 'Arabie-Saoudite', 'es': 'La Meca'},
    'Médine': {'id': 12, 'en': 'Medina', 'ar': 'المدينة المنورة', 'fr': 'Médine', 'lat': None, 'lon': None, 'country': 'Arabie-Saoudite', 'es': 'Medina'},
    'Riyad': {'id': 327, 'en': 'Riyadh', 'ar': 'الرياض', 'fr': 'Riyad', 'lat': None, 'lon': None, 'country': 'Arabie-Saoudite', 'es': 'Riad'},
    # ── Australie (10 villes) ──
    'Adélaïde': {'id': 330, 'en': 'Adelaide', 'ar': 'أديلايد', 'fr': 'Adélaïde', 'lat': None, 'lon': None, 'country': 'Australie', 'es': 'Adelaida'},
    'Brisbane': {'id': 331, 'en': 'Brisbane', 'ar': 'بريسبان', 'fr': 'Brisbane', 'lat': None, 'lon': None, 'country': 'Australie', 'es': 'Brisbane'},
    'Canberra': {'id': 334, 'en': 'Canberra', 'ar': 'كانبرا', 'fr': 'Canberra', 'lat': None, 'lon': None, 'country': 'Australie', 'es': 'Canberra'},
    'Geelong': {'id': 333, 'en': 'Geelong', 'ar': 'جيلونغ', 'fr': 'Geelong', 'lat': None, 'lon': None, 'country': 'Australie', 'es': 'Geelong'},
    'Hobart': {'id': 332, 'en': 'Hobart', 'ar': 'هوبارت', 'fr': 'Hobart', 'lat': None, 'lon': None, 'country': 'Australie', 'es': 'Hobart'},
    'Melbourne': {'id': 337, 'en': 'Melbourne', 'ar': 'ملبورن', 'fr': 'Melbourne', 'lat': None, 'lon': None, 'country': 'Australie', 'es': 'Melbourne'},
    'Newcastle': {'id': 335, 'en': 'Newcastle', 'ar': 'نيوكاسل', 'fr': 'Newcastle', 'lat': None, 'lon': None, 'country': 'Australie', 'es': 'Newcastle'},
    'Perth': {'id': 336, 'en': 'Perth', 'ar': 'بيرث', 'fr': 'Perth', 'lat': None, 'lon': None, 'country': 'Australie', 'es': 'Perth'},
    'Sydney': {'id': 338, 'en': 'Sydney', 'ar': 'سيدني', 'fr': 'Sydney', 'lat': None, 'lon': None, 'country': 'Australie', 'es': 'Sídney'},
    'Wollongong': {'id': 329, 'en': 'Wollongong', 'ar': 'ولونغونغ', 'fr': 'Wollongong', 'lat': None, 'lon': None, 'country': 'Australie', 'es': 'Wollongong'},
    # ── Autriche (3 villes) ──
    'Linz': {'id': 339, 'en': 'Linz', 'ar': 'لينتس', 'fr': 'Linz', 'lat': None, 'lon': None, 'country': 'Autriche', 'es': 'Linz'},
    'Vienne': {'id': 340, 'en': 'Vienna', 'ar': 'فيينا', 'fr': 'Vienne', 'lat': None, 'lon': None, 'country': 'Autriche', 'es': 'Vienne'},
    'Villach': {'id': 341, 'en': 'Villach', 'ar': 'فيلاخ', 'fr': 'Villach', 'lat': None, 'lon': None, 'country': 'Autriche', 'es': 'Villach'},
    # ── Belgique (11 villes) ──
    'Anvers': {'id': 56, 'en': 'Antwerp', 'ar': 'أنتويرب', 'fr': 'Anvers', 'lat': None, 'lon': None, 'country': 'Belgique', 'es': 'Amberes'},
    'Bruxelles': {'id': 55, 'en': 'Brussels', 'ar': 'بروكسل', 'fr': 'Bruxelles', 'lat': None, 'lon': None, 'country': 'Belgique', 'es': 'Bruselas'},
    'Charleroi': {'id': 57, 'en': 'Charleroi', 'ar': 'شارلروا', 'fr': 'Charleroi', 'lat': None, 'lon': None, 'country': 'Belgique', 'es': 'Charleroi'},
    'Gand': {'id': 63, 'en': 'Ghent', 'ar': 'غنت', 'fr': 'Gand', 'lat': None, 'lon': None, 'country': 'Belgique', 'es': 'Gante'},
    'Hasselt': {'id': 58, 'en': 'Hasselt', 'ar': 'هاسلت', 'fr': 'Hasselt', 'lat': None, 'lon': None, 'country': 'Belgique', 'es': 'Hasselt'},
    'Liège': {'id': 61, 'en': 'Liège', 'ar': 'لييج', 'fr': 'Liège', 'lat': None, 'lon': None, 'country': 'Belgique', 'es': 'Lieja'},
    'Mons': {'id': 64, 'en': 'Mons', 'ar': 'مونس', 'fr': 'Mons', 'lat': None, 'lon': None, 'country': 'Belgique', 'es': 'Mons'},
    'Namur': {'id': 59, 'en': 'Namur', 'ar': 'نامور', 'fr': 'Namur', 'lat': None, 'lon': None, 'country': 'Belgique', 'es': 'Namur'},
    'Renaix': {'id': 65, 'en': 'Renaix', 'ar': 'رونسه', 'fr': 'Renaix', 'lat': None, 'lon': None, 'country': 'Belgique', 'es': 'Renaix'},
    'Tournai': {'id': 62, 'en': 'Tournai', 'ar': 'تورناي', 'fr': 'Tournai', 'lat': None, 'lon': None, 'country': 'Belgique', 'es': 'Tournai'},
    'Verviers': {'id': 60, 'en': 'Verviers', 'ar': 'فيرفييه', 'fr': 'Verviers', 'lat': None, 'lon': None, 'country': 'Belgique', 'es': 'Verviers'},
    # ── Cameroun (1 villes) ──
    'Yaoundé': {'id': 44, 'en': 'Yaounde', 'ar': 'ياوندي', 'fr': 'Yaoundé', 'lat': None, 'lon': None, 'country': 'Cameroun', 'es': 'Yaundé'},
    # ── Canada (5 villes) ──
    'Montréal': {'id': 51, 'en': 'Montreal', 'ar': 'مونتريال', 'fr': 'Montréal', 'lat': None, 'lon': None, 'country': 'Canada', 'es': 'Montreal'},
    'Ottawa': {'id': 52, 'en': 'Ottawa', 'ar': 'أوتاوا', 'fr': 'Ottawa', 'lat': None, 'lon': None, 'country': 'Canada', 'es': 'Ottawa'},
    'Québec': {'id': 54, 'en': 'Quebec', 'ar': 'كيبيك', 'fr': 'Québec', 'lat': None, 'lon': None, 'country': 'Canada', 'es': 'Quebec'},
    'Toronto': {'id': 53, 'en': 'Toronto', 'ar': 'تورونتو', 'fr': 'Toronto', 'lat': None, 'lon': None, 'country': 'Canada', 'es': 'Toronto'},
    'Vancouver': {'id': 260, 'en': 'Vancouver', 'ar': 'فانكوفر', 'fr': 'Vancouver', 'lat': None, 'lon': None, 'country': 'Canada', 'es': 'Vancouver'},
    # ── Côte d'ivoire (1 villes) ──
    'Abidjan': {'id': 43, 'en': 'Abidjan', 'ar': 'أبيدجان', 'fr': 'Abidjan', 'lat': None, 'lon': None, 'country': "Côte d'ivoire", 'es': 'Abiyán'},
    # ── Danemark (1 villes) ──
    'Copenhague': {'id': 342, 'en': 'Copenhagen', 'ar': 'كوبنهاغن', 'fr': 'Copenhague', 'lat': None, 'lon': None, 'country': 'Danemark', 'es': 'Copenhague'},
    # ── Egypte (1 villes) ──
    'Le Caire': {'id': 42, 'en': 'Cairo', 'ar': 'القاهرة', 'fr': 'Le Caire', 'lat': None, 'lon': None, 'country': 'Egypte', 'es': 'El Cairo'},
    # ── Emirats arabes unis (2 villes) ──
    'Abou Dhabi': {'id': 9, 'en': 'Abu Dhabi', 'ar': 'أبوظبي', 'fr': 'Abou Dhabi', 'lat': None, 'lon': None, 'country': 'Emirats arabes unis', 'es': 'Abu Dabi'},
    'Dubaï': {'id': 8, 'en': 'Dubai', 'ar': 'دبي', 'fr': 'Dubaï', 'lat': None, 'lon': None, 'country': 'Emirats arabes unis', 'es': 'Dubái'},
    # ── Espagne (54 villes) ──
    'Albacete': {'id': 240, 'en': 'Albacete', 'ar': 'البسيط', 'fr': 'Albacete', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Albacete'},
    'Alcalá de Henares': {'id': 230, 'en': 'Alcala de Henares', 'ar': 'ألكالا دي إيناريس', 'fr': 'Alcalá de Henares', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Alcalá de Henares'},
    'Alcorcón': {'id': 239, 'en': 'Alcorcon', 'ar': 'ألكوركون', 'fr': 'Alcorcón', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Alcorcón'},
    'Algeciras': {'id': 199, 'en': 'Algeciras', 'ar': 'الجزيرة الخضراء', 'fr': 'Algeciras', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Algeciras'},
    'Alicante': {'id': 210, 'en': 'Alicante', 'ar': 'أليكانتي', 'fr': 'Alicante', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Alicante'},
    'Almería': {'id': 233, 'en': 'Almeria', 'ar': 'ألميرية', 'fr': 'Almería', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Almería'},
    'Badajoz': {'id': 246, 'en': 'Badajoz', 'ar': 'بطليوس', 'fr': 'Badajoz', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Badajoz'},
    'Badalona': {'id': 224, 'en': 'Badalona', 'ar': 'بادالونا', 'fr': 'Badalona', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Badalona'},
    'Barcelona': {'id': 202, 'en': 'Barcelona', 'ar': 'برشلونة', 'fr': 'Barcelona', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Barcelona'},
    'Bilbao': {'id': 206, 'en': 'Bilbao', 'ar': 'بلباو', 'fr': 'Bilbao', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Bilbao'},
    'Burgos': {'id': 238, 'en': 'Burgos', 'ar': 'برغش', 'fr': 'Burgos', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Burgos'},
    'Cartagena': {'id': 225, 'en': 'Cartagena', 'ar': 'قرطاجنة', 'fr': 'Cartagena', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Cartagena'},
    'Castellón de la Plana': {'id': 237, 'en': 'Castellon de la Plana', 'ar': 'كاستيون دي لا بلانا', 'fr': 'Castellón de la Plana', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Castellón de la Plana'},
    'Cádiz': {'id': 197, 'en': 'Cadiz', 'ar': 'قادس', 'fr': 'Cádiz', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Cádiz'},
    'Córdoba': {'id': 211, 'en': 'Cordoba', 'ar': 'قرطبة', 'fr': 'Córdoba', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Córdoba'},
    'Elche': {'id': 221, 'en': 'Elche', 'ar': 'إلتشي', 'fr': 'Elche', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Elche'},
    'Fuenlabrada': {'id': 232, 'en': 'Fuenlabrada', 'ar': 'فوينلابرادا', 'fr': 'Fuenlabrada', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Fuenlabrada'},
    'Getafe': {'id': 241, 'en': 'Getafe', 'ar': 'خيتافي', 'fr': 'Getafe', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Getafe'},
    'Gijón': {'id': 216, 'en': 'Gijon', 'ar': 'خيخون', 'fr': 'Gijón', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Gijón'},
    'Granada': {'id': 219, 'en': 'Granada', 'ar': 'غرناطة', 'fr': 'Granada', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Granada'},
    'Huelva': {'id': 245, 'en': 'Huelva', 'ar': 'ولبة', 'fr': 'Huelva', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Huelva'},
    'Jaén': {'id': 198, 'en': 'Jaen', 'ar': 'خاين', 'fr': 'Jaén', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Jaén'},
    'Jerez de la Frontera': {'id': 228, 'en': 'Jerez de la Frontera', 'ar': 'شريش', 'fr': 'Jerez de la Frontera', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Jerez de la Frontera'},
    "L'hospitalet De Llobregat": {'id': 217, 'en': "L'Hospitalet de Llobregat", 'ar': 'هوسبيتالت دي يوبريغات', 'fr': "L'hospitalet De Llobregat", 'lat': None, 'lon': None, 'country': 'Espagne', 'es': "L'hospitalet De Llobregat"},
    'La Coruña': {'id': 218, 'en': 'A Coruña', 'ar': 'لا كورونيا', 'fr': 'La Coruña', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'La Coruña'},
    'Las Palmas De Gran Canaria': {'id': 213, 'en': 'Las Palmas de Gran Canaria', 'ar': 'لاس بالماس دي غران كناريا', 'fr': 'Las Palmas De Gran Canaria', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Las Palmas De Gran Canaria'},
    'Leganés': {'id': 235, 'en': 'Leganes', 'ar': 'ليغانيس', 'fr': 'Leganés', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Leganés'},
    'León': {'id': 248, 'en': 'Leon', 'ar': 'ليون', 'fr': 'León', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'León'},
    'Logroño': {'id': 243, 'en': 'Logrono', 'ar': 'لوغرونيو', 'fr': 'Logroño', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Logroño'},
    'Lérida': {'id': 195, 'en': 'Lleida', 'ar': 'لاردة', 'fr': 'Lérida', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Lérida'},
    'Madrid': {'id': 203, 'en': 'Madrid', 'ar': 'مدريد', 'fr': 'Madrid', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Madrid'},
    'Marbella': {'id': 196, 'en': 'Marbella', 'ar': 'مربلة', 'fr': 'Marbella', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Marbella'},
    'Murcia': {'id': 209, 'en': 'Murcia', 'ar': 'مرسية', 'fr': 'Murcia', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Murcia'},
    'Málaga': {'id': 207, 'en': 'Malaga', 'ar': 'مالقة', 'fr': 'Málaga', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Málaga'},
    'Móstoles': {'id': 226, 'en': 'Mostoles', 'ar': 'موستوليس', 'fr': 'Móstoles', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Móstoles'},
    'Oviedo': {'id': 223, 'en': 'Oviedo', 'ar': 'أوفييدو', 'fr': 'Oviedo', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Oviedo'},
    'Palma de Mallorca': {'id': 212, 'en': 'Palma de Mallorca', 'ar': 'بالما دي مايوركا', 'fr': 'Palma de Mallorca', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Palma de Mallorca'},
    'Pamplona': {'id': 231, 'en': 'Pamplona', 'ar': 'بنبلونة', 'fr': 'Pamplona', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Pamplona'},
    'Reus': {'id': 201, 'en': 'Reus', 'ar': 'ريوس', 'fr': 'Reus', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Reus'},
    'Sabadell': {'id': 229, 'en': 'Sabadell', 'ar': 'ساباديل', 'fr': 'Sabadell', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Sabadell'},
    'Salamanca': {'id': 242, 'en': 'Salamanca', 'ar': 'سلمنكا', 'fr': 'Salamanca', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Salamanca'},
    'San Cristóbal de La Laguna': {'id': 244, 'en': 'San Cristóbal de La Laguna', 'ar': 'سان كريستوبال دي لا لاغونا', 'fr': 'San Cristóbal de La Laguna', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'San Cristóbal de La Laguna'},
    'San Sebastián': {'id': 234, 'en': 'San Sebastian', 'ar': 'سان سيباستيان', 'fr': 'San Sebastián', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'San Sebastián'},
    'Santa Cruz De Tenerife': {'id': 222, 'en': 'Santa Cruz de Tenerife', 'ar': 'سانتا كروز دي تينيريفي', 'fr': 'Santa Cruz De Tenerife', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Santa Cruz De Tenerife'},
    'Santander': {'id': 236, 'en': 'Santander', 'ar': 'سانتاندير', 'fr': 'Santander', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Santander'},
    'Sevilla': {'id': 205, 'en': 'Seville', 'ar': 'إشبيلية', 'fr': 'Sevilla', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Sevilla'},
    'Tarifa': {'id': 200, 'en': 'Tarifa', 'ar': 'طريفة', 'fr': 'Tarifa', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Tarifa'},
    'Tarragona': {'id': 247, 'en': 'Tarragona', 'ar': 'طركونة', 'fr': 'Tarragona', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Tarragona'},
    'Terrassa': {'id': 227, 'en': 'Terrassa', 'ar': 'تاراسا', 'fr': 'Terrassa', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Terrassa'},
    'Valencia': {'id': 204, 'en': 'Valencia', 'ar': 'بلنسية', 'fr': 'Valencia', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Valencia'},
    'Valladolid': {'id': 214, 'en': 'Valladolid', 'ar': 'بلد الوليد', 'fr': 'Valladolid', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Valladolid'},
    'Vigo': {'id': 215, 'en': 'Vigo', 'ar': 'فيغو', 'fr': 'Vigo', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Vigo'},
    'Vitoria': {'id': 220, 'en': 'Vitoria', 'ar': 'فيتوريا', 'fr': 'Vitoria', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Vitoria'},
    'Zaragoza': {'id': 208, 'en': 'Zaragoza', 'ar': 'سرقسطة', 'fr': 'Zaragoza', 'lat': None, 'lon': None, 'country': 'Espagne', 'es': 'Zaragoza'},
    # ── Etats-Unis (13 villes) ──
    'Anchorage': {'id': 376, 'en': 'Anchorage', 'ar': 'أنكوريج', 'fr': 'Anchorage', 'lat': None, 'lon': None, 'country': 'Etats-Unis', 'es': 'Anchorage'},
    'Atlanta': {'id': 380, 'en': 'Atlanta', 'ar': 'أتلانتا', 'fr': 'Atlanta', 'lat': None, 'lon': None, 'country': 'Etats-Unis', 'es': 'Atlanta'},
    'Chicago': {'id': 48, 'en': 'Chicago', 'ar': 'شيكاغو', 'fr': 'Chicago', 'lat': None, 'lon': None, 'country': 'Etats-Unis', 'es': 'Chicago'},
    'Dallas': {'id': 379, 'en': 'Dallas', 'ar': 'دالاس', 'fr': 'Dallas', 'lat': None, 'lon': None, 'country': 'Etats-Unis', 'es': 'Dallas'},
    'Denver': {'id': 378, 'en': 'Denver', 'ar': 'دنفر', 'fr': 'Denver', 'lat': None, 'lon': None, 'country': 'Etats-Unis', 'es': 'Denver'},
    'Détroit': {'id': 375, 'en': 'Detroit', 'ar': 'ديترويت', 'fr': 'Détroit', 'lat': None, 'lon': None, 'country': 'Etats-Unis', 'es': 'Détroit'},
    'Honolulu': {'id': 381, 'en': 'Honolulu', 'ar': 'هونولولو', 'fr': 'Honolulu', 'lat': None, 'lon': None, 'country': 'Etats-Unis', 'es': 'Honolulu'},
    'Houston': {'id': 377, 'en': 'Houston', 'ar': 'هيوستن', 'fr': 'Houston', 'lat': None, 'lon': None, 'country': 'Etats-Unis', 'es': 'Houston'},
    'Los Angeles': {'id': 49, 'en': 'Los Angeles', 'ar': 'لوس أنجلوس', 'fr': 'Los Angeles', 'lat': None, 'lon': None, 'country': 'Etats-Unis', 'es': 'Los Angeles'},
    'Miami': {'id': 47, 'en': 'Miami', 'ar': 'ميامي', 'fr': 'Miami', 'lat': None, 'lon': None, 'country': 'Etats-Unis', 'es': 'Miami'},
    'New York': {'id': 45, 'en': 'New York', 'ar': 'نيويورك', 'fr': 'New York', 'lat': None, 'lon': None, 'country': 'Etats-Unis', 'es': 'Nueva York'},
    'Seattle': {'id': 50, 'en': 'Seattle', 'ar': 'سياتل', 'fr': 'Seattle', 'lat': None, 'lon': None, 'country': 'Etats-Unis', 'es': 'Seattle'},
    'Washington': {'id': 46, 'en': 'Washington', 'ar': 'واشنطن', 'fr': 'Washington', 'lat': None, 'lon': None, 'country': 'Etats-Unis', 'es': 'Washington'},
    # ── Finlande (4 villes) ──
    'Espoo': {'id': 344, 'en': 'Espoo', 'ar': 'إسبو', 'fr': 'Espoo', 'lat': None, 'lon': None, 'country': 'Finlande', 'es': 'Espoo'},
    'Helsinki': {'id': 343, 'en': 'Helsinki', 'ar': 'هلسنكي', 'fr': 'Helsinki', 'lat': None, 'lon': None, 'country': 'Finlande', 'es': 'Helsinki'},
    'Turku': {'id': 345, 'en': 'Turku', 'ar': 'توركو', 'fr': 'Turku', 'lat': None, 'lon': None, 'country': 'Finlande', 'es': 'Turku'},
    'Vantaa': {'id': 346, 'en': 'Vantaa', 'ar': 'فانتا', 'fr': 'Vantaa', 'lat': None, 'lon': None, 'country': 'Finlande', 'es': 'Vantaa'},
    # ── France (86 villes) ──
    'Albi': {'id': 141, 'en': 'Albi', 'ar': 'ألبي', 'fr': 'Albi', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Albi'},
    'Amiens': {'id': 148, 'en': 'Amiens', 'ar': 'أميان', 'fr': 'Amiens', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Amiens'},
    'Angers': {'id': 146, 'en': 'Angers', 'ar': 'أنجيه', 'fr': 'Angers', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Angers'},
    'Angoulême': {'id': 181, 'en': 'Angoulême', 'ar': 'أنغوليم', 'fr': 'Angoulême', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Angoulême'},
    'Annecy': {'id': 186, 'en': 'Annecy', 'ar': 'آنسي', 'fr': 'Annecy', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Annecy'},
    'Arras': {'id': 165, 'en': 'Arras', 'ar': 'أراس', 'fr': 'Arras', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Arras'},
    'Auxerre': {'id': 119, 'en': 'Auxerre', 'ar': 'أوكسير', 'fr': 'Auxerre', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Auxerre'},
    'Avignon': {'id': 191, 'en': 'Avignon', 'ar': 'أفينيون', 'fr': 'Avignon', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Avignon'},
    'Bar-le-Duc': {'id': 134, 'en': 'Bar-le-Duc', 'ar': 'بار لو دوك', 'fr': 'Bar-le-Duc', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Bar-le-Duc'},
    'Bayeux': {'id': 132, 'en': 'Bayeux', 'ar': 'بايو', 'fr': 'Bayeux', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Bayeux'},
    'Beauvais': {'id': 129, 'en': 'Beauvais', 'ar': 'بوفيه', 'fr': 'Beauvais', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Beauvais'},
    'Belfort': {'id': 111, 'en': 'Belfort', 'ar': 'بلفور', 'fr': 'Belfort', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Belfort'},
    'Besançon': {'id': 149, 'en': 'Besançon', 'ar': 'بيزانسون', 'fr': 'Besançon', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Besançon'},
    'Bordeaux': {'id': 150, 'en': 'Bordeaux', 'ar': 'بوردو', 'fr': 'Bordeaux', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Burdeos'},
    'Bourges': {'id': 147, 'en': 'Bourges', 'ar': 'بورج', 'fr': 'Bourges', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Bourges'},
    'Caen': {'id': 131, 'en': 'Caen', 'ar': 'كان', 'fr': 'Caen', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Caen'},
    'Carcassonne': {'id': 143, 'en': 'Carcassonne', 'ar': 'قرقشونة', 'fr': 'Carcassonne', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Carcassonne'},
    'Chalon sur Marne': {'id': 122, 'en': 'Chalon sur Marne', 'ar': 'شالون سور مارن', 'fr': 'Chalon sur Marne', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Chalon sur Marne'},
    'Chalon sur Saône': {'id': 185, 'en': 'Chalon sur Saône', 'ar': 'شالون سور سون', 'fr': 'Chalon sur Saône', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Chalon sur Saône'},
    'Chambéry': {'id': 187, 'en': 'Chambéry', 'ar': 'شامبيري', 'fr': 'Chambéry', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Chambéry'},
    'Charleville-Mézières': {'id': 170, 'en': 'Charleville-Mézières', 'ar': 'شارلفيل ميزيير', 'fr': 'Charleville-Mézières', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Charleville-Mézières'},
    'Chartres': {'id': 124, 'en': 'Chartres', 'ar': 'شارتر', 'fr': 'Chartres', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Chartres'},
    'Chaumont': {'id': 115, 'en': 'Chaumont', 'ar': 'شومون', 'fr': 'Chaumont', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Chaumont'},
    'Cherbourg': {'id': 169, 'en': 'Cherbourg', 'ar': 'شيربورغ', 'fr': 'Cherbourg', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Cherbourg'},
    'Cholet': {'id': 145, 'en': 'Cholet', 'ar': 'شوليه', 'fr': 'Cholet', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Cholet'},
    'Château-Chinon': {'id': 174, 'en': 'Château-Chinon', 'ar': 'شاتو شينون', 'fr': 'Château-Chinon', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Château-Chinon'},
    'Châtellerault': {'id': 127, 'en': 'Châtellerault', 'ar': 'شاتيلرو', 'fr': 'Châtellerault', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Châtellerault'},
    'Clermont-Ferrand': {'id': 151, 'en': 'Clermont-Ferrand', 'ar': 'كليرمون فيران', 'fr': 'Clermont-Ferrand', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Clermont-Ferrand'},
    'Dieppe': {'id': 168, 'en': 'Dieppe', 'ar': 'دييب', 'fr': 'Dieppe', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Dieppe'},
    'Dijon': {'id': 172, 'en': 'Dijon', 'ar': 'ديجون', 'fr': 'Dijon', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Dijon'},
    'Douai': {'id': 166, 'en': 'Douai', 'ar': 'دويه', 'fr': 'Douai', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Douai'},
    'Draguignan': {'id': 189, 'en': 'Draguignan', 'ar': 'دراغينيان', 'fr': 'Draguignan', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Draguignan'},
    'Epinal': {'id': 113, 'en': 'Epinal', 'ar': 'إبينال', 'fr': 'Epinal', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Epinal'},
    'Foix': {'id': 138, 'en': 'Foix', 'ar': 'فوا', 'fr': 'Foix', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Foix'},
    'Forbach': {'id': 110, 'en': 'Forbach', 'ar': 'فورباخ', 'fr': 'Forbach', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Forbach'},
    'La Rochelle': {'id': 182, 'en': 'La Rochelle', 'ar': 'لاروشيل', 'fr': 'La Rochelle', 'lat': None, 'lon': None, 'country': 'France', 'es': 'La Rochelle'},
    'Langres': {'id': 114, 'en': 'Langres', 'ar': 'لانغر', 'fr': 'Langres', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Langres'},
    'Laval': {'id': 116, 'en': 'Laval', 'ar': 'لافال', 'fr': 'Laval', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Laval'},
    'Le Havre': {'id': 130, 'en': 'Le Havre', 'ar': 'لوهافر', 'fr': 'Le Havre', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Le Havre'},
    'Le Mans': {'id': 118, 'en': 'Le Mans', 'ar': 'لومان', 'fr': 'Le Mans', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Le Mans'},
    'Le Puy': {'id': 176, 'en': 'Le Puy', 'ar': 'لوبوي', 'fr': 'Le Puy', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Le Puy'},
    'Lens': {'id': 164, 'en': 'Lens', 'ar': 'لانس', 'fr': 'Lens', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Lens'},
    'Lille': {'id': 152, 'en': 'Lille', 'ar': 'ليل', 'fr': 'Lille', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Lila'},
    'Limoges': {'id': 180, 'en': 'Limoges', 'ar': 'ليموج', 'fr': 'Limoges', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Limoges'},
    'Lyon': {'id': 153, 'en': 'Lyon', 'ar': 'ليون', 'fr': 'Lyon', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Lyon'},
    'Macon': {'id': 126, 'en': 'Macon', 'ar': 'ماكون', 'fr': 'Macon', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Macon'},
    'Marseille': {'id': 154, 'en': 'Marseille', 'ar': 'مرسيليا', 'fr': 'Marseille', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Marsella'},
    'Meaux': {'id': 121, 'en': 'Meaux', 'ar': 'مو', 'fr': 'Meaux', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Meaux'},
    'Melun': {'id': 120, 'en': 'Melun', 'ar': 'مولان', 'fr': 'Melun', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Melun'},
    'Metz': {'id': 155, 'en': 'Metz', 'ar': 'ميتز', 'fr': 'Metz', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Metz'},
    'Montluçon': {'id': 128, 'en': 'Montluçon', 'ar': 'مونلوسون', 'fr': 'Montluçon', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Montluçon'},
    'Montpellier': {'id': 140, 'en': 'Montpellier', 'ar': 'مونبلييه', 'fr': 'Montpellier', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Montpellier'},
    'Mulhouse': {'id': 156, 'en': 'Mulhouse', 'ar': 'ميلوز', 'fr': 'Mulhouse', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Mulhouse'},
    'Nancy': {'id': 133, 'en': 'Nancy', 'ar': 'نانسي', 'fr': 'Nancy', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Nancy'},
    'Nantes': {'id': 144, 'en': 'Nantes', 'ar': 'نانت', 'fr': 'Nantes', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Nantes'},
    'Nevers': {'id': 173, 'en': 'Nevers', 'ar': 'نيفر', 'fr': 'Nevers', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Nevers'},
    'Nice': {'id': 188, 'en': 'Nice', 'ar': 'نيس', 'fr': 'Nice', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Niza'},
    'Niort': {'id': 125, 'en': 'Niort', 'ar': 'نيور', 'fr': 'Niort', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Niort'},
    'Nogent sur Seine': {'id': 123, 'en': 'Nogent sur Seine', 'ar': 'نوجان سور سين', 'fr': 'Nogent sur Seine', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Nogent sur Seine'},
    'Nîmes': {'id': 192, 'en': 'Nîmes', 'ar': 'نيم', 'fr': 'Nîmes', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Nîmes'},
    'Orléans': {'id': 157, 'en': 'Orléans', 'ar': 'أورليان', 'fr': 'Orléans', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Orléans'},
    'Paris': {'id': 158, 'en': 'Paris', 'ar': 'باريس', 'fr': 'Paris', 'lat': None, 'lon': None, 'country': 'France', 'es': 'París'},
    'Pau': {'id': 139, 'en': 'Pau', 'ar': 'بو', 'fr': 'Pau', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Pau'},
    'Perpignan': {'id': 142, 'en': 'Perpignan', 'ar': 'بربينيان', 'fr': 'Perpignan', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Perpignan'},
    'Poitiers': {'id': 159, 'en': 'Poitiers', 'ar': 'بواتييه', 'fr': 'Poitiers', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Poitiers'},
    'Pontarlier': {'id': 175, 'en': 'Pontarlier', 'ar': 'بونتارلييه', 'fr': 'Pontarlier', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Pontarlier'},
    'Péronne': {'id': 171, 'en': 'Péronne', 'ar': 'بيرون', 'fr': 'Péronne', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Péronne'},
    'Reims': {'id': 194, 'en': 'Reims', 'ar': 'رانس', 'fr': 'Reims', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Reims'},
    'Rennes': {'id': 117, 'en': 'Rennes', 'ar': 'رين', 'fr': 'Rennes', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Rennes'},
    'Roanne': {'id': 184, 'en': 'Roanne', 'ar': 'روآن', 'fr': 'Roanne', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Roanne'},
    'Rodez': {'id': 177, 'en': 'Rodez', 'ar': 'روديز', 'fr': 'Rodez', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Rodez'},
    'Rouen': {'id': 160, 'en': 'Rouen', 'ar': 'روان', 'fr': 'Rouen', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Ruán'},
    'Saint Etienne': {'id': 183, 'en': 'Saint Etienne', 'ar': 'سانت إتيان', 'fr': 'Saint Etienne', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Saint Etienne'},
    'Saint-Dizier': {'id': 135, 'en': 'Saint-Dizier', 'ar': 'سان ديزييه', 'fr': 'Saint-Dizier', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Saint-Dizier'},
    'Saint-Dié': {'id': 112, 'en': 'Saint-Dié', 'ar': 'سان دييه', 'fr': 'Saint-Dié', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Saint-Dié'},
    'Strasbourg': {'id': 161, 'en': 'Strasbourg', 'ar': 'ستراسبورغ', 'fr': 'Strasbourg', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Estrasburgo'},
    'Thionville': {'id': 109, 'en': 'Thionville', 'ar': 'تيونفيل', 'fr': 'Thionville', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Thionville'},
    'Toul': {'id': 137, 'en': 'Toul', 'ar': 'تول', 'fr': 'Toul', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Toul'},
    'Toulon': {'id': 190, 'en': 'Toulon', 'ar': 'تولون', 'fr': 'Toulon', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Toulon'},
    'Toulouse': {'id': 162, 'en': 'Toulouse', 'ar': 'تولوز', 'fr': 'Toulouse', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Tolosa'},
    'Tours': {'id': 163, 'en': 'Tours', 'ar': 'تور', 'fr': 'Tours', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Tours'},
    'Troyes': {'id': 136, 'en': 'Troyes', 'ar': 'تروا', 'fr': 'Troyes', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Troyes'},
    'Valence': {'id': 178, 'en': 'Valence', 'ar': 'فالانس', 'fr': 'Valence', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Valence'},
    'Valenciennes': {'id': 167, 'en': 'Valenciennes', 'ar': 'فالانسيان', 'fr': 'Valenciennes', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Valenciennes'},
    'Verdun': {'id': 193, 'en': 'Verdun', 'ar': 'فردان', 'fr': 'Verdun', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Verdun'},
    'Vichy': {'id': 179, 'en': 'Vichy', 'ar': 'فيشي', 'fr': 'Vichy', 'lat': None, 'lon': None, 'country': 'France', 'es': 'Vichy'},
    # ── Ghana (6 villes) ──
    'Accra': {'id': 34, 'en': 'Accra', 'ar': 'أكرا', 'fr': 'Accra', 'lat': None, 'lon': None, 'country': 'Ghana', 'es': 'Accra'},
    'Kumasi': {'id': 348, 'en': 'Kumasi', 'ar': 'كوماسي', 'fr': 'Kumasi', 'lat': None, 'lon': None, 'country': 'Ghana', 'es': 'Kumasi'},
    'Sekondi': {'id': 350, 'en': 'Sekondi', 'ar': 'سيكوندي', 'fr': 'Sekondi', 'lat': None, 'lon': None, 'country': 'Ghana', 'es': 'Sekondi'},
    'Takoradi': {'id': 347, 'en': 'Takoradi', 'ar': 'تاكورادي', 'fr': 'Takoradi', 'lat': None, 'lon': None, 'country': 'Ghana', 'es': 'Takoradi'},
    'Tamale': {'id': 349, 'en': 'Tamale', 'ar': 'تامالي', 'fr': 'Tamale', 'lat': None, 'lon': None, 'country': 'Ghana', 'es': 'Tamale'},
    'Tema': {'id': 351, 'en': 'Tema', 'ar': 'تيما', 'fr': 'Tema', 'lat': None, 'lon': None, 'country': 'Ghana', 'es': 'Tema'},
    # ── Irak (1 villes) ──
    'Bagdad': {'id': 33, 'en': 'Baghdad', 'ar': 'بغداد', 'fr': 'Bagdad', 'lat': None, 'lon': None, 'country': 'Irak', 'es': 'Bagdad'},
    # ── Irlande (1 villes) ──
    'Dublin': {'id': 352, 'en': 'Dublin', 'ar': 'دبلن', 'fr': 'Dublin', 'lat': None, 'lon': None, 'country': 'Irlande', 'es': 'Dublín'},
    # ── Italie (13 villes) ──
    'Bari': {'id': 251, 'en': 'Bari', 'ar': 'باري', 'fr': 'Bari', 'lat': None, 'lon': None, 'country': 'Italie', 'es': 'Bari'},
    'Bologna': {'id': 26, 'en': 'Bologna', 'ar': 'بولونيا', 'fr': 'Bologna', 'lat': None, 'lon': None, 'country': 'Italie', 'es': 'Bolonia'},
    'Cagliari': {'id': 253, 'en': 'Cagliari', 'ar': 'كالياري', 'fr': 'Cagliari', 'lat': None, 'lon': None, 'country': 'Italie', 'es': 'Cagliari'},
    'Catania': {'id': 252, 'en': 'Catania', 'ar': 'قطانية', 'fr': 'Catania', 'lat': None, 'lon': None, 'country': 'Italie', 'es': 'Catania'},
    'Firenze': {'id': 25, 'en': 'Florence', 'ar': 'فلورنسا', 'fr': 'Firenze', 'lat': None, 'lon': None, 'country': 'Italie', 'es': 'Florencia'},
    'Genoa': {'id': 31, 'en': 'Genoa', 'ar': 'جنوة', 'fr': 'Genoa', 'lat': None, 'lon': None, 'country': 'Italie', 'es': 'Génova'},
    'Milan': {'id': 28, 'en': 'Milan', 'ar': 'ميلانو', 'fr': 'Milan', 'lat': None, 'lon': None, 'country': 'Italie', 'es': 'Milán'},
    'Napoli': {'id': 30, 'en': 'Naples', 'ar': 'نابولي', 'fr': 'Napoli', 'lat': None, 'lon': None, 'country': 'Italie', 'es': 'Nápoles'},
    'Palermo': {'id': 24, 'en': 'Palermo', 'ar': 'باليرمو', 'fr': 'Palermo', 'lat': None, 'lon': None, 'country': 'Italie', 'es': 'Palermo'},
    'Roma': {'id': 29, 'en': 'Rome', 'ar': 'روما', 'fr': 'Roma', 'lat': None, 'lon': None, 'country': 'Italie', 'es': 'Roma'},
    'Turin': {'id': 27, 'en': 'Turin', 'ar': 'تورينو', 'fr': 'Turin', 'lat': None, 'lon': None, 'country': 'Italie', 'es': 'Turín'},
    'Venezia': {'id': 32, 'en': 'Venice', 'ar': 'البندقية', 'fr': 'Venezia', 'lat': None, 'lon': None, 'country': 'Italie', 'es': 'Venecia'},
    'Verona': {'id': 249, 'en': 'Verona', 'ar': 'فيرونا', 'fr': 'Verona', 'lat': None, 'lon': None, 'country': 'Italie', 'es': 'Verona'},
    # ── Japon (10 villes) ──
    'Fukuoka': {'id': 356, 'en': 'Fukuoka', 'ar': 'فوكوكا', 'fr': 'Fukuoka', 'lat': None, 'lon': None, 'country': 'Japon', 'es': 'Fukuoka'},
    'Hiroshima': {'id': 361, 'en': 'Hiroshima', 'ar': 'هيروشيما', 'fr': 'Hiroshima', 'lat': None, 'lon': None, 'country': 'Japon', 'es': 'Hiroshima'},
    'Kawasaki': {'id': 359, 'en': 'Kawasaki', 'ar': 'كاواساكي', 'fr': 'Kawasaki', 'lat': None, 'lon': None, 'country': 'Japon', 'es': 'Kawasaki'},
    'Kitakyushu': {'id': 353, 'en': 'Kitakyushu', 'ar': 'كيتاكيوشو', 'fr': 'Kitakyushu', 'lat': None, 'lon': None, 'country': 'Japon', 'es': 'Kitakyushu'},
    'Kobe': {'id': 358, 'en': 'Kobe', 'ar': 'كوبه', 'fr': 'Kobe', 'lat': None, 'lon': None, 'country': 'Japon', 'es': 'Kobe'},
    'Kyoto': {'id': 360, 'en': 'Kyoto', 'ar': 'كيوتو', 'fr': 'Kyoto', 'lat': None, 'lon': None, 'country': 'Japon', 'es': 'Kyoto'},
    'Nagoya': {'id': 354, 'en': 'Nagoya', 'ar': 'ناغويا', 'fr': 'Nagoya', 'lat': None, 'lon': None, 'country': 'Japon', 'es': 'Nagoya'},
    'Osaka': {'id': 362, 'en': 'Osaka', 'ar': 'أوساكا', 'fr': 'Osaka', 'lat': None, 'lon': None, 'country': 'Japon', 'es': 'Osaka'},
    'Sapporo': {'id': 355, 'en': 'Sapporo', 'ar': 'سابورو', 'fr': 'Sapporo', 'lat': None, 'lon': None, 'country': 'Japon', 'es': 'Sapporo'},
    'Tokyo': {'id': 357, 'en': 'Tokyo', 'ar': 'طوكيو', 'fr': 'Tokyo', 'lat': None, 'lon': None, 'country': 'Japon', 'es': 'Tokyo'},
    # ── Liban (1 villes) ──
    'Beyrouth': {'id': 23, 'en': 'Beirut', 'ar': 'بيروت', 'fr': 'Beyrouth', 'lat': None, 'lon': None, 'country': 'Liban', 'es': 'Beirut'},
    # ── Libye (1 villes) ──
    'Tripoli': {'id': 261, 'en': 'Tripoli', 'ar': 'طرابلس', 'fr': 'Tripoli', 'lat': None, 'lon': None, 'country': 'Libye', 'es': 'Trípoli'},
    # ── Mali (1 villes) ──
    'Bamako': {'id': 22, 'en': 'Bamako', 'ar': 'باماكو', 'fr': 'Bamako', 'lat': None, 'lon': None, 'country': 'Mali', 'es': 'Bamako'},
    # ── Mauritanie (1 villes) ──
    'Nouakchott': {'id': 21, 'en': 'Nouakchott', 'ar': 'نواكشوط', 'fr': 'Nouakchott', 'lat': None, 'lon': None, 'country': 'Mauritanie', 'es': 'Nuakchot'},
    # ── Nigéria (7 villes) ──
    'Ibadan': {'id': 367, 'en': 'Ibadan', 'ar': 'إبادان', 'fr': 'Ibadan', 'lat': None, 'lon': None, 'country': 'Nigéria', 'es': 'Ibadan'},
    'Ilesha': {'id': 366, 'en': 'Ilesha', 'ar': 'إيليشا', 'fr': 'Ilesha', 'lat': None, 'lon': None, 'country': 'Nigéria', 'es': 'Ilesha'},
    'Ilorin': {'id': 364, 'en': 'Ilorin', 'ar': 'إلورين', 'fr': 'Ilorin', 'lat': None, 'lon': None, 'country': 'Nigéria', 'es': 'Ilorin'},
    'Kano': {'id': 365, 'en': 'Kano', 'ar': 'كانو', 'fr': 'Kano', 'lat': None, 'lon': None, 'country': 'Nigéria', 'es': 'Kano'},
    'Lagos': {'id': 15, 'en': 'Lagos', 'ar': 'لاغوس', 'fr': 'Lagos', 'lat': None, 'lon': None, 'country': 'Nigéria', 'es': 'Lagos'},
    'Onitsha': {'id': 363, 'en': 'Onitsha', 'ar': 'أونيتشا', 'fr': 'Onitsha', 'lat': None, 'lon': None, 'country': 'Nigéria', 'es': 'Onitsha'},
    'Zaria': {'id': 368, 'en': 'Zaria', 'ar': 'زاريا', 'fr': 'Zaria', 'lat': None, 'lon': None, 'country': 'Nigéria', 'es': 'Zaria'},
    # ── Norvège (1 villes) ──
    'Oslo': {'id': 386, 'en': 'Oslo', 'ar': 'أوسلو', 'fr': 'Oslo', 'lat': None, 'lon': None, 'country': 'Norvège', 'es': 'Oslo'},
    # ── Nouvelle-Zélande (4 villes) ──
    'Auckland': {'id': 385, 'en': 'Auckland', 'ar': 'أوكلاند', 'fr': 'Auckland', 'lat': None, 'lon': None, 'country': 'Nouvelle-Zélande', 'es': 'Auckland'},
    'Dunedin': {'id': 383, 'en': 'Dunedin', 'ar': 'دنيدن', 'fr': 'Dunedin', 'lat': None, 'lon': None, 'country': 'Nouvelle-Zélande', 'es': 'Dunedin'},
    'Hamilton': {'id': 382, 'en': 'Hamilton', 'ar': 'هاميلتون', 'fr': 'Hamilton', 'lat': None, 'lon': None, 'country': 'Nouvelle-Zélande', 'es': 'Hamilton'},
    'Wellington': {'id': 384, 'en': 'Wellington', 'ar': 'ولينغتون', 'fr': 'Wellington', 'lat': None, 'lon': None, 'country': 'Nouvelle-Zélande', 'es': 'Wellington'},
    # ── Pays-Bas (21 villes) ──
    'Almere': {'id': 413, 'en': 'Almere', 'ar': 'ألمير', 'fr': 'Almere', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Almere'},
    'Amersfoort': {'id': 422, 'en': 'Amersfoort', 'ar': 'أمرسفورت', 'fr': 'Amersfoort', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Amersfoort'},
    'Amsterdam': {'id': 16, 'en': 'Amsterdam', 'ar': 'أمستردام', 'fr': 'Amsterdam', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Amsterdam'},
    'Apeldoorn': {'id': 420, 'en': 'Apeldoorn', 'ar': 'أبلدورن', 'fr': 'Apeldoorn', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Apeldoorn'},
    'Arnhem': {'id': 417, 'en': 'Arnhem', 'ar': 'أرنهيم', 'fr': 'Arnhem', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Arnhem'},
    'Bois-le-Duc': {'id': 419, 'en': "'s-Hertogenbosch", 'ar': 'سيرتوخنبوس', 'fr': 'Bois-le-Duc', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Bois-le-Duc'},
    'Bréda': {'id': 414, 'en': 'Breda', 'ar': 'بريدا', 'fr': 'Bréda', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Bréda'},
    'Eindhoven': {'id': 20, 'en': 'Eindhoven', 'ar': 'آيندهوفن', 'fr': 'Eindhoven', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Eindhoven'},
    'Enschede': {'id': 421, 'en': 'Enschede', 'ar': 'أنسخديه', 'fr': 'Enschede', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Enschede'},
    'Groningue': {'id': 412, 'en': 'Groningen', 'ar': 'خرونينغن', 'fr': 'Groningue', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Groningue'},
    'Haarlem': {'id': 418, 'en': 'Haarlem', 'ar': 'هارلم', 'fr': 'Haarlem', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Haarlem'},
    'Haarlemmermeer': {'id': 424, 'en': 'Haarlemmermeer', 'ar': 'هارلمرمير', 'fr': 'Haarlemmermeer', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Haarlemmermeer'},
    'La Haye': {'id': 18, 'en': 'The Hague', 'ar': 'لاهاي', 'fr': 'La Haye', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'La Haye'},
    'Maastricht': {'id': 416, 'en': 'Maastricht', 'ar': 'ماستريخت', 'fr': 'Maastricht', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Maastricht'},
    'Nimègue': {'id': 415, 'en': 'Nijmegen', 'ar': 'نايميخن', 'fr': 'Nimègue', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Nimègue'},
    'Rotterdam': {'id': 17, 'en': 'Rotterdam', 'ar': 'روتردام', 'fr': 'Rotterdam', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Rotterdam'},
    'Tilburg': {'id': 258, 'en': 'Tilburg', 'ar': 'تيلبورغ', 'fr': 'Tilburg', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Tilburg'},
    'Utrecht': {'id': 19, 'en': 'Utrecht', 'ar': 'أوتريخت', 'fr': 'Utrecht', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Utrecht'},
    'Zaanstad': {'id': 423, 'en': 'Zaanstad', 'ar': 'زانستاد', 'fr': 'Zaanstad', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Zaanstad'},
    'Zoetermeer': {'id': 426, 'en': 'Zoetermeer', 'ar': 'زوترمير', 'fr': 'Zoetermeer', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Zoetermeer'},
    'Zwolle': {'id': 425, 'en': 'Zwolle', 'ar': 'زفوله', 'fr': 'Zwolle', 'lat': None, 'lon': None, 'country': 'Pays-Bas', 'es': 'Zwolle'},
    # ── Qatar (1 villes) ──
    'Doha': {'id': 14, 'en': 'Doha', 'ar': 'الدوحة', 'fr': 'Doha', 'lat': None, 'lon': None, 'country': 'Qatar', 'es': 'Doha'},
    # ── Royaume-Uni (9 villes) ──
    'Belfast': {'id': 396, 'en': 'Belfast', 'ar': 'بلفاست', 'fr': 'Belfast', 'lat': None, 'lon': None, 'country': 'Royaume-Uni', 'es': 'Belfast'},
    'Birmingham': {'id': 395, 'en': 'Birmingham', 'ar': 'برمنغهام', 'fr': 'Birmingham', 'lat': None, 'lon': None, 'country': 'Royaume-Uni', 'es': 'Birmingham'},
    'Bristol': {'id': 393, 'en': 'Bristol', 'ar': 'بريستول', 'fr': 'Bristol', 'lat': None, 'lon': None, 'country': 'Royaume-Uni', 'es': 'Bristol'},
    'Cardiff': {'id': 400, 'en': 'Cardiff', 'ar': 'كارديف', 'fr': 'Cardiff', 'lat': None, 'lon': None, 'country': 'Royaume-Uni', 'es': 'Cardiff'},
    'Glasgow': {'id': 399, 'en': 'Glasgow', 'ar': 'غلاسكو', 'fr': 'Glasgow', 'lat': None, 'lon': None, 'country': 'Royaume-Uni', 'es': 'Glasgow'},
    'Liverpool': {'id': 397, 'en': 'Liverpool', 'ar': 'ليفربول', 'fr': 'Liverpool', 'lat': None, 'lon': None, 'country': 'Royaume-Uni', 'es': 'Liverpool'},
    'London': {'id': 7, 'en': 'London', 'ar': 'لندن', 'fr': 'London', 'lat': None, 'lon': None, 'country': 'Royaume-Uni', 'es': 'Londres'},
    'Manchester': {'id': 398, 'en': 'Manchester', 'ar': 'مانشستر', 'fr': 'Manchester', 'lat': None, 'lon': None, 'country': 'Royaume-Uni', 'es': 'Manchester'},
    'Sheffield': {'id': 394, 'en': 'Sheffield', 'ar': 'شيفيلد', 'fr': 'Sheffield', 'lat': None, 'lon': None, 'country': 'Royaume-Uni', 'es': 'Sheffield'},
    # ── Sénégal (1 villes) ──
    'Dakar': {'id': 11, 'en': 'Dakar', 'ar': 'داكار', 'fr': 'Dakar', 'lat': None, 'lon': None, 'country': 'Sénégal', 'es': 'Dakar'},
    # ── Suède (5 villes) ──
    'Borås': {'id': 390, 'en': 'Boras', 'ar': 'بوروس', 'fr': 'Borås', 'lat': None, 'lon': None, 'country': 'Suède', 'es': 'Borås'},
    'Malmö': {'id': 391, 'en': 'Malmo', 'ar': 'مالمو', 'fr': 'Malmö', 'lat': None, 'lon': None, 'country': 'Suède', 'es': 'Malmö'},
    'Stockholm': {'id': 389, 'en': 'Stockholm', 'ar': 'ستوكهولم', 'fr': 'Stockholm', 'lat': None, 'lon': None, 'country': 'Suède', 'es': 'Stockholm'},
    'Uppsala': {'id': 392, 'en': 'Uppsala', 'ar': 'أوبسالا', 'fr': 'Uppsala', 'lat': None, 'lon': None, 'country': 'Suède', 'es': 'Uppsala'},
    'Örebro': {'id': 387, 'en': 'Orebro', 'ar': 'أوريبرو', 'fr': 'Örebro', 'lat': None, 'lon': None, 'country': 'Suède', 'es': 'Örebro'},
    # ── Suisse (15 villes) ──
    'Berne': {'id': 6, 'en': 'Bern', 'ar': 'برن', 'fr': 'Berne', 'lat': None, 'lon': None, 'country': 'Suisse', 'es': 'Berna'},
    'Bienne': {'id': 409, 'en': 'Bienne', 'ar': 'بيال', 'fr': 'Bienne', 'lat': None, 'lon': None, 'country': 'Suisse', 'es': 'Bienne'},
    'Bâle': {'id': 401, 'en': 'Basel', 'ar': 'بازل', 'fr': 'Bâle', 'lat': None, 'lon': None, 'country': 'Suisse', 'es': 'Basilea'},
    'Fribourg': {'id': 403, 'en': 'Fribourg', 'ar': 'فريبورغ', 'fr': 'Fribourg', 'lat': None, 'lon': None, 'country': 'Suisse', 'es': 'Friburgo'},
    'Genève': {'id': 5, 'en': 'Geneva', 'ar': 'جنيف', 'fr': 'Genève', 'lat': None, 'lon': None, 'country': 'Suisse', 'es': 'Ginebra'},
    'La Chaux-de-Fonds': {'id': 411, 'en': 'La Chaux-de-Fonds', 'ar': 'لاشو دو فون', 'fr': 'La Chaux-de-Fonds', 'lat': None, 'lon': None, 'country': 'Suisse', 'es': 'La Chaux-de-Fonds'},
    'Lausanne': {'id': 3, 'en': 'Lausanne', 'ar': 'لوزان', 'fr': 'Lausanne', 'lat': None, 'lon': None, 'country': 'Suisse', 'es': 'Lausana'},
    'Lucerne': {'id': 404, 'en': 'Lucerne', 'ar': 'لوسيرن', 'fr': 'Lucerne', 'lat': None, 'lon': None, 'country': 'Suisse', 'es': 'Lucerna'},
    'Lugano': {'id': 408, 'en': 'Lugano', 'ar': 'لوغانو', 'fr': 'Lugano', 'lat': None, 'lon': None, 'country': 'Suisse', 'es': 'Lugano'},
    'Montreux': {'id': 405, 'en': 'Montreux', 'ar': 'مونترو', 'fr': 'Montreux', 'lat': None, 'lon': None, 'country': 'Suisse', 'es': 'Montreux'},
    'Neuchatel': {'id': 402, 'en': 'Neuchâtel', 'ar': 'نوشاتيل', 'fr': 'Neuchatel', 'lat': None, 'lon': None, 'country': 'Suisse', 'es': 'Neuchâtel'},
    'Saint-Gall': {'id': 407, 'en': 'St. Gallen', 'ar': 'سان غالن', 'fr': 'Saint-Gall', 'lat': None, 'lon': None, 'country': 'Suisse', 'es': 'San Galo'},
    'Thoune': {'id': 410, 'en': 'Thoune', 'ar': 'تون', 'fr': 'Thoune', 'lat': None, 'lon': None, 'country': 'Suisse', 'es': 'Thun'},
    'Winterthour': {'id': 406, 'en': 'Winterthur', 'ar': 'فينترتور', 'fr': 'Winterthour', 'lat': None, 'lon': None, 'country': 'Suisse', 'es': 'Winterthur'},
    'Zurich': {'id': 4, 'en': 'Zurich', 'ar': 'زيورخ', 'fr': 'Zurich', 'lat': None, 'lon': None, 'country': 'Suisse', 'es': 'Zúrich'},
    # ── Syrie (1 villes) ──
    'Damas': {'id': 10, 'en': 'Damascus', 'ar': 'دمشق', 'fr': 'Damas', 'lat': None, 'lon': None, 'country': 'Syrie', 'es': 'Damasco'},
    # ── Tunisie (24 villes) ──
    'Ariana': {'id': 304, 'en': 'Ariana', 'ar': 'أريانة', 'fr': 'Ariana', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Ariana'},
    'Ben Arous': {'id': 306, 'en': 'Ben Arous', 'ar': 'بن عروس', 'fr': 'Ben Arous', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Ben Arous'},
    'Bizerte': {'id': 307, 'en': 'Bizerte', 'ar': 'بنزرت', 'fr': 'Bizerte', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Bizerte'},
    'Béja': {'id': 305, 'en': 'Béja', 'ar': 'باجة', 'fr': 'Béja', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Béja'},
    'Gabès': {'id': 308, 'en': 'Gabès', 'ar': 'قابس', 'fr': 'Gabès', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Gabès'},
    'Gafsa': {'id': 309, 'en': 'Gafsa', 'ar': 'قفصة', 'fr': 'Gafsa', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Gafsa'},
    'Jendouba': {'id': 310, 'en': 'Jendouba', 'ar': 'جندوبة', 'fr': 'Jendouba', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Jendouba'},
    'Kairouan': {'id': 311, 'en': 'Kairouan', 'ar': 'القيروان', 'fr': 'Kairouan', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Kairouan'},
    'Kasserine': {'id': 312, 'en': 'Kasserine', 'ar': 'القصرين', 'fr': 'Kasserine', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Kasserine'},
    'Kébili': {'id': 313, 'en': 'Kébili', 'ar': 'قبلي', 'fr': 'Kébili', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Kébili'},
    'La Manouba': {'id': 316, 'en': 'La Manouba', 'ar': 'منوبة', 'fr': 'La Manouba', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'La Manouba'},
    'Le Kef': {'id': 314, 'en': 'Le Kef', 'ar': 'الكاف', 'fr': 'Le Kef', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Le Kef'},
    'Mahdia': {'id': 315, 'en': 'Mahdia', 'ar': 'المهدية', 'fr': 'Mahdia', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Mahdia'},
    'Monastir': {'id': 318, 'en': 'Monastir', 'ar': 'المنستير', 'fr': 'Monastir', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Monastir'},
    'Médenine': {'id': 317, 'en': 'Médenine', 'ar': 'مدنين', 'fr': 'Médenine', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Médenine'},
    'Nabeul': {'id': 319, 'en': 'Nabeul', 'ar': 'نابل', 'fr': 'Nabeul', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Nabeul'},
    'Sfax': {'id': 320, 'en': 'Sfax', 'ar': 'صفاقس', 'fr': 'Sfax', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Sfax'},
    'Sidi Bouzid': {'id': 321, 'en': 'Sidi Bouzid', 'ar': 'سيدي بوزيد', 'fr': 'Sidi Bouzid', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Sidi Bouzid'},
    'Siliana': {'id': 322, 'en': 'Siliana', 'ar': 'سليانة', 'fr': 'Siliana', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Siliana'},
    'Sousse': {'id': 323, 'en': 'Sousse', 'ar': 'سوسة', 'fr': 'Sousse', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Sousse'},
    'Tataouine': {'id': 324, 'en': 'Tataouine', 'ar': 'تطاوين', 'fr': 'Tataouine', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Tataouine'},
    'Tozeur': {'id': 325, 'en': 'Tozeur', 'ar': 'توزر', 'fr': 'Tozeur', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Tozeur'},
    'Tunis': {'id': 1, 'en': 'Tunis', 'ar': 'تونس', 'fr': 'Tunis', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Túnez'},
    'Zaghouan': {'id': 326, 'en': 'Zaghouan', 'ar': 'زغوان', 'fr': 'Zaghouan', 'lat': None, 'lon': None, 'country': 'Tunisie', 'es': 'Zaghouan'},

}


# ── Countries (French canonical from yabiladi) + en/ar/fr names ──
COUNTRIES = {
    'Afrique du sud': {'en': 'South Africa', 'ar': 'جنوب أفريقيا', 'fr': 'Afrique du sud'},
    'Algérie': {'en': 'Algeria', 'ar': 'الجزائر', 'fr': 'Algérie'},
    'Allemagne': {'en': 'Germany', 'ar': 'ألمانيا', 'fr': 'Allemagne'},
    'Arabie-Saoudite': {'en': 'Saudi Arabia', 'ar': 'السعودية', 'fr': 'Arabie-Saoudite'},
    'Australie': {'en': 'Australia', 'ar': 'أستراليا', 'fr': 'Australie'},
    'Autriche': {'en': 'Austria', 'ar': 'النمسا', 'fr': 'Autriche'},
    'Belgique': {'en': 'Belgium', 'ar': 'بلجيكا', 'fr': 'Belgique'},
    'Cameroun': {'en': 'Cameroon', 'ar': 'الكاميرون', 'fr': 'Cameroun'},
    'Canada': {'en': 'Canada', 'ar': 'كندا', 'fr': 'Canada'},
    "Côte d'ivoire": {'en': 'Ivory Coast', 'ar': 'ساحل العاج', 'fr': "Côte d'ivoire"},
    'Danemark': {'en': 'Denmark', 'ar': 'الدنمارك', 'fr': 'Danemark'},
    'Egypte': {'en': 'Egypt', 'ar': 'مصر', 'fr': 'Egypte'},
    'Emirats arabes unis': {'en': 'United Arab Emirates', 'ar': 'الإمارات العربية المتحدة', 'fr': 'Emirats arabes unis'},
    'Espagne': {'en': 'Spain', 'ar': 'إسبانيا', 'fr': 'Espagne'},
    'Etats-Unis': {'en': 'United States', 'ar': 'الولايات المتحدة', 'fr': 'Etats-Unis'},
    'Finlande': {'en': 'Finland', 'ar': 'فنلندا', 'fr': 'Finlande'},
    'France': {'en': 'France', 'ar': 'فرنسا', 'fr': 'France'},
    'Ghana': {'en': 'Ghana', 'ar': 'غانا', 'fr': 'Ghana'},
    'Irak': {'en': 'Iraq', 'ar': 'العراق', 'fr': 'Irak'},
    'Irlande': {'en': 'Ireland', 'ar': 'أيرلندا', 'fr': 'Irlande'},
    'Italie': {'en': 'Italy', 'ar': 'إيطاليا', 'fr': 'Italie'},
    'Japon': {'en': 'Japan', 'ar': 'اليابان', 'fr': 'Japon'},
    'Liban': {'en': 'Lebanon', 'ar': 'لبنان', 'fr': 'Liban'},
    'Libye': {'en': 'Libya', 'ar': 'ليبيا', 'fr': 'Libye'},
    'Mali': {'en': 'Mali', 'ar': 'مالي', 'fr': 'Mali'},
    'Maroc': {'en': 'Morocco', 'ar': 'المغرب', 'fr': 'Maroc'},
    'Mauritanie': {'en': 'Mauritania', 'ar': 'موريتانيا', 'fr': 'Mauritanie'},
    'Nigéria': {'en': 'Nigeria', 'ar': 'نيجيريا', 'fr': 'Nigéria'},
    'Norvège': {'en': 'Norway', 'ar': 'النرويج', 'fr': 'Norvège'},
    'Nouvelle-Zélande': {'en': 'New Zealand', 'ar': 'نيوزيلندا', 'fr': 'Nouvelle-Zélande'},
    'Pays-Bas': {'en': 'Netherlands', 'ar': 'هولندا', 'fr': 'Pays-Bas'},
    'Qatar': {'en': 'Qatar', 'ar': 'قطر', 'fr': 'Qatar'},
    'Royaume-Uni': {'en': 'United Kingdom', 'ar': 'المملكة المتحدة', 'fr': 'Royaume-Uni'},
    'Sénégal': {'en': 'Senegal', 'ar': 'السنغال', 'fr': 'Sénégal'},
    'Suède': {'en': 'Sweden', 'ar': 'السويد', 'fr': 'Suède'},
    'Suisse': {'en': 'Switzerland', 'ar': 'سويسرا', 'fr': 'Suisse'},
    'Syrie': {'en': 'Syria', 'ar': 'سوريا', 'fr': 'Syrie'},
    'Tunisie': {'en': 'Tunisia', 'ar': 'تونس', 'fr': 'Tunisie'},
}


def tr_country(fr_name, lang):
    """Translated country name; falls back to French."""
    return COUNTRIES.get(fr_name, {}).get(lang, fr_name)


def get_countries():
    """French canonical country names in insertion order."""
    return list(COUNTRIES.keys())


def get_cities_by_country(fr_country):
    """CITIES keys belonging to a country."""
    return [k for k, v in CITIES.items() if v.get('country') == fr_country]
