# Translation dictionaries
TRANSLATIONS = {
    'en': {
        'app_title': 'Salah Times',
        'next_prayer': 'NEXT PRAYER',
        'tomorrow': 'Tomorrow',
        'loading': '🔄 Loading prayer times...',
        'refresh': '↻ Refresh',
        'error': '⚠️ Error: {}\n\nPlease check your internet connection\nand try refreshing.',
        'welcome': '🕌 Welcome to Salah Times',
        'select_city': 'Please select your default city for prayer times:',
        'search_city': 'Search for a city...',
        'cancel': 'Cancel',
        'set_default': 'Set as Default',
        'change_city': 'Change Default City',
        'iqama_time': 'Time before Iqama of {}: {:02d}:{:02d}:{:02d}',
        'iqama_passed': 'Iqama of {}: 00:00:00',
        'hijri_unavailable': 'Hijri date unavailable',
        'hijri_approx': '{} AH (Approximate)',
        'morocco': 'Morocco',
        'months': ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        'days': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        'hijri_months': {'Muharram': 'Muharram', 'Safar': 'Safar', 'Rabi\'al-awwal': 'Rabi al-Awwal', 'Rabi\'al-thani': 'Rabi al-Thani', 'Jumada al-awwal': 'Jumada al-Awwal', 'Jumada al-thani': 'Jumada al-Thani', 'Rajab': 'Rajab', 'Sha\'ban': 'Shaban', 'Ramadan': 'Ramadan', 'Shawwal': 'Shawwal', 'Dhu al-Qi\'dah': 'Dhu al-Qidah', 'Dhu al-Hijjah': 'Dhu al-Hijjah'},
        'language': 'Language',
        'settings': 'Settings',
        'monthly_calendar': 'Monthly Calendar',
        'weekly_schedule': 'Weekly Schedule',
        'refresh_db': '🗄️ Refresh DB',
        'refresh_db_updating': '⏳ Updating...',
        'refresh_db_prompt_title': 'Update Prayer Times',
        'refresh_db_prompt_msg': '30 days have passed since the last database update.\nRefresh all prayer times now?',
        'timezone_view': 'Multiple Timezones',
        'view': 'View',
        'tray_show': '🪟 Show Main Window',
        'tray_refresh': '↻ Refresh Prayer Times',
        'tray_quit': '❌ Quit',
        'no_internet_title': 'No Internet Connection',
        'no_internet_msg': 'Cannot update without an internet connection.\n\nCurrent database:\n• {} cities\n• From: {}\n• Until: {}',
        'prayers': {
            'Date': 'Date',
            'Fajr': 'Fajr',
            'Dohr': 'Dhuhr',
            'Asr': 'Asr',
            'Maghreb': 'Maghrib',
            'Isha': 'Isha'
        }
    },
    'ar': {
        'app_title': 'مواقيت الصلاة',
        'next_prayer': 'الصلاة القادمة',
        'tomorrow': 'غداً',
        'loading': '🔄 جاري تحميل مواقيت الصلاة...',
        'refresh': '↻ تحديث',
        'error': '⚠️ خطأ: {}\n\nيرجى التحقق من اتصال الإنترنت\nوإعادة المحاولة.',
        'welcome': '🕌 مرحباً بك في مواقيت الصلاة',
        'select_city': 'يرجى اختيار مدينتك الافتراضية لمواقيت الصلاة:',
        'search_city': 'البحث عن مدينة...',
        'cancel': 'إلغاء',
        'set_default': 'تعيين كافتراضي',
        'change_city': 'تغيير المدينة الافتراضية',
        'iqama_time': 'الوقت المتبقي لإقامة {}: {:02d}:{:02d}:{:02d}',
        'iqama_passed': 'إقامة {}: 00:00:00',
        'hijri_unavailable': 'التاريخ الهجري غير متوفر',
        'hijri_approx': '{} هـ (تقريبي)',
        'morocco': 'المغرب',
        'months': ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'],
        'days': ['الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت', 'الأحد'],
        'hijri_months': {'Muharram': 'محرم', 'Safar': 'صفر', 'Rabi\'al-awwal': 'ربيع الأول', 'Rabi\'al-thani': 'ربيع الثاني', 'Jumada al-awwal': 'جمادى الأولى', 'Jumada al-thani': 'جمادى الثانية', 'Rajab': 'رجب', 'Sha\'ban': 'شعبان', 'Ramadan': 'رمضان', 'Shawwal': 'شوال', 'Dhu al-Qi\'dah': 'ذو القعدة', 'Dhu al-Hijjah': 'ذو الحجة'},
        'language': 'اللغة',
        'settings': 'الإعدادات',
        'monthly_calendar': 'التقويم الشهري',
        'weekly_schedule': 'الجدول الأسبوعي',
        'refresh_db': '🗄️ تحديث قاعدة البيانات',
        'refresh_db_updating': '⏳ جاري التحديث...',
        'refresh_db_prompt_title': 'تحديث مواقيت الصلاة',
        'refresh_db_prompt_msg': 'مرّ 30 يوماً منذ آخر تحديث لقاعدة البيانات.\nهل تريد تحديث مواقيت الصلاة الآن؟',
        'timezone_view': 'مناطق زمنية متعددة',
        'view': 'عرض',
        'tray_show': '🪟 عرض النافذة الرئيسية',
        'tray_refresh': '↻ تحديث مواقيت الصلاة',
        'tray_quit': '❌ خروج',
        'no_internet_title': 'لا يوجد اتصال بالإنترنت',
        'no_internet_msg': 'لا يمكن التحديث بدون اتصال بالإنترنت.\n\nقاعدة البيانات الحالية:\n• {} مدينة\n• من: {}\n• حتى: {}',
        'prayers': {
            'Date': 'التاريخ',
            'Fajr': 'الفجر',
            'Dohr': 'الظهر',
            'Asr': 'العصر',
            'Maghreb': 'المغرب',
            'Isha': 'العشاء'
        }
    },
    'fr': {
        'app_title': 'Horaires de Priere',
        'next_prayer': 'PROCHAINE PRIERE',
        'tomorrow': 'Demain',
        'loading': '🔄 Chargement des horaires de priere...',
        'refresh': '↻ Actualiser',
        'error': '⚠️ Erreur: {}\n\nVeuillez verifier votre connexion Internet\net reessayer.',
        'welcome': '🕌 Bienvenue dans Horaires de Priere',
        'select_city': 'Veuillez selectionner votre ville par defaut pour les horaires de priere:',
        'search_city': 'Rechercher une ville...',
        'cancel': 'Annuler',
        'set_default': 'Definir par defaut',
        'change_city': 'Changer la ville par defaut',
        'iqama_time': 'Temps avant Iqama de {}: {:02d}:{:02d}:{:02d}',
        'iqama_passed': 'Iqama de {}: 00:00:00',
        'hijri_unavailable': 'Date hijri non disponible',
        'hijri_approx': '{} AH (Approximatif)',
        'morocco': 'Maroc',
        'months': ['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Aout', 'Septembre', 'Octobre', 'Novembre', 'Decembre'],
        'days': ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'],
        'hijri_months': {'Muharram': 'Muharram', 'Safar': 'Safar', 'Rabi\'al-awwal': 'Rabi al-Awwal', 'Rabi\'al-thani': 'Rabi al-Thani', 'Jumada al-awwal': 'Jumada al-Awwal', 'Jumada al-thani': 'Jumada al-Thani', 'Rajab': 'Rajab', 'Sha\'ban': 'Shaban', 'Ramadan': 'Ramadan', 'Shawwal': 'Shawwal', 'Dhu al-Qi\'dah': 'Dhu al-Qidah', 'Dhu al-Hijjah': 'Dhu al-Hijjah'},
        'language': 'Langue',
        'settings': 'Parametres',
        'monthly_calendar': 'Calendrier Mensuel',
        'weekly_schedule': 'Horaire Hebdomadaire',
        'refresh_db': '🗄️ Actualiser BD',
        'refresh_db_updating': '⏳ Mise a jour...',
        'refresh_db_prompt_title': 'Mise a jour des horaires',
        'refresh_db_prompt_msg': '30 jours se sont ecoules depuis la derniere mise a jour.\nActualiser les horaires de priere maintenant?',
        'timezone_view': 'Fuseaux Horaires Multiples',
        'view': 'Affichage',
        'tray_show': '🪟 Afficher la fenetre',
        'tray_refresh': '↻ Actualiser les horaires',
        'tray_quit': '❌ Quitter',
        'no_internet_title': 'Pas de connexion Internet',
        'no_internet_msg': 'Impossible de mettre a jour sans connexion.\n\nBase de donnees actuelle:\n• {} villes\n• Du: {}\n• Au: {}',
        'prayers': {
            'Date': 'Date',
            'Fajr': 'Fajr',
            'Dohr': 'Dhuhr',
            'Asr': 'Asr',
            'Maghreb': 'Maghrib',
            'Isha': 'Isha'
        }
    }
}

CITY_SLUGS = {
    'Agadir': 'agadir', 'Al Hoceima': 'al-hoceima', 'Assila': 'assila',
    'Beni Mellal': 'beni-mellal', 'Berkane': 'berkane', 'Boulemane': 'boulemane',
    'Casablanca': 'casablanca', 'Chefchaouen': 'chefchaouen', 'Dakhla': 'dakhla',
    'El Jadida': 'el-jadida', 'Errachidia': 'errachidia', 'Essaouira': 'essaouira',
    'Fes': 'fes', 'Ifrane': 'ifrane', 'Kalaat Sraghna': 'kalaat-sraghna',
    'Kenitra': 'kenitra', 'Khenifra': 'khenifra', 'Khouribga': 'khouribga',
    'Ksar Lekbir': 'ksar-lekbir', 'Laayoune': 'laayoune', 'Lagouira': 'lagouira',
    'Larache': 'larache', 'Marrakech': 'marrakech', 'Meknes': 'meknes',
    'Mohammedia': 'mohammedia', 'Moulay Idriss Zerhoun': 'moulay-idriss-zerhoun',
    'Nador': 'nador', 'Ouazzane': 'ouazzane', 'Oujda': 'oujda', 'Rabat': 'rabat',
    'Safi': 'safi', 'Sefrou': 'sefrou', 'Settat': 'settat', 'Sidi Kacem': 'sidi-kacem',
    'Smara': 'smara', 'Tan Tan': 'tan-tan', 'Tangier': 'tanger', 'Taounate': 'taounate',
    'Taroudant': 'taroudant', 'Taza': 'taza', 'Tetouan': 'tetouan', 'Tiznit': 'tiznit',
    'Zagora': 'zagora',
}

BASE_URL = 'https://www.yabiladi.com/prieres/details/{}/{}.html'
SCRAPER_HEADERS = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}

CITIES = {
    'Tangier': {'id': 101, 'en': 'Tangier', 'ar': 'طنجة', 'fr': 'Tanger', 'lat': 35.7595, 'lon': -5.8340},
    'Casablanca': {'id': 71, 'en': 'Casablanca', 'ar': 'الدار البيضاء', 'fr': 'Casablanca', 'lat': 33.5731, 'lon': -7.5898},
    'Rabat': {'id': 95, 'en': 'Rabat', 'ar': 'الرباط', 'fr': 'Rabat', 'lat': 34.0209, 'lon': -6.8416},
    'Marrakech': {'id': 88, 'en': 'Marrakech', 'ar': 'مراكش', 'fr': 'Marrakech', 'lat': 31.6295, 'lon': -7.9811},
    'Fes': {'id': 78, 'en': 'Fes', 'ar': 'فاس', 'fr': 'Fes', 'lat': 34.0181, 'lon': -5.0078},
    'Agadir': {'id': 66, 'en': 'Agadir', 'ar': 'أكادير', 'fr': 'Agadir', 'lat': 30.4278, 'lon': -9.5981},
    'Meknes': {'id': 89, 'en': 'Meknes', 'ar': 'مكناس', 'fr': 'Meknes', 'lat': 33.8935, 'lon': -5.5473},
    'Oujda': {'id': 93, 'en': 'Oujda', 'ar': 'وجدة', 'fr': 'Oujda', 'lat': 34.6814, 'lon': -1.9086},
    'Kenitra': {'id': 81, 'en': 'Kenitra', 'ar': 'القنيطرة', 'fr': 'Kenitra', 'lat': 34.2610, 'lon': -6.5802},
    'Tetouan': {'id': 100, 'en': 'Tetouan', 'ar': 'تطوان', 'fr': 'Tetouan', 'lat': 35.5889, 'lon': -5.3626},
    'Safi': {'id': 96, 'en': 'Safi', 'ar': 'آسفي', 'fr': 'Safi', 'lat': 32.2994, 'lon': -9.2372},
    'Mohammedia': {'id': 90, 'en': 'Mohammedia', 'ar': 'المحمدية', 'fr': 'Mohammedia', 'lat': 33.6866, 'lon': -7.3837},
    'Khouribga': {'id': 83, 'en': 'Khouribga', 'ar': 'خريبكة', 'fr': 'Khouribga', 'lat': 32.8811, 'lon': -6.9063},
    'El Jadida': {'id': 74, 'en': 'El Jadida', 'ar': 'الجديدة', 'fr': 'El Jadida', 'lat': 33.2316, 'lon': -8.5007},
    'Taza': {'id': 105, 'en': 'Taza', 'ar': 'تازة', 'fr': 'Taza', 'lat': 34.2133, 'lon': -4.0103},
    'Nador': {'id': 91, 'en': 'Nador', 'ar': 'الناظور', 'fr': 'Nador', 'lat': 35.1681, 'lon': -2.9287},
    'Settat': {'id': 98, 'en': 'Settat', 'ar': 'سطات', 'fr': 'Settat', 'lat': 33.0018, 'lon': -7.6164},
    'Larache': {'id': 87, 'en': 'Larache', 'ar': 'العرائش', 'fr': 'Larache', 'lat': 35.1932, 'lon': -6.1563},
    'Khenifra': {'id': 82, 'en': 'Khenifra', 'ar': 'خنيفرة', 'fr': 'Khenifra', 'lat': 32.9359, 'lon': -5.6675},
    'Essaouira': {'id': 76, 'en': 'Essaouira', 'ar': 'الصويرة', 'fr': 'Essaouira', 'lat': 31.5085, 'lon': -9.7595},
    'Chefchaouen': {'id': 72, 'en': 'Chefchaouen', 'ar': 'شفشاون', 'fr': 'Chefchaouen', 'lat': 35.1688, 'lon': -5.2636},
    'Beni Mellal': {'id': 68, 'en': 'Beni Mellal', 'ar': 'بني ملال', 'fr': 'Beni Mellal', 'lat': 32.3373, 'lon': -6.3498},
    'Al Hoceima': {'id': 79, 'en': 'Al Hoceima', 'ar': 'الحسيمة', 'fr': 'Al Hoceima', 'lat': 35.2517, 'lon': -3.9316},
    'Taroudant': {'id': 103, 'en': 'Taroudant', 'ar': 'تارودانت', 'fr': 'Taroudant', 'lat': 30.4703, 'lon': -8.8770},
    'Ouazzane': {'id': 92, 'en': 'Ouazzane', 'ar': 'وزان', 'fr': 'Ouazzane', 'lat': 34.7936, 'lon': -5.5836},
    'Sefrou': {'id': 97, 'en': 'Sefrou', 'ar': 'صفرو', 'fr': 'Sefrou', 'lat': 33.8307, 'lon': -4.8372},
    'Berkane': {'id': 69, 'en': 'Berkane', 'ar': 'بركان', 'fr': 'Berkane', 'lat': 34.9218, 'lon': -2.3200},
    'Errachidia': {'id': 75, 'en': 'Errachidia', 'ar': 'الراشيدية', 'fr': 'Errachidia', 'lat': 31.9314, 'lon': -4.4244},
    'Laayoune': {'id': 85, 'en': 'Laayoune', 'ar': 'العيون', 'fr': 'Laayoune', 'lat': 27.1253, 'lon': -13.1625},
    'Tiznit': {'id': 106, 'en': 'Tiznit', 'ar': 'تزنيت', 'fr': 'Tiznit', 'lat': 29.6974, 'lon': -9.7316},
    'Ifrane': {'id': 80, 'en': 'Ifrane', 'ar': 'إفران', 'fr': 'Ifrane', 'lat': 33.5228, 'lon': -5.1106},
    'Zagora': {'id': 107, 'en': 'Zagora', 'ar': 'زاكورة', 'fr': 'Zagora', 'lat': 30.3314, 'lon': -5.8372},
    'Dakhla': {'id': 73, 'en': 'Dakhla', 'ar': 'الداخلة', 'fr': 'Dakhla', 'lat': 23.6848, 'lon': -15.9570},
    'Tan Tan': {'id': 102, 'en': 'Tan Tan', 'ar': 'طانطان', 'fr': 'Tan-Tan', 'lat': 28.4378, 'lon': -11.1031},
    'Sidi Kacem': {'id': 99, 'en': 'Sidi Kacem', 'ar': 'سيدي قاسم', 'fr': 'Sidi Kacem', 'lat': 34.2214, 'lon': -5.7081},
    'Ksar Lekbir': {'id': 84, 'en': 'Ksar Lekbir', 'ar': 'القصر الكبير', 'fr': 'Ksar el-Kebir', 'lat': 35.0119, 'lon': -5.9033},
    'Taounate': {'id': 104, 'en': 'Taounate', 'ar': 'تاونات', 'fr': 'Taounate', 'lat': 34.5386, 'lon': -4.6372},
    'Assila': {'id': 67, 'en': 'Assila', 'ar': 'أصيلة', 'fr': 'Asilah', 'lat': 35.4650, 'lon': -6.0362},
    'Boulemane': {'id': 70, 'en': 'Boulemane', 'ar': 'بولمان', 'fr': 'Boulemane', 'lat': 33.3614, 'lon': -4.7331},
    'Kalaat Sraghna': {'id': 94, 'en': 'Kalaat Sraghna', 'ar': 'قلعة السراغنة', 'fr': 'Kalaat es-Sraghna', 'lat': 32.0587, 'lon': -7.4103},
    'Lagouira': {'id': 86, 'en': 'Lagouira', 'ar': 'الكويرة', 'fr': 'Lagouira', 'lat': 20.9331, 'lon': -17.0439},
    'Moulay Idriss Zerhoun': {'id': 108, 'en': 'Moulay Idriss Zerhoun', 'ar': 'مولاي إدريس زرهون', 'fr': 'Moulay Idriss Zerhoun', 'lat': 34.0581, 'lon': -5.5203},
    'Smara': {'id': 77, 'en': 'Smara', 'ar': 'السمارة', 'fr': 'Smara', 'lat': 26.7386, 'lon': -11.6719}
}
