# Translation dictionaries
TRANSLATIONS = {
    'en': {
        'app_title': 'Salah Times',
        'next_prayer': 'NEXT PRAYER',
        'tomorrow': 'Tomorrow',
        'loading': '🔄 Loading prayer times...',
        'refresh': '↻ Refresh',
        'error': '⚠️ Error: {}\n\nPlease check your internet connection\nand try refreshing.',
        'welcome': '🕌 Welcome to Salah Times',
        'select_city': 'Please select your default city for prayer times:',
        'search_city': 'Search for a city...',
        'cancel': 'Cancel',
        'set_default': 'Set as Default',
        'change_city': 'Change Default City',
        'iqama_time': 'Time before Iqama of {}: {:02d}:{:02d}:{:02d}',
        'iqama_passed': 'Iqama of {}: 00:00:00',
        'hijri_unavailable': 'Hijri date unavailable',
        'hijri_approx': '{} AH (Approximate)',
        'morocco': 'Morocco',
        'months': ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        'days': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        'hijri_months': {'Muharram': 'Muharram', 'Safar': 'Safar', 'Rabi\'al-awwal': 'Rabi al-Awwal', 'Rabi\'al-thani': 'Rabi al-Thani', 'Jumada al-awwal': 'Jumada al-Awwal', 'Jumada al-thani': 'Jumada al-Thani', 'Rajab': 'Rajab', 'Sha\'ban': 'Shaban', 'Ramadan': 'Ramadan', 'Shawwal': 'Shawwal', 'Dhu al-Qi\'dah': 'Dhu al-Qidah', 'Dhu al-Hijjah': 'Dhu al-Hijjah'},
        'language': 'Language',
        'settings': 'Settings',
        'monthly_calendar': 'Monthly Calendar',
        'weekly_schedule': 'Weekly Schedule',
        'refresh_db': '🗄️ Refresh DB',
        'refresh_db_updating': '⏳ Updating...',
        'refresh_db_prompt_title': 'Update Prayer Times',
        'refresh_db_prompt_msg': '30 days have passed since the last database update.\nRefresh all prayer times now?',
        'timezone_view': 'Multiple Timezones',
        'view': 'View',
        'tray_show': '🪟 Show Main Window',
        'tray_refresh': '↻ Refresh Prayer Times',
        'tray_quit': '❌ Quit',
        'no_internet_title': 'No Internet Connection',
        'no_internet_msg': 'Cannot update without an internet connection.\n\nCurrent database:\n• {} cities\n• From: {}\n• Until: {}',
        'prayers': {
            'Date': 'Date',
            'Fajr': 'Fajr',
            'Dohr': 'Dhuhr',
            'Asr': 'Asr',
            'Maghreb': 'Maghrib',
            'Isha': 'Isha'
        }
    },
    'ar': {
        'app_title': 'مواقيت الصلاة',
        'next_prayer': 'الصلاة القادمة',
        'tomorrow': 'غداً',
        'loading': '🔄 جاري تحميل مواقيت الصلاة...',
        'refresh': '↻ تحديث',
        'error': '⚠️ خطأ: {}\n\nيرجى التحقق من اتصال الإنترنت\nوإعادة المحاولة.',
        'welcome': '🕌 مرحباً بك في مواقيت الصلاة',
        'select_city': 'يرجى اختيار مدينتك الافتراضية لمواقيت الصلاة:',
        'search_city': 'البحث عن مدينة...',
        'cancel': 'إلغاء',
        'set_default': 'تعيين كافتراضي',
        'change_city': 'تغيير المدينة الافتراضية',
        'iqama_time': 'الوقت المتبقي لإقامة {}: {:02d}:{:02d}:{:02d}',
        'iqama_passed': 'إقامة {}: 00:00:00',
        'hijri_unavailable': 'التاريخ الهجري غير متوفر',
        'hijri_approx': '{} هـ (تقريبي)',
        'morocco': 'المغرب',
        'months': ['يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو', 'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'],
        'days': ['الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت', 'الأحد'],
        'hijri_months': {'Muharram': 'محرم', 'Safar': 'صفر', 'Rabi\'al-awwal': 'ربيع الأول', 'Rabi\'al-thani': 'ربيع الثاني', 'Jumada al-awwal': 'جمادى الأولى', 'Jumada al-thani': 'جمادى الثانية', 'Rajab': 'رجب', 'Sha\'ban': 'شعبان', 'Ramadan': 'رمضان', 'Shawwal': 'شوال', 'Dhu al-Qi\'dah': 'ذو القعدة', 'Dhu al-Hijjah': 'ذو الحجة'},
        'language': 'اللغة',
        'settings': 'الإعدادات',
        'monthly_calendar': 'التقويم الشهري',
        'weekly_schedule': 'الجدول الأسبوعي',
        'refresh_db': '🗄️ تحديث قاعدة البيانات',
        'refresh_db_updating': '⏳ جاري التحديث...',
        'refresh_db_prompt_title': 'تحديث مواقيت الصلاة',
        'refresh_db_prompt_msg': 'مرّ 30 يوماً منذ آخر تحديث لقاعدة البيانات.\nهل تريد تحديث مواقيت الصلاة الآن؟',
        'timezone_view': 'مناطق زمنية متعددة',
        'view': 'عرض',
        'tray_show': '🪟 عرض النافذة الرئيسية',
        'tray_refresh': '↻ تحديث مواقيت الصلاة',
        'tray_quit': '❌ خروج',
        'no_internet_title': 'لا يوجد اتصال بالإنترنت',
        'no_internet_msg': 'لا يمكن التحديث بدون اتصال بالإنترنت.\n\nقاعدة البيانات الحالية:\n• {} مدينة\n• من: {}\n• حتى: {}',
        'prayers': {
            'Date': 'التاريخ',
            'Fajr': 'الفجر',
            'Dohr': 'الظهر',
            'Asr': 'العصر',
            'Maghreb': 'المغرب',
            'Isha': 'العشاء'
        }
    },
    'fr': {
        'app_title': 'Horaires de Priere',
        'next_prayer': 'PROCHAINE PRIERE',
        'tomorrow': 'Demain',
        'loading': '🔄 Chargement des horaires de priere...',
        'refresh': '↻ Actualiser',
        'error': '⚠️ Erreur: {}\n\nVeuillez verifier votre connexion Internet\net reessayer.',
        'welcome': '🕌 Bienvenue dans Horaires de Priere',
        'select_city': 'Veuillez selectionner votre ville par defaut pour les horaires de priere:',
        'search_city': 'Rechercher une ville...',
        'cancel': 'Annuler',
        'set_default': 'Definir par defaut',
        'change_city': 'Changer la ville par defaut',
        'iqama_time': 'Temps avant Iqama de {}: {:02d}:{:02d}:{:02d}',
        'iqama_passed': 'Iqama de {}: 00:00:00',
        'hijri_unavailable': 'Date hijri non disponible',
        'hijri_approx': '{} AH (Approximatif)',
        'morocco': 'Maroc',
        'months': ['Janvier', 'Fevrier', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Aout', 'Septembre', 'Octobre', 'Novembre', 'Decembre'],
        'days': ['Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi', 'Dimanche'],
        'hijri_months': {'Muharram': 'Muharram', 'Safar': 'Safar', 'Rabi\'al-awwal': 'Rabi al-Awwal', 'Rabi\'al-thani': 'Rabi al-Thani', 'Jumada al-awwal': 'Jumada al-Awwal', 'Jumada al-thani': 'Jumada al-Thani', 'Rajab': 'Rajab', 'Sha\'ban': 'Shaban', 'Ramadan': 'Ramadan', 'Shawwal': 'Shawwal', 'Dhu al-Qi\'dah': 'Dhu al-Qidah', 'Dhu al-Hijjah': 'Dhu al-Hijjah'},
        'language': 'Langue',
        'settings': 'Parametres',
        'monthly_calendar': 'Calendrier Mensuel',
        'weekly_schedule': 'Horaire Hebdomadaire',
        'refresh_db': '🗄️ Actualiser BD',
        'refresh_db_updating': '⏳ Mise a jour...',
        'refresh_db_prompt_title': 'Mise a jour des horaires',
        'refresh_db_prompt_msg': '30 jours se sont ecoules depuis la derniere mise a jour.\nActualiser les horaires de priere maintenant?',
        'timezone_view': 'Fuseaux Horaires Multiples',
        'view': 'Affichage',
        'tray_show': '🪟 Afficher la fenetre',
        'tray_refresh': '↻ Actualiser les horaires',
        'tray_quit': '❌ Quitter',
        'no_internet_title': 'Pas de connexion Internet',
        'no_internet_msg': 'Impossible de mettre a jour sans connexion.\n\nBase de donnees actuelle:\n• {} villes\n• Du: {}\n• Au: {}',
        'prayers': {
            'Date': 'Date',
            'Fajr': 'Fajr',
            'Dohr': 'Dhuhr',
            'Asr': 'Asr',
            'Maghreb': 'Maghrib',
            'Isha': 'Isha'
        }
    }
}

CITY_SLUGS = {
    'Agadir': 'agadir', 'Al Hoceima': 'al-hoceima', 'Assila': 'assila',
    'Beni Mellal': 'beni-mellal', 'Berkane': 'berkane', 'Boulemane': 'boulemane',
    'Casablanca': 'casablanca', 'Chefchaouen': 'chefchaouen', 'Dakhla': 'dakhla',
    'El Jadida': 'el-jadida', 'Errachidia': 'errachidia', 'Essaouira': 'essaouira',
    'Fes': 'fes', 'Ifrane': 'ifrane', 'Kalaat Sraghna': 'kalaat-sraghna',
    'Kenitra': 'kenitra', 'Khenifra': 'khenifra', 'Khouribga': 'khouribga',
    'Ksar Lekbir': 'ksar-lekbir', 'Laayoune': 'laayoune', 'Lagouira': 'lagouira',
    'Larache': 'larache', 'Marrakech': 'marrakech', 'Meknes': 'meknes',
    'Mohammedia': 'mohammedia', 'Moulay Idriss Zerhoun': 'moulay-idriss-zerhoun',
    'Nador': 'nador', 'Ouazzane': 'ouazzane', 'Oujda': 'oujda', 'Rabat': 'rabat',
    'Safi': 'safi', 'Sefrou': 'sefrou', 'Settat': 'settat', 'Sidi Kacem': 'sidi-kacem',
    'Smara': 'smara', 'Tan Tan': 'tan-tan', 'Tangier': 'tanger', 'Taounate': 'taounate',
    'Taroudant': 'taroudant', 'Taza': 'taza', 'Tetouan': 'tetouan', 'Tiznit': 'tiznit',
    'Zagora': 'zagora',
    # ── new countries (2026-09 yabiladi expansion) ──
    'Boksburg': 'boksburg',
    'Durban': 'durban',
    'Germiston': 'germiston',
    'Johannesburg': 'johannesburg',
    'Le Cap': 'le-cap',
    'Pretoria': 'pretoria',
    'Alger': 'alger',
    'Annaba': 'annaba',
    'Batna': 'batna',
    'Bir El Djir': 'bir-el-djir',
    'Biskra': 'biskra',
    'Blida': 'blida',
    'Bordj Bou Arreridj': 'bordj-bou-arreridj',
    'Béchar': 'bechar',
    'Béjaïa': 'bejaia',
    'Chlef': 'chlef',
    'Constantine': 'constantine',
    'Djelfa': 'djelfa',
    'El Eulma': 'el-eulma',
    'El Khroub': 'el-khroub',
    'El Oued': 'el-oued',
    'Jijel': 'jijel',
    'Laghouat': 'laghouat',
    "M'Sila": 'm-sila',
    'Mostaganem': 'mostaganem',
    'Médéa': 'medea',
    'Oran': 'oran',
    'Ouargla': 'ouargla',
    'Sidi bel Abbès': 'sidi-bel-abbes',
    'Skikda': 'skikda',
    'Souk Ahras': 'souk-ahras',
    'Sétif': 'setif',
    'Tiaret': 'tiaret',
    'Tizi Ouzou': 'tizi-ouzou',
    'Tlemcen': 'tlemcen',
    'Tébessa': 'tebessa',
    'Berlin': 'berlin',
    'Bielefeld': 'bielefeld',
    'Bochum': 'bochum',
    'Bonn': 'bonn',
    'Brême': 'breme',
    'Cologne': 'cologne',
    'Dortmund': 'dortmund',
    'Dresde': 'dresde',
    'Duisbourg': 'duisbourg',
    'Düsseldorf': 'dusseldorf',
    'Essen': 'essen',
    'Francfort': 'francfort',
    'Hambourg': 'hambourg',
    'Hanovre': 'hanovre',
    'Leipzig': 'leipzig',
    'Mannheim': 'mannheim',
    'Munich': 'munich',
    'Nuremberg': 'nuremberg',
    'Stuttgart': 'stuttgart',
    'Wuppertal': 'wuppertal',
    'Djeddah': 'djeddah',
    'La Mecque': 'la-mecque',
    'Médine': 'medine',
    'Riyad': 'riyad',
    'Adélaïde': 'adelaide',
    'Brisbane': 'brisbane',
    'Canberra': 'canberra',
    'Geelong': 'geelong',
    'Hobart': 'hobart',
    'Melbourne': 'melbourne',
    'Newcastle': 'newcastle',
    'Perth': 'perth',
    'Sydney': 'sydney',
    'Wollongong': 'wollongong',
    'Linz': 'linz',
    'Vienne': 'vienne',
    'Villach': 'villach',
    'Anvers': 'anvers',
    'Bruxelles': 'bruxelles',
    'Charleroi': 'charleroi',
    'Gand': 'gand',
    'Hasselt': 'hasselt',
    'Liège': 'liege',
    'Mons': 'mons',
    'Namur': 'namur',
    'Renaix': 'renaix',
    'Tournai': 'tournai',
    'Verviers': 'verviers',
    'Yaoundé': 'yaounde',
    'Montréal': 'montreal',
    'Ottawa': 'ottawa',
    'Québec': 'quebec',
    'Toronto': 'toronto',
    'Vancouver': 'vancouver',
    'Abidjan': 'abidjan',
    'Copenhague': 'copenhague',
    'Le Caire': 'le-caire',
    'Abou Dhabi': 'abou-dhabi',
    'Dubaï': 'dubai',
    'Albacete': 'albacete',
    'Alcalá de Henares': 'alcala-de-henares',
    'Alcorcón': 'alcorcon',
    'Algeciras': 'algeciras',
    'Alicante': 'alicante',
    'Almería': 'almeria',
    'Badajoz': 'badajoz',
    'Badalona': 'badalona',
    'Barcelona': 'barcelona',
    'Bilbao': 'bilbao',
    'Burgos': 'burgos',
    'Cartagena': 'cartagena',
    'Castellón de la Plana': 'castellon-de-la-plana',
    'Cádiz': 'cadiz',
    'Córdoba': 'cordoba',
    'Elche': 'elche',
    'Fuenlabrada': 'fuenlabrada',
    'Getafe': 'getafe',
    'Gijón': 'gijon',
    'Granada': 'granada',
    'Huelva': 'huelva',
    'Jaén': 'jaen',
    'Jerez de la Frontera': 'jerez-de-la-frontera',
    "L'hospitalet De Llobregat": 'l-hospitalet-de-llobregat',
    'La Coruña': 'la-coruna',
    'Las Palmas De Gran Canaria': 'las-palmas-de-gran-canaria',
    'Leganés': 'leganes',
    'León': 'leon',
    'Logroño': 'logrono',
    'Lérida': 'lerida',
    'Madrid': 'madrid',
    'Marbella': 'marbella',
    'Murcia': 'murcia',
    'Málaga': 'malaga',
    'Móstoles': 'mostoles',
    'Oviedo': 'oviedo',
    'Palma de Mallorca': 'palma-de-mallorca',
    'Pamplona': 'pamplona',
    'Reus': 'reus',
    'Sabadell': 'sabadell',
    'Salamanca': 'salamanca',
    'San Cristóbal de La Laguna': 'san-cristobal-de-la-laguna',
    'San Sebastián': 'san-sebastian',
    'Santa Cruz De Tenerife': 'santa-cruz-de-tenerife',
    'Santander': 'santander',
    'Sevilla': 'sevilla',
    'Tarifa': 'tarifa',
    'Tarragona': 'tarragona',
    'Terrassa': 'terrassa',
    'Valencia': 'valencia',
    'Valladolid': 'valladolid',
    'Vigo': 'vigo',
    'Vitoria': 'vitoria',
    'Zaragoza': 'zaragoza',
    'Anchorage': 'anchorage',
    'Atlanta': 'atlanta',
    'Chicago': 'chicago',
    'Dallas': 'dallas',
    'Denver': 'denver',
    'Détroit': 'detroit',
    'Honolulu': 'honolulu',
    'Houston': 'houston',
    'Los Angeles': 'los-angeles',
    'Miami': 'miami',
    'New York': 'new-york',
    'Seattle': 'seattle',
    'Washington': 'washington',
    'Espoo': 'espoo',
    'Helsinki': 'helsinki',
    'Turku': 'turku',
    'Vantaa': 'vantaa',
    'Albi': 'albi',
    'Amiens': 'amiens',
    'Angers': 'angers',
    'Angoulême': 'angouleme',
    'Annecy': 'annecy',
    'Arras': 'arras',
    'Auxerre': 'auxerre',
    'Avignon': 'avignon',
    'Bar-le-Duc': 'bar-le-duc',
    'Bayeux': 'bayeux',
    'Beauvais': 'beauvais',
    'Belfort': 'belfort',
    'Besançon': 'besancon',
    'Bordeaux': 'bordeaux',
    'Bourges': 'bourges',
    'Caen': 'caen',
    'Carcassonne': 'carcassonne',
    'Chalon sur Marne': 'chalon-sur-marne',
    'Chalon sur Saône': 'chalon-sur-saone',
    'Chambéry': 'chambery',
    'Charleville-Mézières': 'charleville-mezieres',
    'Chartres': 'chartres',
    'Chaumont': 'chaumont',
    'Cherbourg': 'cherbourg',
    'Cholet': 'cholet',
    'Château-Chinon': 'chateau-chinon',
    'Châtellerault': 'chatellerault',
    'Clermont-Ferrand': 'clermont-ferrand',
    'Dieppe': 'dieppe',
    'Dijon': 'dijon',
    'Douai': 'douai',
    'Draguignan': 'draguignan',
    'Epinal': 'epinal',
    'Foix': 'foix',
    'Forbach': 'forbach',
    'La Rochelle': 'la-rochelle',
    'Langres': 'langres',
    'Laval': 'laval',
    'Le Havre': 'le-havre',
    'Le Mans': 'le-mans',
    'Le Puy': 'le-puy',
    'Lens': 'lens',
    'Lille': 'lille',
    'Limoges': 'limoges',
    'Lyon': 'lyon',
    'Macon': 'macon',
    'Marseille': 'marseille',
    'Meaux': 'meaux',
    'Melun': 'melun',
    'Metz': 'metz',
    'Montluçon': 'montlucon',
    'Montpellier': 'montpellier',
    'Mulhouse': 'mulhouse',
    'Nancy': 'nancy',
    'Nantes': 'nantes',
    'Nevers': 'nevers',
    'Nice': 'nice',
    'Niort': 'niort',
    'Nogent sur Seine': 'nogent-sur-seine',
    'Nîmes': 'nimes',
    'Orléans': 'orleans',
    'Paris': 'paris',
    'Pau': 'pau',
    'Perpignan': 'perpignan',
    'Poitiers': 'poitiers',
    'Pontarlier': 'pontarlier',
    'Péronne': 'peronne',
    'Reims': 'reims',
    'Rennes': 'rennes',
    'Roanne': 'roanne',
    'Rodez': 'rodez',
    'Rouen': 'rouen',
    'Saint Etienne': 'saint-etienne',
    'Saint-Dizier': 'saint-dizier',
    'Saint-Dié': 'saint-die',
    'Strasbourg': 'strasbourg',
    'Thionville': 'thionville',
    'Toul': 'toul',
    'Toulon': 'toulon',
    'Toulouse': 'toulouse',
    'Tours': 'tours',
    'Troyes': 'troyes',
    'Valence': 'valence',
    'Valenciennes': 'valenciennes',
    'Verdun': 'verdun',
    'Vichy': 'vichy',
    'Accra': 'accra',
    'Kumasi': 'kumasi',
    'Sekondi': 'sekondi',
    'Takoradi': 'takoradi',
    'Tamale': 'tamale',
    'Tema': 'tema',
    'Bagdad': 'bagdad',
    'Dublin': 'dublin',
    'Bari': 'bari',
    'Bologna': 'bologna',
    'Cagliari': 'cagliari',
    'Catania': 'catania',
    'Firenze': 'firenze',
    'Genoa': 'genoa',
    'Milan': 'milan',
    'Napoli': 'napoli',
    'Palermo': 'palermo',
    'Roma': 'roma',
    'Turin': 'turin',
    'Venezia': 'venezia',
    'Verona': 'verona',
    'Fukuoka': 'fukuoka',
    'Hiroshima': 'hiroshima',
    'Kawasaki': 'kawasaki',
    'Kitakyushu': 'kitakyushu',
    'Kobe': 'kobe',
    'Kyoto': 'kyoto',
    'Nagoya': 'nagoya',
    'Osaka': 'osaka',
    'Sapporo': 'sapporo',
    'Tokyo': 'tokyo',
    'Beyrouth': 'beyrouth',
    'Tripoli': 'tripoli',
    'Bamako': 'bamako',
    'Nouakchott': 'nouakchott',
    'Ibadan': 'ibadan',
    'Ilesha': 'ilesha',
    'Ilorin': 'ilorin',
    'Kano': 'kano',
    'Lagos': 'lagos',
    'Onitsha': 'onitsha',
    'Zaria': 'zaria',
    'Oslo': 'oslo',
    'Auckland': 'auckland',
    'Dunedin': 'dunedin',
    'Hamilton': 'hamilton',
    'Wellington': 'wellington',
    'Almere': 'almere',
    'Amersfoort': 'amersfoort',
    'Amsterdam': 'amsterdam',
    'Apeldoorn': 'apeldoorn',
    'Arnhem': 'arnhem',
    'Bois-le-Duc': 'bois-le-duc',
    'Bréda': 'breda',
    'Eindhoven': 'eindhoven',
    'Enschede': 'enschede',
    'Groningue': 'groningue',
    'Haarlem': 'haarlem',
    'Haarlemmermeer': 'haarlemmermeer',
    'La Haye': 'la-haye',
    'Maastricht': 'maastricht',
    'Nimègue': 'nimegue',
    'Rotterdam': 'rotterdam',
    'Tilburg': 'tilburg',
    'Utrecht': 'utrecht',
    'Zaanstad': 'zaanstad',
    'Zoetermeer': 'zoetermeer',
    'Zwolle': 'zwolle',
    'Doha': 'doha',
    'Belfast': 'belfast',
    'Birmingham': 'birmingham',
    'Bristol': 'bristol',
    'Cardiff': 'cardiff',
    'Glasgow': 'glasgow',
    'Liverpool': 'liverpool',
    'London': 'london',
    'Manchester': 'manchester',
    'Sheffield': 'sheffield',
    'Dakar': 'dakar',
    'Borås': 'boras',
    'Malmö': 'malmo',
    'Stockholm': 'stockholm',
    'Uppsala': 'uppsala',
    'Örebro': 'orebro',
    'Berne': 'berne',
    'Bienne': 'bienne',
    'Bâle': 'bale',
    'Fribourg': 'fribourg',
    'Genève': 'geneve',
    'La Chaux-de-Fonds': 'la-chaux-de-fonds',
    'Lausanne': 'lausanne',
    'Lucerne': 'lucerne',
    'Lugano': 'lugano',
    'Montreux': 'montreux',
    'Neuchatel': 'neuchatel',
    'Saint-Gall': 'saint-gall',
    'Thoune': 'thoune',
    'Winterthour': 'winterthour',
    'Zurich': 'zurich',
    'Damas': 'damas',
    'Ariana': 'ariana',
    'Ben Arous': 'ben-arous',
    'Bizerte': 'bizerte',
    'Béja': 'beja',
    'Gabès': 'gabes',
    'Gafsa': 'gafsa',
    'Jendouba': 'jendouba',
    'Kairouan': 'kairouan',
    'Kasserine': 'kasserine',
    'Kébili': 'kebili',
    'La Manouba': 'la-manouba',
    'Le Kef': 'le-kef',
    'Mahdia': 'mahdia',
    'Monastir': 'monastir',
    'Médenine': 'medenine',
    'Nabeul': 'nabeul',
    'Sfax': 'sfax',
    'Sidi Bouzid': 'sidi-bouzid',
    'Siliana': 'siliana',
    'Sousse': 'sousse',
    'Tataouine': 'tataouine',
    'Tozeur': 'tozeur',
    'Tunis': 'tunis',
    'Zaghouan': 'zaghouan',
}

BASE_URL = 'https://www.yabiladi.com/prieres/details/{}/{}.html'
SCRAPER_HEADERS = {'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}

CITIES = {
    'Tangier': {'id': 101, 'en': 'Tangier', 'ar': 'طنجة', 'fr': 'Tanger', 'lat': 35.7595, 'lon': -5.8340, 'country': 'Maroc'},
    'Casablanca': {'id': 71, 'en': 'Casablanca', 'ar': 'الدار البيضاء', 'fr': 'Casablanca', 'lat': 33.5731, 'lon': -7.5898, 'country': 'Maroc'},
    'Rabat': {'id': 95, 'en': 'Rabat', 'ar': 'الرباط', 'fr': 'Rabat', 'lat': 34.0209, 'lon': -6.8416, 'country': 'Maroc'},
    'Marrakech': {'id': 88, 'en': 'Marrakech', 'ar': 'مراكش', 'fr': 'Marrakech', 'lat': 31.6295, 'lon': -7.9811, 'country': 'Maroc'},
    'Fes': {'id': 78, 'en': 'Fes', 'ar': 'فاس', 'fr': 'Fes', 'lat': 34.0181, 'lon': -5.0078, 'country': 'Maroc'},
    'Agadir': {'id': 66, 'en': 'Agadir', 'ar': 'أكادير', 'fr': 'Agadir', 'lat': 30.4278, 'lon': -9.5981, 'country': 'Maroc'},
    'Meknes': {'id': 89, 'en': 'Meknes', 'ar': 'مكناس', 'fr': 'Meknes', 'lat': 33.8935, 'lon': -5.5473, 'country': 'Maroc'},
    'Oujda': {'id': 93, 'en': 'Oujda', 'ar': 'وجدة', 'fr': 'Oujda', 'lat': 34.6814, 'lon': -1.9086, 'country': 'Maroc'},
    'Kenitra': {'id': 81, 'en': 'Kenitra', 'ar': 'القنيطرة', 'fr': 'Kenitra', 'lat': 34.2610, 'lon': -6.5802, 'country': 'Maroc'},
    'Tetouan': {'id': 100, 'en': 'Tetouan', 'ar': 'تطوان', 'fr': 'Tetouan', 'lat': 35.5889, 'lon': -5.3626, 'country': 'Maroc'},
    'Safi': {'id': 96, 'en': 'Safi', 'ar': 'آسفي', 'fr': 'Safi', 'lat': 32.2994, 'lon': -9.2372, 'country': 'Maroc'},
    'Mohammedia': {'id': 90, 'en': 'Mohammedia', 'ar': 'المحمدية', 'fr': 'Mohammedia', 'lat': 33.6866, 'lon': -7.3837, 'country': 'Maroc'},
    'Khouribga': {'id': 83, 'en': 'Khouribga', 'ar': 'خريبكة', 'fr': 'Khouribga', 'lat': 32.8811, 'lon': -6.9063, 'country': 'Maroc'},
    'El Jadida': {'id': 74, 'en': 'El Jadida', 'ar': 'الجديدة', 'fr': 'El Jadida', 'lat': 33.2316, 'lon': -8.5007, 'country': 'Maroc'},
    'Taza': {'id': 105, 'en': 'Taza', 'ar': 'تازة', 'fr': 'Taza', 'lat': 34.2133, 'lon': -4.0103, 'country': 'Maroc'},
    'Nador': {'id': 91, 'en': 'Nador', 'ar': 'الناظور', 'fr': 'Nador', 'lat': 35.1681, 'lon': -2.9287, 'country': 'Maroc'},
    'Settat': {'id': 98, 'en': 'Settat', 'ar': 'سطات', 'fr': 'Settat', 'lat': 33.0018, 'lon': -7.6164, 'country': 'Maroc'},
    'Larache': {'id': 87, 'en': 'Larache', 'ar': 'العرائش', 'fr': 'Larache', 'lat': 35.1932, 'lon': -6.1563, 'country': 'Maroc'},
    'Khenifra': {'id': 82, 'en': 'Khenifra', 'ar': 'خنيفرة', 'fr': 'Khenifra', 'lat': 32.9359, 'lon': -5.6675, 'country': 'Maroc'},
    'Essaouira': {'id': 76, 'en': 'Essaouira', 'ar': 'الصويرة', 'fr': 'Essaouira', 'lat': 31.5085, 'lon': -9.7595, 'country': 'Maroc'},
    'Chefchaouen': {'id': 72, 'en': 'Chefchaouen', 'ar': 'شفشاون', 'fr': 'Chefchaouen', 'lat': 35.1688, 'lon': -5.2636, 'country': 'Maroc'},
    'Beni Mellal': {'id': 68, 'en': 'Beni Mellal', 'ar': 'بني ملال', 'fr': 'Beni Mellal', 'lat': 32.3373, 'lon': -6.3498, 'country': 'Maroc'},
    'Al Hoceima': {'id': 79, 'en': 'Al Hoceima', 'ar': 'الحسيمة', 'fr': 'Al Hoceima', 'lat': 35.2517, 'lon': -3.9316, 'country': 'Maroc'},
    'Taroudant': {'id': 103, 'en': 'Taroudant', 'ar': 'تارودانت', 'fr': 'Taroudant', 'lat': 30.4703, 'lon': -8.8770, 'country': 'Maroc'},
    'Ouazzane': {'id': 92, 'en': 'Ouazzane', 'ar': 'وزان', 'fr': 'Ouazzane', 'lat': 34.7936, 'lon': -5.5836, 'country': 'Maroc'},
    'Sefrou': {'id': 97, 'en': 'Sefrou', 'ar': 'صفرو', 'fr': 'Sefrou', 'lat': 33.8307, 'lon': -4.8372, 'country': 'Maroc'},
    'Berkane': {'id': 69, 'en': 'Berkane', 'ar': 'بركان', 'fr': 'Berkane', 'lat': 34.9218, 'lon': -2.3200, 'country': 'Maroc'},
    'Errachidia': {'id': 75, 'en': 'Errachidia', 'ar': 'الراشيدية', 'fr': 'Errachidia', 'lat': 31.9314, 'lon': -4.4244, 'country': 'Maroc'},
    'Laayoune': {'id': 85, 'en': 'Laayoune', 'ar': 'العيون', 'fr': 'Laayoune', 'lat': 27.1253, 'lon': -13.1625, 'country': 'Maroc'},
    'Tiznit': {'id': 106, 'en': 'Tiznit', 'ar': 'تزنيت', 'fr': 'Tiznit', 'lat': 29.6974, 'lon': -9.7316, 'country': 'Maroc'},
    'Ifrane': {'id': 80, 'en': 'Ifrane', 'ar': 'إفران', 'fr': 'Ifrane', 'lat': 33.5228, 'lon': -5.1106, 'country': 'Maroc'},
    'Zagora': {'id': 107, 'en': 'Zagora', 'ar': 'زاكورة', 'fr': 'Zagora', 'lat': 30.3314, 'lon': -5.8372, 'country': 'Maroc'},
    'Dakhla': {'id': 73, 'en': 'Dakhla', 'ar': 'الداخلة', 'fr': 'Dakhla', 'lat': 23.6848, 'lon': -15.9570, 'country': 'Maroc'},
    'Tan Tan': {'id': 102, 'en': 'Tan Tan', 'ar': 'طانطان', 'fr': 'Tan-Tan', 'lat': 28.4378, 'lon': -11.1031, 'country': 'Maroc'},
    'Sidi Kacem': {'id': 99, 'en': 'Sidi Kacem', 'ar': 'سيدي قاسم', 'fr': 'Sidi Kacem', 'lat': 34.2214, 'lon': -5.7081, 'country': 'Maroc'},
    'Ksar Lekbir': {'id': 84, 'en': 'Ksar Lekbir', 'ar': 'القصر الكبير', 'fr': 'Ksar el-Kebir', 'lat': 35.0119, 'lon': -5.9033, 'country': 'Maroc'},
    'Taounate': {'id': 104, 'en': 'Taounate', 'ar': 'تاونات', 'fr': 'Taounate', 'lat': 34.5386, 'lon': -4.6372, 'country': 'Maroc'},
    'Assila': {'id': 67, 'en': 'Assila', 'ar': 'أصيلة', 'fr': 'Asilah', 'lat': 35.4650, 'lon': -6.0362, 'country': 'Maroc'},
    'Boulemane': {'id': 70, 'en': 'Boulemane', 'ar': 'بولمان', 'fr': 'Boulemane', 'lat': 33.3614, 'lon': -4.7331, 'country': 'Maroc'},
    'Kalaat Sraghna': {'id': 94, 'en': 'Kalaat Sraghna', 'ar': 'قلعة السراغنة', 'fr': 'Kalaat es-Sraghna', 'lat': 32.0587, 'lon': -7.4103, 'country': 'Maroc'},
    'Lagouira': {'id': 86, 'en': 'Lagouira', 'ar': 'الكويرة', 'fr': 'Lagouira', 'lat': 20.9331, 'lon': -17.0439, 'country': 'Maroc'},
    'Moulay Idriss Zerhoun': {'id': 108, 'en': 'Moulay Idriss Zerhoun', 'ar': 'مولاي إدريس زرهون', 'fr': 'Moulay Idriss Zerhoun', 'lat': 34.0581, 'lon': -5.5203, 'country': 'Maroc'},
    'Smara': {'id': 77, 'en': 'Smara', 'ar': 'السمارة', 'fr': 'Smara', 'lat': 26.7386, 'lon': -11.6719, 'country': 'Maroc'},
    # ── Afrique du sud (6 villes) ──
    'Boksburg': {'id': 370, 'en': 'Boksburg', 'ar': 'Boksburg', 'fr': 'Boksburg', 'lat': None, 'lon': None, 'country': 'Afrique du sud'},
    'Durban': {'id': 371, 'en': 'Durban', 'ar': 'Durban', 'fr': 'Durban', 'lat': None, 'lon': None, 'country': 'Afrique du sud'},
    'Germiston': {'id': 369, 'en': 'Germiston', 'ar': 'Germiston', 'fr': 'Germiston', 'lat': None, 'lon': None, 'country': 'Afrique du sud'},
    'Johannesburg': {'id': 374, 'en': 'Johannesburg', 'ar': 'Johannesburg', 'fr': 'Johannesburg', 'lat': None, 'lon': None, 'country': 'Afrique du sud'},
    'Le Cap': {'id': 372, 'en': 'Le Cap', 'ar': 'Le Cap', 'fr': 'Le Cap', 'lat': None, 'lon': None, 'country': 'Afrique du sud'},
    'Pretoria': {'id': 373, 'en': 'Pretoria', 'ar': 'Pretoria', 'fr': 'Pretoria', 'lat': None, 'lon': None, 'country': 'Afrique du sud'},
    # ── Algérie (30 villes) ──
    'Alger': {'id': 2, 'en': 'Alger', 'ar': 'Alger', 'fr': 'Alger', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Annaba': {'id': 280, 'en': 'Annaba', 'ar': 'Annaba', 'fr': 'Annaba', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Batna': {'id': 277, 'en': 'Batna', 'ar': 'Batna', 'fr': 'Batna', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Bir El Djir': {'id': 295, 'en': 'Bir El Djir', 'ar': 'Bir El Djir', 'fr': 'Bir El Djir', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Biskra': {'id': 282, 'en': 'Biskra', 'ar': 'Biskra', 'fr': 'Biskra', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Blida': {'id': 291, 'en': 'Blida', 'ar': 'Blida', 'fr': 'Blida', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Bordj Bou Arreridj': {'id': 288, 'en': 'Bordj Bou Arreridj', 'ar': 'Bordj Bou Arreridj', 'fr': 'Bordj Bou Arreridj', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Béchar': {'id': 289, 'en': 'Béchar', 'ar': 'Béchar', 'fr': 'Béchar', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Béjaïa': {'id': 287, 'en': 'Béjaïa', 'ar': 'Béjaïa', 'fr': 'Béjaïa', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Chlef': {'id': 286, 'en': 'Chlef', 'ar': 'Chlef', 'fr': 'Chlef', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Constantine': {'id': 276, 'en': 'Constantine', 'ar': 'Constantine', 'fr': 'Constantine', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Djelfa': {'id': 278, 'en': 'Djelfa', 'ar': 'Djelfa', 'fr': 'Djelfa', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'El Eulma': {'id': 294, 'en': 'El Eulma', 'ar': 'El Eulma', 'fr': 'El Eulma', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'El Khroub': {'id': 285, 'en': 'El Khroub', 'ar': 'El Khroub', 'fr': 'El Khroub', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'El Oued': {'id': 302, 'en': 'El Oued', 'ar': 'El Oued', 'fr': 'El Oued', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Jijel': {'id': 301, 'en': 'Jijel', 'ar': 'Jijel', 'fr': 'Jijel', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Laghouat': {'id': 297, 'en': 'Laghouat', 'ar': 'Laghouat', 'fr': 'Laghouat', 'lat': None, 'lon': None, 'country': 'Algérie'},
    "M'Sila": {'id': 292, 'en': "M'Sila", 'ar': "M'Sila", 'fr': "M'Sila", 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Mostaganem': {'id': 296, 'en': 'Mostaganem', 'ar': 'Mostaganem', 'fr': 'Mostaganem', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Médéa': {'id': 299, 'en': 'Médéa', 'ar': 'Médéa', 'fr': 'Médéa', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Oran': {'id': 275, 'en': 'Oran', 'ar': 'Oran', 'fr': 'Oran', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Ouargla': {'id': 303, 'en': 'Ouargla', 'ar': 'Ouargla', 'fr': 'Ouargla', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Sidi bel Abbès': {'id': 281, 'en': 'Sidi bel Abbès', 'ar': 'Sidi bel Abbès', 'fr': 'Sidi bel Abbès', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Skikda': {'id': 290, 'en': 'Skikda', 'ar': 'Skikda', 'fr': 'Skikda', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Souk Ahras': {'id': 293, 'en': 'Souk Ahras', 'ar': 'Souk Ahras', 'fr': 'Souk Ahras', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Sétif': {'id': 279, 'en': 'Sétif', 'ar': 'Sétif', 'fr': 'Sétif', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Tiaret': {'id': 283, 'en': 'Tiaret', 'ar': 'Tiaret', 'fr': 'Tiaret', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Tizi Ouzou': {'id': 300, 'en': 'Tizi Ouzou', 'ar': 'Tizi Ouzou', 'fr': 'Tizi Ouzou', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Tlemcen': {'id': 298, 'en': 'Tlemcen', 'ar': 'Tlemcen', 'fr': 'Tlemcen', 'lat': None, 'lon': None, 'country': 'Algérie'},
    'Tébessa': {'id': 284, 'en': 'Tébessa', 'ar': 'Tébessa', 'fr': 'Tébessa', 'lat': None, 'lon': None, 'country': 'Algérie'},
    # ── Allemagne (20 villes) ──
    'Berlin': {'id': 35, 'en': 'Berlin', 'ar': 'Berlin', 'fr': 'Berlin', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Bielefeld': {'id': 273, 'en': 'Bielefeld', 'ar': 'Bielefeld', 'fr': 'Bielefeld', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Bochum': {'id': 271, 'en': 'Bochum', 'ar': 'Bochum', 'fr': 'Bochum', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Bonn': {'id': 38, 'en': 'Bonn', 'ar': 'Bonn', 'fr': 'Bonn', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Brême': {'id': 265, 'en': 'Brême', 'ar': 'Brême', 'fr': 'Brême', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Cologne': {'id': 40, 'en': 'Cologne', 'ar': 'Cologne', 'fr': 'Cologne', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Dortmund': {'id': 263, 'en': 'Dortmund', 'ar': 'Dortmund', 'fr': 'Dortmund', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Dresde': {'id': 266, 'en': 'Dresde', 'ar': 'Dresde', 'fr': 'Dresde', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Duisbourg': {'id': 270, 'en': 'Duisbourg', 'ar': 'Duisbourg', 'fr': 'Duisbourg', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Düsseldorf': {'id': 41, 'en': 'Düsseldorf', 'ar': 'Düsseldorf', 'fr': 'Düsseldorf', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Essen': {'id': 264, 'en': 'Essen', 'ar': 'Essen', 'fr': 'Essen', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Francfort': {'id': 39, 'en': 'Francfort', 'ar': 'Francfort', 'fr': 'Francfort', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Hambourg': {'id': 37, 'en': 'Hambourg', 'ar': 'Hambourg', 'fr': 'Hambourg', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Hanovre': {'id': 268, 'en': 'Hanovre', 'ar': 'Hanovre', 'fr': 'Hanovre', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Leipzig': {'id': 267, 'en': 'Leipzig', 'ar': 'Leipzig', 'fr': 'Leipzig', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Mannheim': {'id': 274, 'en': 'Mannheim', 'ar': 'Mannheim', 'fr': 'Mannheim', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Munich': {'id': 36, 'en': 'Munich', 'ar': 'Munich', 'fr': 'Munich', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Nuremberg': {'id': 269, 'en': 'Nuremberg', 'ar': 'Nuremberg', 'fr': 'Nuremberg', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Stuttgart': {'id': 262, 'en': 'Stuttgart', 'ar': 'Stuttgart', 'fr': 'Stuttgart', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    'Wuppertal': {'id': 272, 'en': 'Wuppertal', 'ar': 'Wuppertal', 'fr': 'Wuppertal', 'lat': None, 'lon': None, 'country': 'Allemagne'},
    # ── Arabie-Saoudite (4 villes) ──
    'Djeddah': {'id': 328, 'en': 'Djeddah', 'ar': 'Djeddah', 'fr': 'Djeddah', 'lat': None, 'lon': None, 'country': 'Arabie-Saoudite'},
    'La Mecque': {'id': 13, 'en': 'La Mecque', 'ar': 'La Mecque', 'fr': 'La Mecque', 'lat': None, 'lon': None, 'country': 'Arabie-Saoudite'},
    'Médine': {'id': 12, 'en': 'Médine', 'ar': 'Médine', 'fr': 'Médine', 'lat': None, 'lon': None, 'country': 'Arabie-Saoudite'},
    'Riyad': {'id': 327, 'en': 'Riyad', 'ar': 'Riyad', 'fr': 'Riyad', 'lat': None, 'lon': None, 'country': 'Arabie-Saoudite'},
    # ── Australie (10 villes) ──
    'Adélaïde': {'id': 330, 'en': 'Adélaïde', 'ar': 'Adélaïde', 'fr': 'Adélaïde', 'lat': None, 'lon': None, 'country': 'Australie'},
    'Brisbane': {'id': 331, 'en': 'Brisbane', 'ar': 'Brisbane', 'fr': 'Brisbane', 'lat': None, 'lon': None, 'country': 'Australie'},
    'Canberra': {'id': 334, 'en': 'Canberra', 'ar': 'Canberra', 'fr': 'Canberra', 'lat': None, 'lon': None, 'country': 'Australie'},
    'Geelong': {'id': 333, 'en': 'Geelong', 'ar': 'Geelong', 'fr': 'Geelong', 'lat': None, 'lon': None, 'country': 'Australie'},
    'Hobart': {'id': 332, 'en': 'Hobart', 'ar': 'Hobart', 'fr': 'Hobart', 'lat': None, 'lon': None, 'country': 'Australie'},
    'Melbourne': {'id': 337, 'en': 'Melbourne', 'ar': 'Melbourne', 'fr': 'Melbourne', 'lat': None, 'lon': None, 'country': 'Australie'},
    'Newcastle': {'id': 335, 'en': 'Newcastle', 'ar': 'Newcastle', 'fr': 'Newcastle', 'lat': None, 'lon': None, 'country': 'Australie'},
    'Perth': {'id': 336, 'en': 'Perth', 'ar': 'Perth', 'fr': 'Perth', 'lat': None, 'lon': None, 'country': 'Australie'},
    'Sydney': {'id': 338, 'en': 'Sydney', 'ar': 'Sydney', 'fr': 'Sydney', 'lat': None, 'lon': None, 'country': 'Australie'},
    'Wollongong': {'id': 329, 'en': 'Wollongong', 'ar': 'Wollongong', 'fr': 'Wollongong', 'lat': None, 'lon': None, 'country': 'Australie'},
    # ── Autriche (3 villes) ──
    'Linz': {'id': 339, 'en': 'Linz', 'ar': 'Linz', 'fr': 'Linz', 'lat': None, 'lon': None, 'country': 'Autriche'},
    'Vienne': {'id': 340, 'en': 'Vienne', 'ar': 'Vienne', 'fr': 'Vienne', 'lat': None, 'lon': None, 'country': 'Autriche'},
    'Villach': {'id': 341, 'en': 'Villach', 'ar': 'Villach', 'fr': 'Villach', 'lat': None, 'lon': None, 'country': 'Autriche'},
    # ── Belgique (11 villes) ──
    'Anvers': {'id': 56, 'en': 'Anvers', 'ar': 'Anvers', 'fr': 'Anvers', 'lat': None, 'lon': None, 'country': 'Belgique'},
    'Bruxelles': {'id': 55, 'en': 'Bruxelles', 'ar': 'Bruxelles', 'fr': 'Bruxelles', 'lat': None, 'lon': None, 'country': 'Belgique'},
    'Charleroi': {'id': 57, 'en': 'Charleroi', 'ar': 'Charleroi', 'fr': 'Charleroi', 'lat': None, 'lon': None, 'country': 'Belgique'},
    'Gand': {'id': 63, 'en': 'Gand', 'ar': 'Gand', 'fr': 'Gand', 'lat': None, 'lon': None, 'country': 'Belgique'},
    'Hasselt': {'id': 58, 'en': 'Hasselt', 'ar': 'Hasselt', 'fr': 'Hasselt', 'lat': None, 'lon': None, 'country': 'Belgique'},
    'Liège': {'id': 61, 'en': 'Liège', 'ar': 'Liège', 'fr': 'Liège', 'lat': None, 'lon': None, 'country': 'Belgique'},
    'Mons': {'id': 64, 'en': 'Mons', 'ar': 'Mons', 'fr': 'Mons', 'lat': None, 'lon': None, 'country': 'Belgique'},
    'Namur': {'id': 59, 'en': 'Namur', 'ar': 'Namur', 'fr': 'Namur', 'lat': None, 'lon': None, 'country': 'Belgique'},
    'Renaix': {'id': 65, 'en': 'Renaix', 'ar': 'Renaix', 'fr': 'Renaix', 'lat': None, 'lon': None, 'country': 'Belgique'},
    'Tournai': {'id': 62, 'en': 'Tournai', 'ar': 'Tournai', 'fr': 'Tournai', 'lat': None, 'lon': None, 'country': 'Belgique'},
    'Verviers': {'id': 60, 'en': 'Verviers', 'ar': 'Verviers', 'fr': 'Verviers', 'lat': None, 'lon': None, 'country': 'Belgique'},
    # ── Cameroun (1 villes) ──
    'Yaoundé': {'id': 44, 'en': 'Yaoundé', 'ar': 'Yaoundé', 'fr': 'Yaoundé', 'lat': None, 'lon': None, 'country': 'Cameroun'},
    # ── Canada (5 villes) ──
    'Montréal': {'id': 51, 'en': 'Montréal', 'ar': 'Montréal', 'fr': 'Montréal', 'lat': None, 'lon': None, 'country': 'Canada'},
    'Ottawa': {'id': 52, 'en': 'Ottawa', 'ar': 'Ottawa', 'fr': 'Ottawa', 'lat': None, 'lon': None, 'country': 'Canada'},
    'Québec': {'id': 54, 'en': 'Québec', 'ar': 'Québec', 'fr': 'Québec', 'lat': None, 'lon': None, 'country': 'Canada'},
    'Toronto': {'id': 53, 'en': 'Toronto', 'ar': 'Toronto', 'fr': 'Toronto', 'lat': None, 'lon': None, 'country': 'Canada'},
    'Vancouver': {'id': 260, 'en': 'Vancouver', 'ar': 'Vancouver', 'fr': 'Vancouver', 'lat': None, 'lon': None, 'country': 'Canada'},
    # ── Côte d'ivoire (1 villes) ──
    'Abidjan': {'id': 43, 'en': 'Abidjan', 'ar': 'Abidjan', 'fr': 'Abidjan', 'lat': None, 'lon': None, 'country': "Côte d'ivoire"},
    # ── Danemark (1 villes) ──
    'Copenhague': {'id': 342, 'en': 'Copenhague', 'ar': 'Copenhague', 'fr': 'Copenhague', 'lat': None, 'lon': None, 'country': 'Danemark'},
    # ── Egypte (1 villes) ──
    'Le Caire': {'id': 42, 'en': 'Le Caire', 'ar': 'Le Caire', 'fr': 'Le Caire', 'lat': None, 'lon': None, 'country': 'Egypte'},
    # ── Emirats arabes unis (2 villes) ──
    'Abou Dhabi': {'id': 9, 'en': 'Abou Dhabi', 'ar': 'Abou Dhabi', 'fr': 'Abou Dhabi', 'lat': None, 'lon': None, 'country': 'Emirats arabes unis'},
    'Dubaï': {'id': 8, 'en': 'Dubaï', 'ar': 'Dubaï', 'fr': 'Dubaï', 'lat': None, 'lon': None, 'country': 'Emirats arabes unis'},
    # ── Espagne (54 villes) ──
    'Albacete': {'id': 240, 'en': 'Albacete', 'ar': 'Albacete', 'fr': 'Albacete', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Alcalá de Henares': {'id': 230, 'en': 'Alcalá de Henares', 'ar': 'Alcalá de Henares', 'fr': 'Alcalá de Henares', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Alcorcón': {'id': 239, 'en': 'Alcorcón', 'ar': 'Alcorcón', 'fr': 'Alcorcón', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Algeciras': {'id': 199, 'en': 'Algeciras', 'ar': 'Algeciras', 'fr': 'Algeciras', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Alicante': {'id': 210, 'en': 'Alicante', 'ar': 'Alicante', 'fr': 'Alicante', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Almería': {'id': 233, 'en': 'Almería', 'ar': 'Almería', 'fr': 'Almería', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Badajoz': {'id': 246, 'en': 'Badajoz', 'ar': 'Badajoz', 'fr': 'Badajoz', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Badalona': {'id': 224, 'en': 'Badalona', 'ar': 'Badalona', 'fr': 'Badalona', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Barcelona': {'id': 202, 'en': 'Barcelona', 'ar': 'Barcelona', 'fr': 'Barcelona', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Bilbao': {'id': 206, 'en': 'Bilbao', 'ar': 'Bilbao', 'fr': 'Bilbao', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Burgos': {'id': 238, 'en': 'Burgos', 'ar': 'Burgos', 'fr': 'Burgos', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Cartagena': {'id': 225, 'en': 'Cartagena', 'ar': 'Cartagena', 'fr': 'Cartagena', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Castellón de la Plana': {'id': 237, 'en': 'Castellón de la Plana', 'ar': 'Castellón de la Plana', 'fr': 'Castellón de la Plana', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Cádiz': {'id': 197, 'en': 'Cádiz', 'ar': 'Cádiz', 'fr': 'Cádiz', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Córdoba': {'id': 211, 'en': 'Córdoba', 'ar': 'Córdoba', 'fr': 'Córdoba', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Elche': {'id': 221, 'en': 'Elche', 'ar': 'Elche', 'fr': 'Elche', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Fuenlabrada': {'id': 232, 'en': 'Fuenlabrada', 'ar': 'Fuenlabrada', 'fr': 'Fuenlabrada', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Getafe': {'id': 241, 'en': 'Getafe', 'ar': 'Getafe', 'fr': 'Getafe', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Gijón': {'id': 216, 'en': 'Gijón', 'ar': 'Gijón', 'fr': 'Gijón', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Granada': {'id': 219, 'en': 'Granada', 'ar': 'Granada', 'fr': 'Granada', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Huelva': {'id': 245, 'en': 'Huelva', 'ar': 'Huelva', 'fr': 'Huelva', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Jaén': {'id': 198, 'en': 'Jaén', 'ar': 'Jaén', 'fr': 'Jaén', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Jerez de la Frontera': {'id': 228, 'en': 'Jerez de la Frontera', 'ar': 'Jerez de la Frontera', 'fr': 'Jerez de la Frontera', 'lat': None, 'lon': None, 'country': 'Espagne'},
    "L'hospitalet De Llobregat": {'id': 217, 'en': "L'hospitalet De Llobregat", 'ar': "L'hospitalet De Llobregat", 'fr': "L'hospitalet De Llobregat", 'lat': None, 'lon': None, 'country': 'Espagne'},
    'La Coruña': {'id': 218, 'en': 'La Coruña', 'ar': 'La Coruña', 'fr': 'La Coruña', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Las Palmas De Gran Canaria': {'id': 213, 'en': 'Las Palmas De Gran Canaria', 'ar': 'Las Palmas De Gran Canaria', 'fr': 'Las Palmas De Gran Canaria', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Leganés': {'id': 235, 'en': 'Leganés', 'ar': 'Leganés', 'fr': 'Leganés', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'León': {'id': 248, 'en': 'León', 'ar': 'León', 'fr': 'León', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Logroño': {'id': 243, 'en': 'Logroño', 'ar': 'Logroño', 'fr': 'Logroño', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Lérida': {'id': 195, 'en': 'Lérida', 'ar': 'Lérida', 'fr': 'Lérida', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Madrid': {'id': 203, 'en': 'Madrid', 'ar': 'Madrid', 'fr': 'Madrid', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Marbella': {'id': 196, 'en': 'Marbella', 'ar': 'Marbella', 'fr': 'Marbella', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Murcia': {'id': 209, 'en': 'Murcia', 'ar': 'Murcia', 'fr': 'Murcia', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Málaga': {'id': 207, 'en': 'Málaga', 'ar': 'Málaga', 'fr': 'Málaga', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Móstoles': {'id': 226, 'en': 'Móstoles', 'ar': 'Móstoles', 'fr': 'Móstoles', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Oviedo': {'id': 223, 'en': 'Oviedo', 'ar': 'Oviedo', 'fr': 'Oviedo', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Palma de Mallorca': {'id': 212, 'en': 'Palma de Mallorca', 'ar': 'Palma de Mallorca', 'fr': 'Palma de Mallorca', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Pamplona': {'id': 231, 'en': 'Pamplona', 'ar': 'Pamplona', 'fr': 'Pamplona', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Reus': {'id': 201, 'en': 'Reus', 'ar': 'Reus', 'fr': 'Reus', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Sabadell': {'id': 229, 'en': 'Sabadell', 'ar': 'Sabadell', 'fr': 'Sabadell', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Salamanca': {'id': 242, 'en': 'Salamanca', 'ar': 'Salamanca', 'fr': 'Salamanca', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'San Cristóbal de La Laguna': {'id': 244, 'en': 'San Cristóbal de La Laguna', 'ar': 'San Cristóbal de La Laguna', 'fr': 'San Cristóbal de La Laguna', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'San Sebastián': {'id': 234, 'en': 'San Sebastián', 'ar': 'San Sebastián', 'fr': 'San Sebastián', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Santa Cruz De Tenerife': {'id': 222, 'en': 'Santa Cruz De Tenerife', 'ar': 'Santa Cruz De Tenerife', 'fr': 'Santa Cruz De Tenerife', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Santander': {'id': 236, 'en': 'Santander', 'ar': 'Santander', 'fr': 'Santander', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Sevilla': {'id': 205, 'en': 'Sevilla', 'ar': 'Sevilla', 'fr': 'Sevilla', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Tarifa': {'id': 200, 'en': 'Tarifa', 'ar': 'Tarifa', 'fr': 'Tarifa', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Tarragona': {'id': 247, 'en': 'Tarragona', 'ar': 'Tarragona', 'fr': 'Tarragona', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Terrassa': {'id': 227, 'en': 'Terrassa', 'ar': 'Terrassa', 'fr': 'Terrassa', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Valencia': {'id': 204, 'en': 'Valencia', 'ar': 'Valencia', 'fr': 'Valencia', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Valladolid': {'id': 214, 'en': 'Valladolid', 'ar': 'Valladolid', 'fr': 'Valladolid', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Vigo': {'id': 215, 'en': 'Vigo', 'ar': 'Vigo', 'fr': 'Vigo', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Vitoria': {'id': 220, 'en': 'Vitoria', 'ar': 'Vitoria', 'fr': 'Vitoria', 'lat': None, 'lon': None, 'country': 'Espagne'},
    'Zaragoza': {'id': 208, 'en': 'Zaragoza', 'ar': 'Zaragoza', 'fr': 'Zaragoza', 'lat': None, 'lon': None, 'country': 'Espagne'},
    # ── Etats-Unis (13 villes) ──
    'Anchorage': {'id': 376, 'en': 'Anchorage', 'ar': 'Anchorage', 'fr': 'Anchorage', 'lat': None, 'lon': None, 'country': 'Etats-Unis'},
    'Atlanta': {'id': 380, 'en': 'Atlanta', 'ar': 'Atlanta', 'fr': 'Atlanta', 'lat': None, 'lon': None, 'country': 'Etats-Unis'},
    'Chicago': {'id': 48, 'en': 'Chicago', 'ar': 'Chicago', 'fr': 'Chicago', 'lat': None, 'lon': None, 'country': 'Etats-Unis'},
    'Dallas': {'id': 379, 'en': 'Dallas', 'ar': 'Dallas', 'fr': 'Dallas', 'lat': None, 'lon': None, 'country': 'Etats-Unis'},
    'Denver': {'id': 378, 'en': 'Denver', 'ar': 'Denver', 'fr': 'Denver', 'lat': None, 'lon': None, 'country': 'Etats-Unis'},
    'Détroit': {'id': 375, 'en': 'Détroit', 'ar': 'Détroit', 'fr': 'Détroit', 'lat': None, 'lon': None, 'country': 'Etats-Unis'},
    'Honolulu': {'id': 381, 'en': 'Honolulu', 'ar': 'Honolulu', 'fr': 'Honolulu', 'lat': None, 'lon': None, 'country': 'Etats-Unis'},
    'Houston': {'id': 377, 'en': 'Houston', 'ar': 'Houston', 'fr': 'Houston', 'lat': None, 'lon': None, 'country': 'Etats-Unis'},
    'Los Angeles': {'id': 49, 'en': 'Los Angeles', 'ar': 'Los Angeles', 'fr': 'Los Angeles', 'lat': None, 'lon': None, 'country': 'Etats-Unis'},
    'Miami': {'id': 47, 'en': 'Miami', 'ar': 'Miami', 'fr': 'Miami', 'lat': None, 'lon': None, 'country': 'Etats-Unis'},
    'New York': {'id': 45, 'en': 'New York', 'ar': 'New York', 'fr': 'New York', 'lat': None, 'lon': None, 'country': 'Etats-Unis'},
    'Seattle': {'id': 50, 'en': 'Seattle', 'ar': 'Seattle', 'fr': 'Seattle', 'lat': None, 'lon': None, 'country': 'Etats-Unis'},
    'Washington': {'id': 46, 'en': 'Washington', 'ar': 'Washington', 'fr': 'Washington', 'lat': None, 'lon': None, 'country': 'Etats-Unis'},
    # ── Finlande (4 villes) ──
    'Espoo': {'id': 344, 'en': 'Espoo', 'ar': 'Espoo', 'fr': 'Espoo', 'lat': None, 'lon': None, 'country': 'Finlande'},
    'Helsinki': {'id': 343, 'en': 'Helsinki', 'ar': 'Helsinki', 'fr': 'Helsinki', 'lat': None, 'lon': None, 'country': 'Finlande'},
    'Turku': {'id': 345, 'en': 'Turku', 'ar': 'Turku', 'fr': 'Turku', 'lat': None, 'lon': None, 'country': 'Finlande'},
    'Vantaa': {'id': 346, 'en': 'Vantaa', 'ar': 'Vantaa', 'fr': 'Vantaa', 'lat': None, 'lon': None, 'country': 'Finlande'},
    # ── France (86 villes) ──
    'Albi': {'id': 141, 'en': 'Albi', 'ar': 'Albi', 'fr': 'Albi', 'lat': None, 'lon': None, 'country': 'France'},
    'Amiens': {'id': 148, 'en': 'Amiens', 'ar': 'Amiens', 'fr': 'Amiens', 'lat': None, 'lon': None, 'country': 'France'},
    'Angers': {'id': 146, 'en': 'Angers', 'ar': 'Angers', 'fr': 'Angers', 'lat': None, 'lon': None, 'country': 'France'},
    'Angoulême': {'id': 181, 'en': 'Angoulême', 'ar': 'Angoulême', 'fr': 'Angoulême', 'lat': None, 'lon': None, 'country': 'France'},
    'Annecy': {'id': 186, 'en': 'Annecy', 'ar': 'Annecy', 'fr': 'Annecy', 'lat': None, 'lon': None, 'country': 'France'},
    'Arras': {'id': 165, 'en': 'Arras', 'ar': 'Arras', 'fr': 'Arras', 'lat': None, 'lon': None, 'country': 'France'},
    'Auxerre': {'id': 119, 'en': 'Auxerre', 'ar': 'Auxerre', 'fr': 'Auxerre', 'lat': None, 'lon': None, 'country': 'France'},
    'Avignon': {'id': 191, 'en': 'Avignon', 'ar': 'Avignon', 'fr': 'Avignon', 'lat': None, 'lon': None, 'country': 'France'},
    'Bar-le-Duc': {'id': 134, 'en': 'Bar-le-Duc', 'ar': 'Bar-le-Duc', 'fr': 'Bar-le-Duc', 'lat': None, 'lon': None, 'country': 'France'},
    'Bayeux': {'id': 132, 'en': 'Bayeux', 'ar': 'Bayeux', 'fr': 'Bayeux', 'lat': None, 'lon': None, 'country': 'France'},
    'Beauvais': {'id': 129, 'en': 'Beauvais', 'ar': 'Beauvais', 'fr': 'Beauvais', 'lat': None, 'lon': None, 'country': 'France'},
    'Belfort': {'id': 111, 'en': 'Belfort', 'ar': 'Belfort', 'fr': 'Belfort', 'lat': None, 'lon': None, 'country': 'France'},
    'Besançon': {'id': 149, 'en': 'Besançon', 'ar': 'Besançon', 'fr': 'Besançon', 'lat': None, 'lon': None, 'country': 'France'},
    'Bordeaux': {'id': 150, 'en': 'Bordeaux', 'ar': 'Bordeaux', 'fr': 'Bordeaux', 'lat': None, 'lon': None, 'country': 'France'},
    'Bourges': {'id': 147, 'en': 'Bourges', 'ar': 'Bourges', 'fr': 'Bourges', 'lat': None, 'lon': None, 'country': 'France'},
    'Caen': {'id': 131, 'en': 'Caen', 'ar': 'Caen', 'fr': 'Caen', 'lat': None, 'lon': None, 'country': 'France'},
    'Carcassonne': {'id': 143, 'en': 'Carcassonne', 'ar': 'Carcassonne', 'fr': 'Carcassonne', 'lat': None, 'lon': None, 'country': 'France'},
    'Chalon sur Marne': {'id': 122, 'en': 'Chalon sur Marne', 'ar': 'Chalon sur Marne', 'fr': 'Chalon sur Marne', 'lat': None, 'lon': None, 'country': 'France'},
    'Chalon sur Saône': {'id': 185, 'en': 'Chalon sur Saône', 'ar': 'Chalon sur Saône', 'fr': 'Chalon sur Saône', 'lat': None, 'lon': None, 'country': 'France'},
    'Chambéry': {'id': 187, 'en': 'Chambéry', 'ar': 'Chambéry', 'fr': 'Chambéry', 'lat': None, 'lon': None, 'country': 'France'},
    'Charleville-Mézières': {'id': 170, 'en': 'Charleville-Mézières', 'ar': 'Charleville-Mézières', 'fr': 'Charleville-Mézières', 'lat': None, 'lon': None, 'country': 'France'},
    'Chartres': {'id': 124, 'en': 'Chartres', 'ar': 'Chartres', 'fr': 'Chartres', 'lat': None, 'lon': None, 'country': 'France'},
    'Chaumont': {'id': 115, 'en': 'Chaumont', 'ar': 'Chaumont', 'fr': 'Chaumont', 'lat': None, 'lon': None, 'country': 'France'},
    'Cherbourg': {'id': 169, 'en': 'Cherbourg', 'ar': 'Cherbourg', 'fr': 'Cherbourg', 'lat': None, 'lon': None, 'country': 'France'},
    'Cholet': {'id': 145, 'en': 'Cholet', 'ar': 'Cholet', 'fr': 'Cholet', 'lat': None, 'lon': None, 'country': 'France'},
    'Château-Chinon': {'id': 174, 'en': 'Château-Chinon', 'ar': 'Château-Chinon', 'fr': 'Château-Chinon', 'lat': None, 'lon': None, 'country': 'France'},
    'Châtellerault': {'id': 127, 'en': 'Châtellerault', 'ar': 'Châtellerault', 'fr': 'Châtellerault', 'lat': None, 'lon': None, 'country': 'France'},
    'Clermont-Ferrand': {'id': 151, 'en': 'Clermont-Ferrand', 'ar': 'Clermont-Ferrand', 'fr': 'Clermont-Ferrand', 'lat': None, 'lon': None, 'country': 'France'},
    'Dieppe': {'id': 168, 'en': 'Dieppe', 'ar': 'Dieppe', 'fr': 'Dieppe', 'lat': None, 'lon': None, 'country': 'France'},
    'Dijon': {'id': 172, 'en': 'Dijon', 'ar': 'Dijon', 'fr': 'Dijon', 'lat': None, 'lon': None, 'country': 'France'},
    'Douai': {'id': 166, 'en': 'Douai', 'ar': 'Douai', 'fr': 'Douai', 'lat': None, 'lon': None, 'country': 'France'},
    'Draguignan': {'id': 189, 'en': 'Draguignan', 'ar': 'Draguignan', 'fr': 'Draguignan', 'lat': None, 'lon': None, 'country': 'France'},
    'Epinal': {'id': 113, 'en': 'Epinal', 'ar': 'Epinal', 'fr': 'Epinal', 'lat': None, 'lon': None, 'country': 'France'},
    'Foix': {'id': 138, 'en': 'Foix', 'ar': 'Foix', 'fr': 'Foix', 'lat': None, 'lon': None, 'country': 'France'},
    'Forbach': {'id': 110, 'en': 'Forbach', 'ar': 'Forbach', 'fr': 'Forbach', 'lat': None, 'lon': None, 'country': 'France'},
    'La Rochelle': {'id': 182, 'en': 'La Rochelle', 'ar': 'La Rochelle', 'fr': 'La Rochelle', 'lat': None, 'lon': None, 'country': 'France'},
    'Langres': {'id': 114, 'en': 'Langres', 'ar': 'Langres', 'fr': 'Langres', 'lat': None, 'lon': None, 'country': 'France'},
    'Laval': {'id': 116, 'en': 'Laval', 'ar': 'Laval', 'fr': 'Laval', 'lat': None, 'lon': None, 'country': 'France'},
    'Le Havre': {'id': 130, 'en': 'Le Havre', 'ar': 'Le Havre', 'fr': 'Le Havre', 'lat': None, 'lon': None, 'country': 'France'},
    'Le Mans': {'id': 118, 'en': 'Le Mans', 'ar': 'Le Mans', 'fr': 'Le Mans', 'lat': None, 'lon': None, 'country': 'France'},
    'Le Puy': {'id': 176, 'en': 'Le Puy', 'ar': 'Le Puy', 'fr': 'Le Puy', 'lat': None, 'lon': None, 'country': 'France'},
    'Lens': {'id': 164, 'en': 'Lens', 'ar': 'Lens', 'fr': 'Lens', 'lat': None, 'lon': None, 'country': 'France'},
    'Lille': {'id': 152, 'en': 'Lille', 'ar': 'Lille', 'fr': 'Lille', 'lat': None, 'lon': None, 'country': 'France'},
    'Limoges': {'id': 180, 'en': 'Limoges', 'ar': 'Limoges', 'fr': 'Limoges', 'lat': None, 'lon': None, 'country': 'France'},
    'Lyon': {'id': 153, 'en': 'Lyon', 'ar': 'Lyon', 'fr': 'Lyon', 'lat': None, 'lon': None, 'country': 'France'},
    'Macon': {'id': 126, 'en': 'Macon', 'ar': 'Macon', 'fr': 'Macon', 'lat': None, 'lon': None, 'country': 'France'},
    'Marseille': {'id': 154, 'en': 'Marseille', 'ar': 'Marseille', 'fr': 'Marseille', 'lat': None, 'lon': None, 'country': 'France'},
    'Meaux': {'id': 121, 'en': 'Meaux', 'ar': 'Meaux', 'fr': 'Meaux', 'lat': None, 'lon': None, 'country': 'France'},
    'Melun': {'id': 120, 'en': 'Melun', 'ar': 'Melun', 'fr': 'Melun', 'lat': None, 'lon': None, 'country': 'France'},
    'Metz': {'id': 155, 'en': 'Metz', 'ar': 'Metz', 'fr': 'Metz', 'lat': None, 'lon': None, 'country': 'France'},
    'Montluçon': {'id': 128, 'en': 'Montluçon', 'ar': 'Montluçon', 'fr': 'Montluçon', 'lat': None, 'lon': None, 'country': 'France'},
    'Montpellier': {'id': 140, 'en': 'Montpellier', 'ar': 'Montpellier', 'fr': 'Montpellier', 'lat': None, 'lon': None, 'country': 'France'},
    'Mulhouse': {'id': 156, 'en': 'Mulhouse', 'ar': 'Mulhouse', 'fr': 'Mulhouse', 'lat': None, 'lon': None, 'country': 'France'},
    'Nancy': {'id': 133, 'en': 'Nancy', 'ar': 'Nancy', 'fr': 'Nancy', 'lat': None, 'lon': None, 'country': 'France'},
    'Nantes': {'id': 144, 'en': 'Nantes', 'ar': 'Nantes', 'fr': 'Nantes', 'lat': None, 'lon': None, 'country': 'France'},
    'Nevers': {'id': 173, 'en': 'Nevers', 'ar': 'Nevers', 'fr': 'Nevers', 'lat': None, 'lon': None, 'country': 'France'},
    'Nice': {'id': 188, 'en': 'Nice', 'ar': 'Nice', 'fr': 'Nice', 'lat': None, 'lon': None, 'country': 'France'},
    'Niort': {'id': 125, 'en': 'Niort', 'ar': 'Niort', 'fr': 'Niort', 'lat': None, 'lon': None, 'country': 'France'},
    'Nogent sur Seine': {'id': 123, 'en': 'Nogent sur Seine', 'ar': 'Nogent sur Seine', 'fr': 'Nogent sur Seine', 'lat': None, 'lon': None, 'country': 'France'},
    'Nîmes': {'id': 192, 'en': 'Nîmes', 'ar': 'Nîmes', 'fr': 'Nîmes', 'lat': None, 'lon': None, 'country': 'France'},
    'Orléans': {'id': 157, 'en': 'Orléans', 'ar': 'Orléans', 'fr': 'Orléans', 'lat': None, 'lon': None, 'country': 'France'},
    'Paris': {'id': 158, 'en': 'Paris', 'ar': 'Paris', 'fr': 'Paris', 'lat': None, 'lon': None, 'country': 'France'},
    'Pau': {'id': 139, 'en': 'Pau', 'ar': 'Pau', 'fr': 'Pau', 'lat': None, 'lon': None, 'country': 'France'},
    'Perpignan': {'id': 142, 'en': 'Perpignan', 'ar': 'Perpignan', 'fr': 'Perpignan', 'lat': None, 'lon': None, 'country': 'France'},
    'Poitiers': {'id': 159, 'en': 'Poitiers', 'ar': 'Poitiers', 'fr': 'Poitiers', 'lat': None, 'lon': None, 'country': 'France'},
    'Pontarlier': {'id': 175, 'en': 'Pontarlier', 'ar': 'Pontarlier', 'fr': 'Pontarlier', 'lat': None, 'lon': None, 'country': 'France'},
    'Péronne': {'id': 171, 'en': 'Péronne', 'ar': 'Péronne', 'fr': 'Péronne', 'lat': None, 'lon': None, 'country': 'France'},
    'Reims': {'id': 194, 'en': 'Reims', 'ar': 'Reims', 'fr': 'Reims', 'lat': None, 'lon': None, 'country': 'France'},
    'Rennes': {'id': 117, 'en': 'Rennes', 'ar': 'Rennes', 'fr': 'Rennes', 'lat': None, 'lon': None, 'country': 'France'},
    'Roanne': {'id': 184, 'en': 'Roanne', 'ar': 'Roanne', 'fr': 'Roanne', 'lat': None, 'lon': None, 'country': 'France'},
    'Rodez': {'id': 177, 'en': 'Rodez', 'ar': 'Rodez', 'fr': 'Rodez', 'lat': None, 'lon': None, 'country': 'France'},
    'Rouen': {'id': 160, 'en': 'Rouen', 'ar': 'Rouen', 'fr': 'Rouen', 'lat': None, 'lon': None, 'country': 'France'},
    'Saint Etienne': {'id': 183, 'en': 'Saint Etienne', 'ar': 'Saint Etienne', 'fr': 'Saint Etienne', 'lat': None, 'lon': None, 'country': 'France'},
    'Saint-Dizier': {'id': 135, 'en': 'Saint-Dizier', 'ar': 'Saint-Dizier', 'fr': 'Saint-Dizier', 'lat': None, 'lon': None, 'country': 'France'},
    'Saint-Dié': {'id': 112, 'en': 'Saint-Dié', 'ar': 'Saint-Dié', 'fr': 'Saint-Dié', 'lat': None, 'lon': None, 'country': 'France'},
    'Strasbourg': {'id': 161, 'en': 'Strasbourg', 'ar': 'Strasbourg', 'fr': 'Strasbourg', 'lat': None, 'lon': None, 'country': 'France'},
    'Thionville': {'id': 109, 'en': 'Thionville', 'ar': 'Thionville', 'fr': 'Thionville', 'lat': None, 'lon': None, 'country': 'France'},
    'Toul': {'id': 137, 'en': 'Toul', 'ar': 'Toul', 'fr': 'Toul', 'lat': None, 'lon': None, 'country': 'France'},
    'Toulon': {'id': 190, 'en': 'Toulon', 'ar': 'Toulon', 'fr': 'Toulon', 'lat': None, 'lon': None, 'country': 'France'},
    'Toulouse': {'id': 162, 'en': 'Toulouse', 'ar': 'Toulouse', 'fr': 'Toulouse', 'lat': None, 'lon': None, 'country': 'France'},
    'Tours': {'id': 163, 'en': 'Tours', 'ar': 'Tours', 'fr': 'Tours', 'lat': None, 'lon': None, 'country': 'France'},
    'Troyes': {'id': 136, 'en': 'Troyes', 'ar': 'Troyes', 'fr': 'Troyes', 'lat': None, 'lon': None, 'country': 'France'},
    'Valence': {'id': 178, 'en': 'Valence', 'ar': 'Valence', 'fr': 'Valence', 'lat': None, 'lon': None, 'country': 'France'},
    'Valenciennes': {'id': 167, 'en': 'Valenciennes', 'ar': 'Valenciennes', 'fr': 'Valenciennes', 'lat': None, 'lon': None, 'country': 'France'},
    'Verdun': {'id': 193, 'en': 'Verdun', 'ar': 'Verdun', 'fr': 'Verdun', 'lat': None, 'lon': None, 'country': 'France'},
    'Vichy': {'id': 179, 'en': 'Vichy', 'ar': 'Vichy', 'fr': 'Vichy', 'lat': None, 'lon': None, 'country': 'France'},
    # ── Ghana (6 villes) ──
    'Accra': {'id': 34, 'en': 'Accra', 'ar': 'Accra', 'fr': 'Accra', 'lat': None, 'lon': None, 'country': 'Ghana'},
    'Kumasi': {'id': 348, 'en': 'Kumasi', 'ar': 'Kumasi', 'fr': 'Kumasi', 'lat': None, 'lon': None, 'country': 'Ghana'},
    'Sekondi': {'id': 350, 'en': 'Sekondi', 'ar': 'Sekondi', 'fr': 'Sekondi', 'lat': None, 'lon': None, 'country': 'Ghana'},
    'Takoradi': {'id': 347, 'en': 'Takoradi', 'ar': 'Takoradi', 'fr': 'Takoradi', 'lat': None, 'lon': None, 'country': 'Ghana'},
    'Tamale': {'id': 349, 'en': 'Tamale', 'ar': 'Tamale', 'fr': 'Tamale', 'lat': None, 'lon': None, 'country': 'Ghana'},
    'Tema': {'id': 351, 'en': 'Tema', 'ar': 'Tema', 'fr': 'Tema', 'lat': None, 'lon': None, 'country': 'Ghana'},
    # ── Irak (1 villes) ──
    'Bagdad': {'id': 33, 'en': 'Bagdad', 'ar': 'Bagdad', 'fr': 'Bagdad', 'lat': None, 'lon': None, 'country': 'Irak'},
    # ── Irlande (1 villes) ──
    'Dublin': {'id': 352, 'en': 'Dublin', 'ar': 'Dublin', 'fr': 'Dublin', 'lat': None, 'lon': None, 'country': 'Irlande'},
    # ── Italie (13 villes) ──
    'Bari': {'id': 251, 'en': 'Bari', 'ar': 'Bari', 'fr': 'Bari', 'lat': None, 'lon': None, 'country': 'Italie'},
    'Bologna': {'id': 26, 'en': 'Bologna', 'ar': 'Bologna', 'fr': 'Bologna', 'lat': None, 'lon': None, 'country': 'Italie'},
    'Cagliari': {'id': 253, 'en': 'Cagliari', 'ar': 'Cagliari', 'fr': 'Cagliari', 'lat': None, 'lon': None, 'country': 'Italie'},
    'Catania': {'id': 252, 'en': 'Catania', 'ar': 'Catania', 'fr': 'Catania', 'lat': None, 'lon': None, 'country': 'Italie'},
    'Firenze': {'id': 25, 'en': 'Firenze', 'ar': 'Firenze', 'fr': 'Firenze', 'lat': None, 'lon': None, 'country': 'Italie'},
    'Genoa': {'id': 31, 'en': 'Genoa', 'ar': 'Genoa', 'fr': 'Genoa', 'lat': None, 'lon': None, 'country': 'Italie'},
    'Milan': {'id': 28, 'en': 'Milan', 'ar': 'Milan', 'fr': 'Milan', 'lat': None, 'lon': None, 'country': 'Italie'},
    'Napoli': {'id': 30, 'en': 'Napoli', 'ar': 'Napoli', 'fr': 'Napoli', 'lat': None, 'lon': None, 'country': 'Italie'},
    'Palermo': {'id': 24, 'en': 'Palermo', 'ar': 'Palermo', 'fr': 'Palermo', 'lat': None, 'lon': None, 'country': 'Italie'},
    'Roma': {'id': 29, 'en': 'Roma', 'ar': 'Roma', 'fr': 'Roma', 'lat': None, 'lon': None, 'country': 'Italie'},
    'Turin': {'id': 27, 'en': 'Turin', 'ar': 'Turin', 'fr': 'Turin', 'lat': None, 'lon': None, 'country': 'Italie'},
    'Venezia': {'id': 32, 'en': 'Venezia', 'ar': 'Venezia', 'fr': 'Venezia', 'lat': None, 'lon': None, 'country': 'Italie'},
    'Verona': {'id': 249, 'en': 'Verona', 'ar': 'Verona', 'fr': 'Verona', 'lat': None, 'lon': None, 'country': 'Italie'},
    # ── Japon (10 villes) ──
    'Fukuoka': {'id': 356, 'en': 'Fukuoka', 'ar': 'Fukuoka', 'fr': 'Fukuoka', 'lat': None, 'lon': None, 'country': 'Japon'},
    'Hiroshima': {'id': 361, 'en': 'Hiroshima', 'ar': 'Hiroshima', 'fr': 'Hiroshima', 'lat': None, 'lon': None, 'country': 'Japon'},
    'Kawasaki': {'id': 359, 'en': 'Kawasaki', 'ar': 'Kawasaki', 'fr': 'Kawasaki', 'lat': None, 'lon': None, 'country': 'Japon'},
    'Kitakyushu': {'id': 353, 'en': 'Kitakyushu', 'ar': 'Kitakyushu', 'fr': 'Kitakyushu', 'lat': None, 'lon': None, 'country': 'Japon'},
    'Kobe': {'id': 358, 'en': 'Kobe', 'ar': 'Kobe', 'fr': 'Kobe', 'lat': None, 'lon': None, 'country': 'Japon'},
    'Kyoto': {'id': 360, 'en': 'Kyoto', 'ar': 'Kyoto', 'fr': 'Kyoto', 'lat': None, 'lon': None, 'country': 'Japon'},
    'Nagoya': {'id': 354, 'en': 'Nagoya', 'ar': 'Nagoya', 'fr': 'Nagoya', 'lat': None, 'lon': None, 'country': 'Japon'},
    'Osaka': {'id': 362, 'en': 'Osaka', 'ar': 'Osaka', 'fr': 'Osaka', 'lat': None, 'lon': None, 'country': 'Japon'},
    'Sapporo': {'id': 355, 'en': 'Sapporo', 'ar': 'Sapporo', 'fr': 'Sapporo', 'lat': None, 'lon': None, 'country': 'Japon'},
    'Tokyo': {'id': 357, 'en': 'Tokyo', 'ar': 'Tokyo', 'fr': 'Tokyo', 'lat': None, 'lon': None, 'country': 'Japon'},
    # ── Liban (1 villes) ──
    'Beyrouth': {'id': 23, 'en': 'Beyrouth', 'ar': 'Beyrouth', 'fr': 'Beyrouth', 'lat': None, 'lon': None, 'country': 'Liban'},
    # ── Libye (1 villes) ──
    'Tripoli': {'id': 261, 'en': 'Tripoli', 'ar': 'Tripoli', 'fr': 'Tripoli', 'lat': None, 'lon': None, 'country': 'Libye'},
    # ── Mali (1 villes) ──
    'Bamako': {'id': 22, 'en': 'Bamako', 'ar': 'Bamako', 'fr': 'Bamako', 'lat': None, 'lon': None, 'country': 'Mali'},
    # ── Mauritanie (1 villes) ──
    'Nouakchott': {'id': 21, 'en': 'Nouakchott', 'ar': 'Nouakchott', 'fr': 'Nouakchott', 'lat': None, 'lon': None, 'country': 'Mauritanie'},
    # ── Nigéria (7 villes) ──
    'Ibadan': {'id': 367, 'en': 'Ibadan', 'ar': 'Ibadan', 'fr': 'Ibadan', 'lat': None, 'lon': None, 'country': 'Nigéria'},
    'Ilesha': {'id': 366, 'en': 'Ilesha', 'ar': 'Ilesha', 'fr': 'Ilesha', 'lat': None, 'lon': None, 'country': 'Nigéria'},
    'Ilorin': {'id': 364, 'en': 'Ilorin', 'ar': 'Ilorin', 'fr': 'Ilorin', 'lat': None, 'lon': None, 'country': 'Nigéria'},
    'Kano': {'id': 365, 'en': 'Kano', 'ar': 'Kano', 'fr': 'Kano', 'lat': None, 'lon': None, 'country': 'Nigéria'},
    'Lagos': {'id': 15, 'en': 'Lagos', 'ar': 'Lagos', 'fr': 'Lagos', 'lat': None, 'lon': None, 'country': 'Nigéria'},
    'Onitsha': {'id': 363, 'en': 'Onitsha', 'ar': 'Onitsha', 'fr': 'Onitsha', 'lat': None, 'lon': None, 'country': 'Nigéria'},
    'Zaria': {'id': 368, 'en': 'Zaria', 'ar': 'Zaria', 'fr': 'Zaria', 'lat': None, 'lon': None, 'country': 'Nigéria'},
    # ── Norvège (1 villes) ──
    'Oslo': {'id': 386, 'en': 'Oslo', 'ar': 'Oslo', 'fr': 'Oslo', 'lat': None, 'lon': None, 'country': 'Norvège'},
    # ── Nouvelle-Zélande (4 villes) ──
    'Auckland': {'id': 385, 'en': 'Auckland', 'ar': 'Auckland', 'fr': 'Auckland', 'lat': None, 'lon': None, 'country': 'Nouvelle-Zélande'},
    'Dunedin': {'id': 383, 'en': 'Dunedin', 'ar': 'Dunedin', 'fr': 'Dunedin', 'lat': None, 'lon': None, 'country': 'Nouvelle-Zélande'},
    'Hamilton': {'id': 382, 'en': 'Hamilton', 'ar': 'Hamilton', 'fr': 'Hamilton', 'lat': None, 'lon': None, 'country': 'Nouvelle-Zélande'},
    'Wellington': {'id': 384, 'en': 'Wellington', 'ar': 'Wellington', 'fr': 'Wellington', 'lat': None, 'lon': None, 'country': 'Nouvelle-Zélande'},
    # ── Pays-Bas (21 villes) ──
    'Almere': {'id': 413, 'en': 'Almere', 'ar': 'Almere', 'fr': 'Almere', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Amersfoort': {'id': 422, 'en': 'Amersfoort', 'ar': 'Amersfoort', 'fr': 'Amersfoort', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Amsterdam': {'id': 16, 'en': 'Amsterdam', 'ar': 'Amsterdam', 'fr': 'Amsterdam', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Apeldoorn': {'id': 420, 'en': 'Apeldoorn', 'ar': 'Apeldoorn', 'fr': 'Apeldoorn', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Arnhem': {'id': 417, 'en': 'Arnhem', 'ar': 'Arnhem', 'fr': 'Arnhem', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Bois-le-Duc': {'id': 419, 'en': 'Bois-le-Duc', 'ar': 'Bois-le-Duc', 'fr': 'Bois-le-Duc', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Bréda': {'id': 414, 'en': 'Bréda', 'ar': 'Bréda', 'fr': 'Bréda', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Eindhoven': {'id': 20, 'en': 'Eindhoven', 'ar': 'Eindhoven', 'fr': 'Eindhoven', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Enschede': {'id': 421, 'en': 'Enschede', 'ar': 'Enschede', 'fr': 'Enschede', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Groningue': {'id': 412, 'en': 'Groningue', 'ar': 'Groningue', 'fr': 'Groningue', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Haarlem': {'id': 418, 'en': 'Haarlem', 'ar': 'Haarlem', 'fr': 'Haarlem', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Haarlemmermeer': {'id': 424, 'en': 'Haarlemmermeer', 'ar': 'Haarlemmermeer', 'fr': 'Haarlemmermeer', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'La Haye': {'id': 18, 'en': 'La Haye', 'ar': 'La Haye', 'fr': 'La Haye', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Maastricht': {'id': 416, 'en': 'Maastricht', 'ar': 'Maastricht', 'fr': 'Maastricht', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Nimègue': {'id': 415, 'en': 'Nimègue', 'ar': 'Nimègue', 'fr': 'Nimègue', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Rotterdam': {'id': 17, 'en': 'Rotterdam', 'ar': 'Rotterdam', 'fr': 'Rotterdam', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Tilburg': {'id': 258, 'en': 'Tilburg', 'ar': 'Tilburg', 'fr': 'Tilburg', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Utrecht': {'id': 19, 'en': 'Utrecht', 'ar': 'Utrecht', 'fr': 'Utrecht', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Zaanstad': {'id': 423, 'en': 'Zaanstad', 'ar': 'Zaanstad', 'fr': 'Zaanstad', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Zoetermeer': {'id': 426, 'en': 'Zoetermeer', 'ar': 'Zoetermeer', 'fr': 'Zoetermeer', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    'Zwolle': {'id': 425, 'en': 'Zwolle', 'ar': 'Zwolle', 'fr': 'Zwolle', 'lat': None, 'lon': None, 'country': 'Pays-Bas'},
    # ── Qatar (1 villes) ──
    'Doha': {'id': 14, 'en': 'Doha', 'ar': 'Doha', 'fr': 'Doha', 'lat': None, 'lon': None, 'country': 'Qatar'},
    # ── Royaume-Uni (9 villes) ──
    'Belfast': {'id': 396, 'en': 'Belfast', 'ar': 'Belfast', 'fr': 'Belfast', 'lat': None, 'lon': None, 'country': 'Royaume-Uni'},
    'Birmingham': {'id': 395, 'en': 'Birmingham', 'ar': 'Birmingham', 'fr': 'Birmingham', 'lat': None, 'lon': None, 'country': 'Royaume-Uni'},
    'Bristol': {'id': 393, 'en': 'Bristol', 'ar': 'Bristol', 'fr': 'Bristol', 'lat': None, 'lon': None, 'country': 'Royaume-Uni'},
    'Cardiff': {'id': 400, 'en': 'Cardiff', 'ar': 'Cardiff', 'fr': 'Cardiff', 'lat': None, 'lon': None, 'country': 'Royaume-Uni'},
    'Glasgow': {'id': 399, 'en': 'Glasgow', 'ar': 'Glasgow', 'fr': 'Glasgow', 'lat': None, 'lon': None, 'country': 'Royaume-Uni'},
    'Liverpool': {'id': 397, 'en': 'Liverpool', 'ar': 'Liverpool', 'fr': 'Liverpool', 'lat': None, 'lon': None, 'country': 'Royaume-Uni'},
    'London': {'id': 7, 'en': 'London', 'ar': 'London', 'fr': 'London', 'lat': None, 'lon': None, 'country': 'Royaume-Uni'},
    'Manchester': {'id': 398, 'en': 'Manchester', 'ar': 'Manchester', 'fr': 'Manchester', 'lat': None, 'lon': None, 'country': 'Royaume-Uni'},
    'Sheffield': {'id': 394, 'en': 'Sheffield', 'ar': 'Sheffield', 'fr': 'Sheffield', 'lat': None, 'lon': None, 'country': 'Royaume-Uni'},
    # ── Sénégal (1 villes) ──
    'Dakar': {'id': 11, 'en': 'Dakar', 'ar': 'Dakar', 'fr': 'Dakar', 'lat': None, 'lon': None, 'country': 'Sénégal'},
    # ── Suède (5 villes) ──
    'Borås': {'id': 390, 'en': 'Borås', 'ar': 'Borås', 'fr': 'Borås', 'lat': None, 'lon': None, 'country': 'Suède'},
    'Malmö': {'id': 391, 'en': 'Malmö', 'ar': 'Malmö', 'fr': 'Malmö', 'lat': None, 'lon': None, 'country': 'Suède'},
    'Stockholm': {'id': 389, 'en': 'Stockholm', 'ar': 'Stockholm', 'fr': 'Stockholm', 'lat': None, 'lon': None, 'country': 'Suède'},
    'Uppsala': {'id': 392, 'en': 'Uppsala', 'ar': 'Uppsala', 'fr': 'Uppsala', 'lat': None, 'lon': None, 'country': 'Suède'},
    'Örebro': {'id': 387, 'en': 'Örebro', 'ar': 'Örebro', 'fr': 'Örebro', 'lat': None, 'lon': None, 'country': 'Suède'},
    # ── Suisse (15 villes) ──
    'Berne': {'id': 6, 'en': 'Berne', 'ar': 'Berne', 'fr': 'Berne', 'lat': None, 'lon': None, 'country': 'Suisse'},
    'Bienne': {'id': 409, 'en': 'Bienne', 'ar': 'Bienne', 'fr': 'Bienne', 'lat': None, 'lon': None, 'country': 'Suisse'},
    'Bâle': {'id': 401, 'en': 'Bâle', 'ar': 'Bâle', 'fr': 'Bâle', 'lat': None, 'lon': None, 'country': 'Suisse'},
    'Fribourg': {'id': 403, 'en': 'Fribourg', 'ar': 'Fribourg', 'fr': 'Fribourg', 'lat': None, 'lon': None, 'country': 'Suisse'},
    'Genève': {'id': 5, 'en': 'Genève', 'ar': 'Genève', 'fr': 'Genève', 'lat': None, 'lon': None, 'country': 'Suisse'},
    'La Chaux-de-Fonds': {'id': 411, 'en': 'La Chaux-de-Fonds', 'ar': 'La Chaux-de-Fonds', 'fr': 'La Chaux-de-Fonds', 'lat': None, 'lon': None, 'country': 'Suisse'},
    'Lausanne': {'id': 3, 'en': 'Lausanne', 'ar': 'Lausanne', 'fr': 'Lausanne', 'lat': None, 'lon': None, 'country': 'Suisse'},
    'Lucerne': {'id': 404, 'en': 'Lucerne', 'ar': 'Lucerne', 'fr': 'Lucerne', 'lat': None, 'lon': None, 'country': 'Suisse'},
    'Lugano': {'id': 408, 'en': 'Lugano', 'ar': 'Lugano', 'fr': 'Lugano', 'lat': None, 'lon': None, 'country': 'Suisse'},
    'Montreux': {'id': 405, 'en': 'Montreux', 'ar': 'Montreux', 'fr': 'Montreux', 'lat': None, 'lon': None, 'country': 'Suisse'},
    'Neuchatel': {'id': 402, 'en': 'Neuchatel', 'ar': 'Neuchatel', 'fr': 'Neuchatel', 'lat': None, 'lon': None, 'country': 'Suisse'},
    'Saint-Gall': {'id': 407, 'en': 'Saint-Gall', 'ar': 'Saint-Gall', 'fr': 'Saint-Gall', 'lat': None, 'lon': None, 'country': 'Suisse'},
    'Thoune': {'id': 410, 'en': 'Thoune', 'ar': 'Thoune', 'fr': 'Thoune', 'lat': None, 'lon': None, 'country': 'Suisse'},
    'Winterthour': {'id': 406, 'en': 'Winterthour', 'ar': 'Winterthour', 'fr': 'Winterthour', 'lat': None, 'lon': None, 'country': 'Suisse'},
    'Zurich': {'id': 4, 'en': 'Zurich', 'ar': 'Zurich', 'fr': 'Zurich', 'lat': None, 'lon': None, 'country': 'Suisse'},
    # ── Syrie (1 villes) ──
    'Damas': {'id': 10, 'en': 'Damas', 'ar': 'Damas', 'fr': 'Damas', 'lat': None, 'lon': None, 'country': 'Syrie'},
    # ── Tunisie (24 villes) ──
    'Ariana': {'id': 304, 'en': 'Ariana', 'ar': 'Ariana', 'fr': 'Ariana', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Ben Arous': {'id': 306, 'en': 'Ben Arous', 'ar': 'Ben Arous', 'fr': 'Ben Arous', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Bizerte': {'id': 307, 'en': 'Bizerte', 'ar': 'Bizerte', 'fr': 'Bizerte', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Béja': {'id': 305, 'en': 'Béja', 'ar': 'Béja', 'fr': 'Béja', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Gabès': {'id': 308, 'en': 'Gabès', 'ar': 'Gabès', 'fr': 'Gabès', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Gafsa': {'id': 309, 'en': 'Gafsa', 'ar': 'Gafsa', 'fr': 'Gafsa', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Jendouba': {'id': 310, 'en': 'Jendouba', 'ar': 'Jendouba', 'fr': 'Jendouba', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Kairouan': {'id': 311, 'en': 'Kairouan', 'ar': 'Kairouan', 'fr': 'Kairouan', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Kasserine': {'id': 312, 'en': 'Kasserine', 'ar': 'Kasserine', 'fr': 'Kasserine', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Kébili': {'id': 313, 'en': 'Kébili', 'ar': 'Kébili', 'fr': 'Kébili', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'La Manouba': {'id': 316, 'en': 'La Manouba', 'ar': 'La Manouba', 'fr': 'La Manouba', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Le Kef': {'id': 314, 'en': 'Le Kef', 'ar': 'Le Kef', 'fr': 'Le Kef', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Mahdia': {'id': 315, 'en': 'Mahdia', 'ar': 'Mahdia', 'fr': 'Mahdia', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Monastir': {'id': 318, 'en': 'Monastir', 'ar': 'Monastir', 'fr': 'Monastir', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Médenine': {'id': 317, 'en': 'Médenine', 'ar': 'Médenine', 'fr': 'Médenine', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Nabeul': {'id': 319, 'en': 'Nabeul', 'ar': 'Nabeul', 'fr': 'Nabeul', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Sfax': {'id': 320, 'en': 'Sfax', 'ar': 'Sfax', 'fr': 'Sfax', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Sidi Bouzid': {'id': 321, 'en': 'Sidi Bouzid', 'ar': 'Sidi Bouzid', 'fr': 'Sidi Bouzid', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Siliana': {'id': 322, 'en': 'Siliana', 'ar': 'Siliana', 'fr': 'Siliana', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Sousse': {'id': 323, 'en': 'Sousse', 'ar': 'Sousse', 'fr': 'Sousse', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Tataouine': {'id': 324, 'en': 'Tataouine', 'ar': 'Tataouine', 'fr': 'Tataouine', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Tozeur': {'id': 325, 'en': 'Tozeur', 'ar': 'Tozeur', 'fr': 'Tozeur', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Tunis': {'id': 1, 'en': 'Tunis', 'ar': 'Tunis', 'fr': 'Tunis', 'lat': None, 'lon': None, 'country': 'Tunisie'},
    'Zaghouan': {'id': 326, 'en': 'Zaghouan', 'ar': 'Zaghouan', 'fr': 'Zaghouan', 'lat': None, 'lon': None, 'country': 'Tunisie'},

}
